/*
 Highcharts JS v8.2.2 (2020-10-27)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(n){c(n);c.Highcharts=n;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function n(c,p,u,e){c.hasOwnProperty(p)||(c[p]=e.apply(null,u))}c=c?c._modules:{};n(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],
function(c,p,u,e){var x=e.defined,k=e.extend,n=e.isArray,t=e.isNumber,q=e.pick,w=c.seriesTypes.area.prototype,a=c.seriesTypes.column.prototype,r=u.prototype,v=p.Series.prototype;c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",
deferTranslatePolar:!0,toYData:function(g){return[g.low,g.high]},highToXY:function(g){var d=this.chart,b=this.xAxis.postTranslate(g.rectPlotX,this.yAxis.len-g.plotHigh);g.plotHighX=b.x-d.plotLeft;g.plotHigh=b.y-d.plotTop;g.plotLowX=g.plotX},translate:function(){var g=this,d=g.yAxis,b=!!g.modifyValue;w.translate.apply(g);g.points.forEach(function(a){var c=a.high,f=a.plotY;a.isNull?a.plotY=null:(a.plotLow=f,a.plotHigh=d.translate(b?g.modifyValue(c,a):c,0,1,0,1),b&&(a.yBottom=a.plotHigh))});this.chart.polar&&
this.points.forEach(function(b){g.highToXY(b);b.tooltipPos=[(b.plotHighX+b.plotLowX)/2,(b.plotHigh+b.plotLow)/2]})},getGraphPath:function(a){var d=[],b=[],g,c=w.getGraphPath;var f=this.options;var r=this.chart.polar,v=r&&!1!==f.connectEnds,h=f.connectNulls,l=f.step;a=a||this.points;for(g=a.length;g--;){var e=a[g];var k=r?{plotX:e.rectPlotX,plotY:e.yBottom,doCurve:!1}:{plotX:e.plotX,plotY:e.plotY,doCurve:!1};e.isNull||v||h||a[g+1]&&!a[g+1].isNull||b.push(k);var p={polarPlotY:e.polarPlotY,rectPlotX:e.rectPlotX,
yBottom:e.yBottom,plotX:q(e.plotHighX,e.plotX),plotY:e.plotHigh,isNull:e.isNull};b.push(p);d.push(p);e.isNull||v||h||a[g-1]&&!a[g-1].isNull||b.push(k)}a=c.call(this,a);l&&(!0===l&&(l="left"),f.step={left:"right",center:"center",right:"left"}[l]);d=c.call(this,d);b=c.call(this,b);f.step=l;f=[].concat(a,d);!this.chart.polar&&b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.graphPath=f;this.areaPath=a.concat(b);f.isArea=!0;f.xMap=a.xMap;this.areaPath.xMap=a.xMap;return f},drawDataLabels:function(){var a=
this.points,d=a.length,b,c=[],e=this.options.dataLabels,f,r=this.chart.inverted;if(n(e)){var m=e[0]||{enabled:!1};var h=e[1]||{enabled:!1}}else m=k({},e),m.x=e.xHigh,m.y=e.yHigh,h=k({},e),h.x=e.xLow,h.y=e.yLow;if(m.enabled||this._hasPointLabels){for(b=d;b--;)if(f=a[b]){var l=m.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow;f.y=f.high;f._plotY=f.plotY;f.plotY=f.plotHigh;c[b]=f.dataLabel;f.dataLabel=f.dataLabelUpper;f.below=l;r?m.align||(m.align=l?"right":"left"):m.verticalAlign||(m.verticalAlign=
l?"top":"bottom")}this.options.dataLabels=m;v.drawDataLabels&&v.drawDataLabels.apply(this,arguments);for(b=d;b--;)if(f=a[b])f.dataLabelUpper=f.dataLabel,f.dataLabel=c[b],delete f.dataLabels,f.y=f.low,f.plotY=f._plotY}if(h.enabled||this._hasPointLabels){for(b=d;b--;)if(f=a[b])l=h.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow,f.below=!l,r?h.align||(h.align=l?"left":"right"):h.verticalAlign||(h.verticalAlign=l?"bottom":"top");this.options.dataLabels=h;v.drawDataLabels&&v.drawDataLabels.apply(this,
arguments)}if(m.enabled)for(b=d;b--;)if(f=a[b])f.dataLabels=[f.dataLabelUpper,f.dataLabel].filter(function(a){return!!a});this.options.dataLabels=e},alignDataLabel:function(){a.alignDataLabel.apply(this,arguments)},drawPoints:function(){var a=this.points.length,d;v.drawPoints.apply(this,arguments);for(d=0;d<a;){var b=this.points[d];b.origProps={plotY:b.plotY,plotX:b.plotX,isInside:b.isInside,negative:b.negative,zone:b.zone,y:b.y};b.lowerGraphic=b.graphic;b.graphic=b.upperGraphic;b.plotY=b.plotHigh;
x(b.plotHighX)&&(b.plotX=b.plotHighX);b.y=b.high;b.negative=b.high<(this.options.threshold||0);b.zone=this.zones.length&&b.getZone();this.chart.polar||(b.isInside=b.isTopInside="undefined"!==typeof b.plotY&&0<=b.plotY&&b.plotY<=this.yAxis.len&&0<=b.plotX&&b.plotX<=this.xAxis.len);d++}v.drawPoints.apply(this,arguments);for(d=0;d<a;)b=this.points[d],b.upperGraphic=b.graphic,b.graphic=b.lowerGraphic,k(b,b.origProps),delete b.origProps,d++},setStackedPoints:p.noop},{setState:function(){var a=this.state,
d=this.series,b=d.chart.polar;x(this.plotHigh)||(this.plotHigh=d.yAxis.toPixels(this.high,!0));x(this.plotLow)||(this.plotLow=this.plotY=d.yAxis.toPixels(this.low,!0));d.stateMarkerGraphic&&(d.lowerStateMarkerGraphic=d.stateMarkerGraphic,d.stateMarkerGraphic=d.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);r.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;b&&(this.plotX=this.plotLowX);
d.stateMarkerGraphic&&(d.upperStateMarkerGraphic=d.stateMarkerGraphic,d.stateMarkerGraphic=d.lowerStateMarkerGraphic,d.lowerStateMarkerGraphic=void 0);r.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,d=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(d=r.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(d=d.concat(r.haloPath.apply(this,arguments)));return d},destroyElements:function(){["lowerGraphic",
"upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return r.destroyElements.apply(this,arguments)},isValid:function(){return t(this.low)&&t(this.high)}});""});n(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,p,u,e){p=p.noop;u=u.defaultOptions;var n=e.clamp,k=e.merge,y=e.pick,t=c.seriesTypes.arearange.prototype,q=c.seriesTypes.column.prototype;c.seriesType("columnrange",
"arearange",k(u.plotOptions.column,u.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){k(!0,arguments[0],{stacking:void 0});return t.setOptions.apply(this,arguments)},translate:function(){var c=this,a=c.yAxis,e=c.xAxis,v=e.startAngleRad,g,d=c.chart,b=c.xAxis.isRadial,k=Math.max(d.chartWidth,d.chartHeight)+999,p;q.translate.apply(c);c.points.forEach(function(f){var r=f.shapeArgs,m=c.options.minPointLength;f.plotHigh=p=n(a.translate(f.high,0,1,0,1),
-k,k);f.plotLow=n(f.plotY,-k,k);var h=p;var l=y(f.rectPlotY,f.plotY)-p;Math.abs(l)<m?(m-=l,l+=m,h-=m/2):0>l&&(l*=-1,h-=l);b?(g=f.barX+v,f.shapeType="arc",f.shapeArgs=c.polarArc(h+l,h,g,g+f.pointWidth)):(r.height=l,r.y=h,f.tooltipPos=d.inverted?[a.len+a.pos-d.plotLeft-h-l/2,e.len+e.pos-d.plotTop-r.x-r.width/2,l]:[e.left-d.plotLeft+r.x+r.width/2,a.pos-d.plotTop+h+l/2,l])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:p,getSymbol:p,crispCol:function(){return q.crispCol.apply(this,
arguments)},drawPoints:function(){return q.drawPoints.apply(this,arguments)},drawTracker:function(){return q.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return q.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return q.pointAttribs.apply(this,arguments)},animate:function(){return q.animate.apply(this,arguments)},polarArc:function(){return q.polarArc.apply(this,arguments)},translate3dPoints:function(){return q.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return q.translate3dShapes.apply(this,
arguments)}},{setState:q.pointClass.prototype.setState});""});n(c,"Series/DumbbellSeries.js",[c["Core/Series/Series.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,p,n,e){var u=e.extend,k=e.pick,y=n.Series.prototype;e=c.seriesTypes;var t=e.arearange.prototype,q=e.column.prototype,w=t.pointClass.prototype;c.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,
crisp:!1,pointPadding:.1,lowColor:"#333333",states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:n.TrackerMixin.drawTrackerPoint,drawGraph:n.noop,crispCol:q.crispCol,getConnectorAttribs:function(a){var c=this.chart,e=a.options,g=this.options,d=this.xAxis,b=this.yAxis,n=k(e.connectorWidth,g.connectorWidth),q=k(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),f=k(g.states&&g.states.hover&&g.states.hover.connectorWidthPlus,
1),t=k(e.dashStyle,g.dashStyle),m=k(a.plotLow,a.plotY),h=b.toPixels(g.threshold||0,!0);h=k(a.plotHigh,c.inverted?b.len-h:h);a.state&&(n+=f);0>m?m=0:m>=b.len&&(m=b.len);0>h?h=0:h>=b.len&&(h=b.len);if(0>a.plotX||a.plotX>d.len)n=0;a.upperGraphic&&(d={y:a.y,zone:a.zone},a.y=a.high,a.zone=a.zone?a.getZone():void 0,q=k(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),u(a,d));a={d:p.prototype.crispLine([["M",a.plotX,m],["L",a.plotX,h]],n,"ceil")};c.styledMode||(a.stroke=q,a["stroke-width"]=
n,t&&(a.dashstyle=t));return a},drawConnector:function(a){var c=k(this.options.animationLimit,250);c=a.connector&&this.chart.pointCount<c?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));a.connector[c](this.getConnectorAttribs(a))},getColumnMetrics:function(){var a=q.getColumnMetrics.apply(this,arguments);a.offset+=a.width/2;return a},translatePoint:t.translate,setShapeArgs:e.columnrange.prototype.translate,
translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(a){var c=a.shapeArgs,e=a.pointWidth;a.plotX=c.x;c.x=a.plotX-e/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:t.drawPoints,drawPoints:function(){var a=this.chart,c=this.points.length,e=this.lowColor=this.options.lowColor,g=0;for(this.seriesDrawPoints.apply(this,arguments);g<c;){var d=this.points[g];this.drawConnector(d);d.upperGraphic&&
(d.upperGraphic.element.point=d,d.upperGraphic.addClass("highcharts-lollipop-high"));d.connector.element.point=d;if(d.lowerGraphic){var b=d.zone&&d.zone.color;b=k(d.options.lowColor,e,d.options.color,b,d.color,this.color);a.styledMode||d.lowerGraphic.attr({fill:b});d.lowerGraphic.addClass("highcharts-lollipop-low")}g++}},markerAttribs:function(){var a=t.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a},pointAttribs:function(a,c){var e=y.pointAttribs.apply(this,
arguments);"hover"===c&&delete e.fill;return e}},{destroyElements:w.destroyElements,isValid:w.isValid,pointSetState:w.setState,setState:function(){var a=this.series,c=a.chart,e=a.options.marker,g=this.options,d=k(g.lowColor,a.options.lowColor,g.color,this.zone&&this.zone.color,this.color,a.color),b="attr";this.pointSetState.apply(this,arguments);this.state||(b="animate",this.lowerGraphic&&!c.styledMode&&(this.lowerGraphic.attr({fill:d}),this.upperGraphic&&(c={y:this.y,zone:this.zone},this.y=this.high,
this.zone=this.zone?this.getZone():void 0,e=k(this.marker?this.marker.fillColor:void 0,e?e.fillColor:void 0,g.color,this.zone?this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:e}),u(this,c))));this.connector[b](a.getConnectorAttribs(this))}});""});n(c,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map