/*
 Highcharts JS v8.2.2 (2020-10-27)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/lollipop",["highcharts"],function(p){c(p);c.Highcharts=p;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function p(c,n,q,d){c.hasOwnProperty(n)||(c[n]=d.apply(null,q))}c=c?c._modules:{};p(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],
function(c,n,q,d){var w=d.defined,l=d.extend,u=d.isArray,t=d.isNumber,g=d.pick,x=c.seriesTypes.area.prototype,a=c.seriesTypes.column.prototype,r=q.prototype,v=n.Series.prototype;c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",
deferTranslatePolar:!0,toYData:function(h){return[h.low,h.high]},highToXY:function(h){var e=this.chart,b=this.xAxis.postTranslate(h.rectPlotX,this.yAxis.len-h.plotHigh);h.plotHighX=b.x-e.plotLeft;h.plotHigh=b.y-e.plotTop;h.plotLowX=h.plotX},translate:function(){var h=this,e=h.yAxis,b=!!h.modifyValue;x.translate.apply(h);h.points.forEach(function(a){var c=a.high,f=a.plotY;a.isNull?a.plotY=null:(a.plotLow=f,a.plotHigh=e.translate(b?h.modifyValue(c,a):c,0,1,0,1),b&&(a.yBottom=a.plotHigh))});this.chart.polar&&
this.points.forEach(function(b){h.highToXY(b);b.tooltipPos=[(b.plotHighX+b.plotLowX)/2,(b.plotHigh+b.plotLow)/2]})},getGraphPath:function(a){var e=[],b=[],h,c=x.getGraphPath;var f=this.options;var r=this.chart.polar,v=r&&!1!==f.connectEnds,k=f.connectNulls,m=f.step;a=a||this.points;for(h=a.length;h--;){var d=a[h];var l=r?{plotX:d.rectPlotX,plotY:d.yBottom,doCurve:!1}:{plotX:d.plotX,plotY:d.plotY,doCurve:!1};d.isNull||v||k||a[h+1]&&!a[h+1].isNull||b.push(l);var n={polarPlotY:d.polarPlotY,rectPlotX:d.rectPlotX,
yBottom:d.yBottom,plotX:g(d.plotHighX,d.plotX),plotY:d.plotHigh,isNull:d.isNull};b.push(n);e.push(n);d.isNull||v||k||a[h-1]&&!a[h-1].isNull||b.push(l)}a=c.call(this,a);m&&(!0===m&&(m="left"),f.step={left:"right",center:"center",right:"left"}[m]);e=c.call(this,e);b=c.call(this,b);f.step=m;f=[].concat(a,e);!this.chart.polar&&b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.graphPath=f;this.areaPath=a.concat(b);f.isArea=!0;f.xMap=a.xMap;this.areaPath.xMap=a.xMap;return f},drawDataLabels:function(){var a=
this.points,e=a.length,b,c=[],d=this.options.dataLabels,f,r=this.chart.inverted;if(u(d)){var g=d[0]||{enabled:!1};var k=d[1]||{enabled:!1}}else g=l({},d),g.x=d.xHigh,g.y=d.yHigh,k=l({},d),k.x=d.xLow,k.y=d.yLow;if(g.enabled||this._hasPointLabels){for(b=e;b--;)if(f=a[b]){var m=g.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow;f.y=f.high;f._plotY=f.plotY;f.plotY=f.plotHigh;c[b]=f.dataLabel;f.dataLabel=f.dataLabelUpper;f.below=m;r?g.align||(g.align=m?"right":"left"):g.verticalAlign||(g.verticalAlign=
m?"top":"bottom")}this.options.dataLabels=g;v.drawDataLabels&&v.drawDataLabels.apply(this,arguments);for(b=e;b--;)if(f=a[b])f.dataLabelUpper=f.dataLabel,f.dataLabel=c[b],delete f.dataLabels,f.y=f.low,f.plotY=f._plotY}if(k.enabled||this._hasPointLabels){for(b=e;b--;)if(f=a[b])m=k.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow,f.below=!m,r?k.align||(k.align=m?"left":"right"):k.verticalAlign||(k.verticalAlign=m?"bottom":"top");this.options.dataLabels=k;v.drawDataLabels&&v.drawDataLabels.apply(this,
arguments)}if(g.enabled)for(b=e;b--;)if(f=a[b])f.dataLabels=[f.dataLabelUpper,f.dataLabel].filter(function(a){return!!a});this.options.dataLabels=d},alignDataLabel:function(){a.alignDataLabel.apply(this,arguments)},drawPoints:function(){var a=this.points.length,e;v.drawPoints.apply(this,arguments);for(e=0;e<a;){var b=this.points[e];b.origProps={plotY:b.plotY,plotX:b.plotX,isInside:b.isInside,negative:b.negative,zone:b.zone,y:b.y};b.lowerGraphic=b.graphic;b.graphic=b.upperGraphic;b.plotY=b.plotHigh;
w(b.plotHighX)&&(b.plotX=b.plotHighX);b.y=b.high;b.negative=b.high<(this.options.threshold||0);b.zone=this.zones.length&&b.getZone();this.chart.polar||(b.isInside=b.isTopInside="undefined"!==typeof b.plotY&&0<=b.plotY&&b.plotY<=this.yAxis.len&&0<=b.plotX&&b.plotX<=this.xAxis.len);e++}v.drawPoints.apply(this,arguments);for(e=0;e<a;)b=this.points[e],b.upperGraphic=b.graphic,b.graphic=b.lowerGraphic,l(b,b.origProps),delete b.origProps,e++},setStackedPoints:n.noop},{setState:function(){var a=this.state,
e=this.series,b=e.chart.polar;w(this.plotHigh)||(this.plotHigh=e.yAxis.toPixels(this.high,!0));w(this.plotLow)||(this.plotLow=this.plotY=e.yAxis.toPixels(this.low,!0));e.stateMarkerGraphic&&(e.lowerStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);r.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;b&&(this.plotX=this.plotLowX);
e.stateMarkerGraphic&&(e.upperStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.lowerStateMarkerGraphic,e.lowerStateMarkerGraphic=void 0);r.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,e=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(e=r.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(e=e.concat(r.haloPath.apply(this,arguments)));return e},destroyElements:function(){["lowerGraphic",
"upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return r.destroyElements.apply(this,arguments)},isValid:function(){return t(this.low)&&t(this.high)}});""});p(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,n,q,d){n=n.noop;q=q.defaultOptions;var w=d.clamp,l=d.merge,u=d.pick,t=c.seriesTypes.arearange.prototype,g=c.seriesTypes.column.prototype;c.seriesType("columnrange",
"arearange",l(q.plotOptions.column,q.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){l(!0,arguments[0],{stacking:void 0});return t.setOptions.apply(this,arguments)},translate:function(){var c=this,a=c.yAxis,d=c.xAxis,v=d.startAngleRad,h,e=c.chart,b=c.xAxis.isRadial,l=Math.max(e.chartWidth,e.chartHeight)+999,n;g.translate.apply(c);c.points.forEach(function(f){var g=f.shapeArgs,r=c.options.minPointLength;f.plotHigh=n=w(a.translate(f.high,0,1,0,1),
-l,l);f.plotLow=w(f.plotY,-l,l);var k=n;var m=u(f.rectPlotY,f.plotY)-n;Math.abs(m)<r?(r-=m,m+=r,k-=r/2):0>m&&(m*=-1,k-=m);b?(h=f.barX+v,f.shapeType="arc",f.shapeArgs=c.polarArc(k+m,k,h,h+f.pointWidth)):(g.height=m,g.y=k,f.tooltipPos=e.inverted?[a.len+a.pos-e.plotLeft-k-m/2,d.len+d.pos-e.plotTop-g.x-g.width/2,m]:[d.left-e.plotLeft+g.x+g.width/2,a.pos-e.plotTop+k+m/2,m])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:n,getSymbol:n,crispCol:function(){return g.crispCol.apply(this,
arguments)},drawPoints:function(){return g.drawPoints.apply(this,arguments)},drawTracker:function(){return g.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return g.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return g.pointAttribs.apply(this,arguments)},animate:function(){return g.animate.apply(this,arguments)},polarArc:function(){return g.polarArc.apply(this,arguments)},translate3dPoints:function(){return g.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return g.translate3dShapes.apply(this,
arguments)}},{setState:g.pointClass.prototype.setState});""});p(c,"Series/DumbbellSeries.js",[c["Core/Series/Series.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,n,q,d){var w=d.extend,l=d.pick,u=q.Series.prototype;d=c.seriesTypes;var t=d.arearange.prototype,g=d.column.prototype,p=t.pointClass.prototype;c.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,
crisp:!1,pointPadding:.1,lowColor:"#333333",states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:q.TrackerMixin.drawTrackerPoint,drawGraph:q.noop,crispCol:g.crispCol,getConnectorAttribs:function(a){var c=this.chart,d=a.options,h=this.options,e=this.xAxis,b=this.yAxis,g=l(d.connectorWidth,h.connectorWidth),q=l(d.connectorColor,h.connectorColor,d.color,a.zone?a.zone.color:void 0,a.color),f=l(h.states&&h.states.hover&&h.states.hover.connectorWidthPlus,
1),t=l(d.dashStyle,h.dashStyle),p=l(a.plotLow,a.plotY),k=b.toPixels(h.threshold||0,!0);k=l(a.plotHigh,c.inverted?b.len-k:k);a.state&&(g+=f);0>p?p=0:p>=b.len&&(p=b.len);0>k?k=0:k>=b.len&&(k=b.len);if(0>a.plotX||a.plotX>e.len)g=0;a.upperGraphic&&(e={y:a.y,zone:a.zone},a.y=a.high,a.zone=a.zone?a.getZone():void 0,q=l(d.connectorColor,h.connectorColor,d.color,a.zone?a.zone.color:void 0,a.color),w(a,e));a={d:n.prototype.crispLine([["M",a.plotX,p],["L",a.plotX,k]],g,"ceil")};c.styledMode||(a.stroke=q,a["stroke-width"]=
g,t&&(a.dashstyle=t));return a},drawConnector:function(a){var c=l(this.options.animationLimit,250);c=a.connector&&this.chart.pointCount<c?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));a.connector[c](this.getConnectorAttribs(a))},getColumnMetrics:function(){var a=g.getColumnMetrics.apply(this,arguments);a.offset+=a.width/2;return a},translatePoint:t.translate,setShapeArgs:d.columnrange.prototype.translate,
translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(a){var c=a.shapeArgs,d=a.pointWidth;a.plotX=c.x;c.x=a.plotX-d/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:t.drawPoints,drawPoints:function(){var a=this.chart,c=this.points.length,d=this.lowColor=this.options.lowColor,g=0;for(this.seriesDrawPoints.apply(this,arguments);g<c;){var e=this.points[g];this.drawConnector(e);e.upperGraphic&&
(e.upperGraphic.element.point=e,e.upperGraphic.addClass("highcharts-lollipop-high"));e.connector.element.point=e;if(e.lowerGraphic){var b=e.zone&&e.zone.color;b=l(e.options.lowColor,d,e.options.color,b,e.color,this.color);a.styledMode||e.lowerGraphic.attr({fill:b});e.lowerGraphic.addClass("highcharts-lollipop-low")}g++}},markerAttribs:function(){var a=t.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a},pointAttribs:function(a,c){var d=u.pointAttribs.apply(this,
arguments);"hover"===c&&delete d.fill;return d}},{destroyElements:p.destroyElements,isValid:p.isValid,pointSetState:p.setState,setState:function(){var a=this.series,c=a.chart,d=a.options.marker,g=this.options,e=l(g.lowColor,a.options.lowColor,g.color,this.zone&&this.zone.color,this.color,a.color),b="attr";this.pointSetState.apply(this,arguments);this.state||(b="animate",this.lowerGraphic&&!c.styledMode&&(this.lowerGraphic.attr({fill:e}),this.upperGraphic&&(c={y:this.y,zone:this.zone},this.y=this.high,
this.zone=this.zone?this.getZone():void 0,d=l(this.marker?this.marker.fillColor:void 0,d?d.fillColor:void 0,g.color,this.zone?this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:d}),w(this,c))));this.connector[b](a.getConnectorAttribs(this))}});""});p(c,"Series/LollipopSeries.js",[c["Core/Series/Point.js"],c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,n,p,d){var q=d.isObject,l=d.pick,u=n.seriesTypes;d=u.area.prototype;u=u.column.prototype;n.seriesType("lollipop",
"dumbbell",{lowColor:void 0,threshold:0,connectorWidth:1,groupPadding:.2,pointPadding:.1,states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}},tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>'}},{pointArrayMap:["y"],pointValKey:"y",toYData:function(c){return[l(c.y,c.low)]},translatePoint:d.translate,drawPoint:d.drawPoints,drawDataLabels:u.drawDataLabels,setShapeArgs:u.translate},{pointSetState:d.pointClass.prototype.setState,setState:p.seriesTypes.dumbbell.prototype.pointClass.prototype.setState,
init:function(d,g,l){q(g)&&"low"in g&&(g.y=g.low,delete g.low);return c.prototype.init.apply(this,arguments)}});""});p(c,"masters/modules/lollipop.src.js",[],function(){})});
//# sourceMappingURL=lollipop.js.map