/*
 Highstock JS v8.2.2 (2020-10-27)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(K){b(K);b.Highcharts=K;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function K(b,w,B,n){b.hasOwnProperty(w)||(b[w]=n.apply(null,B))}b=b?b._modules:{};K(b,"Core/Axis/NavigatorAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,w){var B=b.isTouchDevice,n=w.addEvent,y=w.correctFloat,
t=w.defined,a=w.isNumber,e=w.pick,L=function(){function b(a){this.axis=a}b.prototype.destroy=function(){this.axis=void 0};b.prototype.toFixedRange=function(b,u,C,v){var z=this.axis,k=z.chart;k=k&&k.fixedRange;var H=(z.pointRange||0)/2;b=e(C,z.translate(b,!0,!z.horiz));u=e(v,z.translate(u,!0,!z.horiz));z=k&&(u-b)/k;t(C)||(b=y(b+H));t(v)||(u=y(u-H));.7<z&&1.3>z&&(v?b=u-k:u=b+k);a(b)&&a(u)||(b=u=void 0);return{min:b,max:u}};return b}();return function(){function a(){}a.compose=function(a){a.keepProps.push("navigatorAxis");
n(a,"init",function(){this.navigatorAxis||(this.navigatorAxis=new L(this))});n(a,"zoom",function(a){var e=this.chart.options,b=e.navigator,z=this.navigatorAxis,k=e.chart.pinchType,H=e.rangeSelector;e=e.chart.zoomType;this.isXAxis&&(b&&b.enabled||H&&H.enabled)&&("y"===e?a.zoomed=!1:(!B&&"xy"===e||B&&"xy"===k)&&this.options.range&&(b=z.previousZoom,t(a.newMin)?z.previousZoom=[this.min,this.max]:b&&(a.newMin=b[0],a.newMax=b[1],z.previousZoom=void 0)));"undefined"!==typeof a.zoomed&&a.preventDefault()})};
a.AdditionsClass=L;return a}()});K(b,"Core/Axis/ScrollbarAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,w){var B=w.addEvent,n=w.defined,y=w.pick;return function(){function t(){}t.compose=function(a,e){B(a,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new e(a.chart.renderer,a.options.scrollbar,a.chart),B(a.scrollbar,"changed",function(e){var t=
y(a.options&&a.options.min,a.min),u=y(a.options&&a.options.max,a.max),C=n(a.dataMin)?Math.min(t,a.min,a.dataMin):t,v=(n(a.dataMax)?Math.max(u,a.max,a.dataMax):u)-C;n(t)&&n(u)&&(a.horiz&&!a.reversed||!a.horiz&&a.reversed?(t=C+v*this.to,C+=v*this.from):(t=C+v*(1-this.from),C+=v*(1-this.to)),y(this.options.liveRedraw,b.svg&&!b.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===e.DOMType||!n(e.DOMType)?a.setExtremes(C,t,!0,"mousemove"!==e.DOMType,e):this.setRange(this.from,this.to))}))});B(a,"afterRender",
function(){var a=Math.min(y(this.options.min,this.min),this.min,y(this.dataMin,this.min)),e=Math.max(y(this.options.max,this.max),this.max,y(this.dataMax,this.max)),b=this.scrollbar,u=this.axisTitleMargin+(this.titleOffset||0),C=this.chart.scrollbarsOffsets,v=this.options.margin||0;b&&(this.horiz?(this.opposite||(C[1]+=u),b.position(this.left,this.top+this.height+2+C[1]-(this.opposite?v:0),this.width,this.height),this.opposite||(C[1]+=v),u=1):(this.opposite&&(C[0]+=u),b.position(this.left+this.width+
2+C[0]-(this.opposite?0:v),this.top,this.width,this.height),this.opposite&&(C[0]+=v),u=0),C[u]+=b.size+b.options.margin,isNaN(a)||isNaN(e)||!n(this.min)||!n(this.max)||this.min===this.max?b.setRange(0,1):(C=(this.min-a)/(e-a),a=(this.max-a)/(e-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?b.setRange(C,a):b.setRange(1-a,1-C)))});B(a,"afterGetOffset",function(){var a=this.horiz?2:1,b=this.scrollbar;b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=b.size+b.options.margin)})};
return t}()});K(b,"Core/Scrollbar.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/ScrollbarAxis.js"],b["Core/Utilities.js"],b["Core/Options.js"]],function(b,w,B,n,y){var t=n.addEvent,a=n.correctFloat,e=n.defined,L=n.destroyObjectProperties,D=n.fireEvent,J=n.merge,u=n.pick,C=n.removeEvent;n=y.defaultOptions;var v=w.hasTouch,z=w.isTouchDevice,k=w.swapXY=function(a,G){G&&a.forEach(function(c){for(var m=c.length,a,G=0;G<m;G+=2)a=c[G+1],"number"===typeof a&&(c[G+1]=c[G+2],c[G+2]=a)});return a};
y=function(){function b(a,c,m){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=m;this.options=c;this.renderer=m.renderer;this.init(a,c,m)}b.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,
1],c=this.scrollbarButtons,m=this.scrollbarGroup.element,k=this.track.element,b=this.mouseDownHandler.bind(this),h=this.mouseMoveHandler.bind(this),g=this.mouseUpHandler.bind(this);a=[[c[a[0]].element,"click",this.buttonToMinClick.bind(this)],[c[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[k,"click",this.trackClick.bind(this)],[m,"mousedown",b],[m.ownerDocument,"mousemove",h],[m.ownerDocument,"mouseup",g]];v&&a.push([m,"touchstart",b],[m.ownerDocument,"touchmove",h],[m.ownerDocument,"touchend",
g]);a.forEach(function(p){t.apply(null,p)});this._events=a};b.prototype.buttonToMaxClick=function(a){var c=(this.to-this.from)*u(this.options.step,.2);this.updatePosition(this.from+c,this.to+c);D(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};b.prototype.buttonToMinClick=function(G){var c=a(this.to-this.from)*u(this.options.step,.2);this.updatePosition(a(this.from-c),a(this.to-c));D(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:G})};b.prototype.cursorToScrollbarPosition=
function(a){var c=this.options;c=c.minWidth>this.calculatedWidth?c.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-c),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-c)}};b.prototype.destroy=function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(c){this[c]&&this[c].destroy&&(this[c]=this[c].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,L(a.scrollbarButtons))};b.prototype.drawScrollbarButton=
function(a){var c=this.renderer,m=this.scrollbarButtons,G=this.options,b=this.size;var h=c.g().add(this.group);m.push(h);h=c.rect().addClass("highcharts-scrollbar-button").add(h);this.chart.styledMode||h.attr({stroke:G.buttonBorderColor,"stroke-width":G.buttonBorderWidth,fill:G.buttonBackgroundColor});h.attr(h.crisp({x:-.5,y:-.5,width:b+1,height:b+1,r:G.buttonBorderRadius},h.strokeWidth()));h=c.path(k([["M",b/2+(a?-1:1),b/2-3],["L",b/2+(a?-1:1),b/2+3],["L",b/2+(a?2:-2),b/2]],G.vertical)).addClass("highcharts-scrollbar-arrow").add(m[a]);
this.chart.styledMode||h.attr({fill:G.buttonArrowColor})};b.prototype.init=function(a,c,m){this.scrollbarButtons=[];this.renderer=a;this.userOptions=c;this.options=J(b.defaultOptions,c);this.chart=m;this.size=u(this.options.size,this.options.height);c.enabled&&(this.render(),this.addEvents())};b.prototype.mouseDownHandler=function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=
!0};b.prototype.mouseMoveHandler=function(a){var c=this.chart.pointer.normalize(a),m=this.options.vertical?"chartY":"chartX",k=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][m]||(c=this.cursorToScrollbarPosition(c)[m],m=this[m],m=c-m,this.hasDragged=!0,this.updatePosition(k[0]+m,k[1]+m),this.hasDragged&&D(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};b.prototype.mouseUpHandler=function(a){this.hasDragged&&D(this,"changed",{from:this.from,
to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};b.prototype.position=function(a,c,m,k){var b=this.options.vertical,h=0,g=this.rendered?"animate":"attr";this.x=a;this.y=c+this.trackBorderWidth;this.width=m;this.xOffset=this.height=k;this.yOffset=h;b?(this.width=this.yOffset=m=h=this.size,this.xOffset=c=0,this.barWidth=k-2*m,this.x=a+=this.options.margin):(this.height=this.xOffset=k=c=this.size,this.barWidth=m-2*k,this.y+=this.options.margin);
this.group[g]({translateX:a,translateY:this.y});this.track[g]({width:m,height:k});this.scrollbarButtons[1][g]({translateX:b?0:m-c,translateY:b?k-h:0})};b.prototype.removeEvents=function(){this._events.forEach(function(a){C.apply(null,a)});this._events.length=0};b.prototype.render=function(){var a=this.renderer,c=this.options,m=this.size,b=this.chart.styledMode,e;this.group=e=a.g("scrollbar").attr({zIndex:c.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,
r:c.trackBorderRadius||0,height:m,width:m}).add(e);b||this.track.attr({fill:c.trackBackgroundColor,stroke:c.trackBorderColor,"stroke-width":c.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(e);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:m,width:m,r:c.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(k([["M",-3,m/4],["L",-3,2*m/3],["M",0,m/4],["L",
0,2*m/3],["M",3,m/4],["L",3,2*m/3]],c.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);b||(this.scrollbar.attr({fill:c.barBackgroundColor,stroke:c.barBorderColor,"stroke-width":c.barBorderWidth}),this.scrollbarRifles.attr({stroke:c.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};b.prototype.setRange=
function(k,c){var m=this.options,b=m.vertical,G=m.minWidth,h=this.barWidth,g,p=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(e(h)){k=Math.max(k,0);var d=Math.ceil(h*k);this.calculatedWidth=g=a(h*Math.min(c,1)-d);g<G&&(d=(h-G+g)*k,g=G);G=Math.floor(d+this.xOffset+this.yOffset);h=g/2-.5;this.from=k;this.to=c;b?(this.scrollbarGroup[p]({translateY:G}),this.scrollbar[p]({height:g}),this.scrollbarRifles[p]({translateY:h}),this.scrollbarTop=G,
this.scrollbarLeft=0):(this.scrollbarGroup[p]({translateX:G}),this.scrollbar[p]({width:g}),this.scrollbarRifles[p]({translateX:h}),this.scrollbarLeft=G,this.scrollbarTop=0);12>=g?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===m.showFull&&(0>=k&&1<=c?this.group.hide():this.group.show());this.rendered=!0}};b.prototype.trackClick=function(a){var c=this.chart.pointer.normalize(a),m=this.to-this.from,k=this.y+this.scrollbarTop,b=this.x+this.scrollbarLeft;this.options.vertical&&c.chartY>
k||!this.options.vertical&&c.chartX>b?this.updatePosition(this.from+m,this.to+m):this.updatePosition(this.from-m,this.to-m);D(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};b.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,J(!0,this.options,a),this.chart)};b.prototype.updatePosition=function(k,c){1<c&&(k=a(1-a(c-k)),c=1);0>k&&(c=a(c-k),k=0);this.from=k;this.to=c};b.defaultOptions={height:z?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,
margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return b}();w.Scrollbar||(n.scrollbar=J(!0,y.defaultOptions,n.scrollbar),w.Scrollbar=y,B.compose(b,y));return w.Scrollbar});K(b,"Core/Navigator.js",[b["Core/Axis/Axis.js"],b["Core/Series/Series.js"],
b["Core/Chart/Chart.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Series/LineSeries.js"],b["Core/Axis/NavigatorAxis.js"],b["Core/Options.js"],b["Core/Scrollbar.js"],b["Core/Utilities.js"]],function(b,w,B,n,y,t,a,e,L,D){n=n.parse;var J=y.hasTouch,u=y.isTouchDevice,C=e.defaultOptions,v=D.addEvent,z=D.clamp,k=D.correctFloat,H=D.defined,G=D.destroyObjectProperties,c=D.erase,m=D.extend,A=D.find,F=D.isArray,h=D.isNumber,g=D.merge,p=D.pick,d=D.removeEvent,E=D.splat,f=function(a){for(var l=[],x=1;x<
arguments.length;x++)l[x-1]=arguments[x];l=[].filter.call(l,h);if(l.length)return Math[a].apply(0,l)};w="undefined"===typeof w.seriesTypes.areaspline?"line":"areaspline";m(C,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:n("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:w,fillOpacity:.05,lineWidth:1,compare:null,
dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",
tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});y.Renderer.prototype.symbols["navigator-handle"]=function(a,l,x,p,f){a=(f&&f.width||0)/2;l=Math.round(a/3)+.5;f=f&&f.height||0;return[["M",-a-1,.5],
["L",a,.5],["L",a,f+.5],["L",-a-1,f+.5],["L",-a-1,.5],["M",-l,4],["L",-l,f-3],["M",l-1,4],["L",l-1,f-3]]};var r=function(){function q(l){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(l)}q.prototype.drawHandle=function(l,
x,a,f){var p=this.navigatorOptions.handles.height;this.handles[x][f](a?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(l,10)+.5-p)}:{translateX:Math.round(this.left+parseInt(l,10)),translateY:Math.round(this.top+this.height/2-p/2-1)})};q.prototype.drawOutline=function(l,x,a,f){var p=this.navigatorOptions.maskInside,d=this.outline.strokeWidth(),g=d/2,q=d%2/2;d=this.outlineHeight;var c=this.scrollbarHeight||0,I=this.size,r=this.left-c,E=this.top;a?(r-=g,a=E+x+
q,x=E+l+q,q=[["M",r+d,E-c-q],["L",r+d,a],["L",r,a],["L",r,x],["L",r+d,x],["L",r+d,E+I+c]],p&&q.push(["M",r+d,a-g],["L",r+d,x+g])):(l+=r+c-q,x+=r+c-q,E+=g,q=[["M",r,E],["L",l,E],["L",l,E+d],["L",x,E+d],["L",x,E],["L",r+I+2*c,E]],p&&q.push(["M",l-g,E],["L",x+g,E]));this.outline[f]({d:q})};q.prototype.drawMasks=function(l,x,a,f){var p=this.left,d=this.top,g=this.height;if(a){var q=[p,p,p];var r=[d,d+l,d+x];var c=[g,g,g];var I=[l,x-l,this.size-x]}else q=[p,p+l,p+x],r=[d,d,d],c=[l,x-l,this.size-x],I=[g,
g,g];this.shades.forEach(function(l,x){l[f]({x:q[x],y:r[x],width:c[x],height:I[x]})})};q.prototype.renderElements=function(){var l=this,x=l.navigatorOptions,a=x.maskInside,f=l.chart,p=f.renderer,d,g={cursor:f.inverted?"ns-resize":"ew-resize"};l.navigatorGroup=d=p.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!a,a,!a].forEach(function(a,q){l.shades[q]=p.rect().addClass("highcharts-navigator-mask"+(1===q?"-inside":"-outside")).add(d);f.styledMode||l.shades[q].attr({fill:a?x.maskFill:"rgba(0,0,0,0)"}).css(1===
q&&g)});l.outline=p.path().addClass("highcharts-navigator-outline").add(d);f.styledMode||l.outline.attr({"stroke-width":x.outlineWidth,stroke:x.outlineColor});x.handles.enabled&&[0,1].forEach(function(a){x.handles.inverted=f.inverted;l.handles[a]=p.symbol(x.handles.symbols[a],-x.handles.width/2-1,0,x.handles.width,x.handles.height,x.handles);l.handles[a].attr({zIndex:7-a}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][a]).add(d);if(!f.styledMode){var q=x.handles;
l.handles[a].attr({fill:q.backgroundColor,stroke:q.borderColor,"stroke-width":q.lineWidth}).css(g)}})};q.prototype.update=function(l){(this.series||[]).forEach(function(l){l.baseSeries&&delete l.baseSeries.navigatorSeries});this.destroy();g(!0,this.chart.options.navigator,this.options,l);this.init(this.chart)};q.prototype.render=function(l,x,a,f){var d=this.chart,g=this.scrollbarHeight,q,r=this.xAxis,c=r.pointRange||0;var E=r.navigatorAxis.fake?d.xAxis[0]:r;var I=this.navigatorEnabled,m,b=this.rendered;
var M=d.inverted;var e=d.xAxis[0].minRange,G=d.xAxis[0].options.maxRange;if(!this.hasDragged||H(a)){l=k(l-c/2);x=k(x+c/2);if(!h(l)||!h(x))if(b)a=0,f=p(r.width,E.width);else return;this.left=p(r.left,d.plotLeft+g+(M?d.plotWidth:0));this.size=m=q=p(r.len,(M?d.plotHeight:d.plotWidth)-2*g);d=M?g:q+2*g;a=p(a,r.toPixels(l,!0));f=p(f,r.toPixels(x,!0));h(a)&&Infinity!==Math.abs(a)||(a=0,f=d);l=r.toValue(a,!0);x=r.toValue(f,!0);var A=Math.abs(k(x-l));A<e?this.grabbedLeft?a=r.toPixels(x-e-c,!0):this.grabbedRight&&
(f=r.toPixels(l+e+c,!0)):H(G)&&k(A-c)>G&&(this.grabbedLeft?a=r.toPixels(x-G-c,!0):this.grabbedRight&&(f=r.toPixels(l+G+c,!0)));this.zoomedMax=z(Math.max(a,f),0,m);this.zoomedMin=z(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(a,f),0,m);this.range=this.zoomedMax-this.zoomedMin;m=Math.round(this.zoomedMax);a=Math.round(this.zoomedMin);I&&(this.navigatorGroup.attr({visibility:"visible"}),b=b&&!this.hasDragged?"animate":"attr",this.drawMasks(a,m,M,b),this.drawOutline(a,m,M,b),this.navigatorOptions.handles.enabled&&
(this.drawHandle(a,0,M,b),this.drawHandle(m,1,M,b)));this.scrollbar&&(M?(M=this.top-g,E=this.left-g+(I||!E.opposite?0:(E.titleOffset||0)+E.axisTitleMargin),g=q+2*g):(M=this.top+(I?this.height:-g),E=this.left-g),this.scrollbar.position(E,M,d,g),this.scrollbar.setRange(this.zoomedMin/(q||1),this.zoomedMax/(q||1)));this.rendered=!0}};q.prototype.addMouseEvents=function(){var l=this,x=l.chart,a=x.container,f=[],d,g;l.mouseMoveHandler=d=function(x){l.onMouseMove(x)};l.mouseUpHandler=g=function(x){l.onMouseUp(x)};
f=l.getPartsEvents("mousedown");f.push(v(x.renderTo,"mousemove",d),v(a.ownerDocument,"mouseup",g));J&&(f.push(v(x.renderTo,"touchmove",d),v(a.ownerDocument,"touchend",g)),f.concat(l.getPartsEvents("touchstart")));l.eventsToUnbind=f;l.series&&l.series[0]&&f.push(v(l.series[0].xAxis,"foundExtremes",function(){x.navigator.modifyNavigatorAxisExtremes()}))};q.prototype.getPartsEvents=function(l){var x=this,a=[];["shades","handles"].forEach(function(f){x[f].forEach(function(d,g){a.push(v(d.element,l,function(l){x[f+
"Mousedown"](l,g)}))})});return a};q.prototype.shadesMousedown=function(l,x){l=this.chart.pointer.normalize(l);var a=this.chart,f=this.xAxis,d=this.zoomedMin,g=this.left,p=this.size,q=this.range,r=l.chartX;a.inverted&&(r=l.chartY,g=this.top);if(1===x)this.grabbedCenter=r,this.fixedWidth=q,this.dragOffset=r-d;else{l=r-g-q/2;if(0===x)l=Math.max(0,l);else if(2===x&&l+q>=p)if(l=p-q,this.reversedExtremes){l-=q;var c=this.getUnionExtremes().dataMin}else var E=this.getUnionExtremes().dataMax;l!==d&&(this.fixedWidth=
q,x=f.navigatorAxis.toFixedRange(l,l+q,c,E),H(x.min)&&a.xAxis[0].setExtremes(Math.min(x.min,x.max),Math.max(x.min,x.max),!0,null,{trigger:"navigator"}))}};q.prototype.handlesMousedown=function(l,x){this.chart.pointer.normalize(l);l=this.chart;var a=l.xAxis[0],f=this.reversedExtremes;0===x?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=f?a.min:a.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=f?a.max:a.min);l.fixedRange=null};q.prototype.onMouseMove=
function(l){var a=this,f=a.chart,d=a.left,g=a.navigatorSize,q=a.range,r=a.dragOffset,c=f.inverted;l.touches&&0===l.touches[0].pageX||(l=f.pointer.normalize(l),f=l.chartX,c&&(d=a.top,f=l.chartY),a.grabbedLeft?(a.hasDragged=!0,a.render(0,0,f-d,a.otherHandlePos)):a.grabbedRight?(a.hasDragged=!0,a.render(0,0,a.otherHandlePos,f-d)):a.grabbedCenter&&(a.hasDragged=!0,f<r?f=r:f>g+r-q&&(f=g+r-q),a.render(0,0,f-r,f-r+q)),a.hasDragged&&a.scrollbar&&p(a.scrollbar.options.liveRedraw,y.svg&&!u&&!this.chart.isBoosting)&&
(l.DOMType=l.type,setTimeout(function(){a.onMouseUp(l)},0)))};q.prototype.onMouseUp=function(l){var a=this.chart,f=this.xAxis,d=this.scrollbar,g=l.DOMEvent||l,q=a.inverted,p=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===l.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var r=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var c=this.fixedExtreme;this.zoomedMax===this.size&&(c=this.reversedExtremes?
d.dataMin:d.dataMax);0===this.zoomedMin&&(r=this.reversedExtremes?d.dataMax:d.dataMin);f=f.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,r,c);H(f.min)&&a.xAxis[0].setExtremes(Math.min(f.min,f.max),Math.max(f.min,f.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:g})}"mousemove"!==l.DOMType&&"touchmove"!==l.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=
null);this.navigatorEnabled&&h(this.zoomedMin)&&h(this.zoomedMax)&&(a=Math.round(this.zoomedMin),l=Math.round(this.zoomedMax),this.shades&&this.drawMasks(a,l,q,p),this.outline&&this.drawOutline(a,l,q,p),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(a,0,q,p),this.drawHandle(l,1,q,p)))};q.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};
q.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){d(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&d(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};q.prototype.init=function(l){var d=l.options,q=d.navigator,r=q.enabled,c=d.scrollbar,E=c.enabled;d=r?q.height:0;var m=E?c.height:0;this.handles=[];this.shades=[];this.chart=l;this.setBaseSeries();this.height=
d;this.scrollbarHeight=m;this.scrollbarEnabled=E;this.navigatorEnabled=r;this.navigatorOptions=q;this.scrollbarOptions=c;this.outlineHeight=d+m;this.opposite=p(q.opposite,!(r||!l.inverted));var h=this;r=h.baseSeries;c=l.xAxis.length;E=l.yAxis.length;var k=r&&r[0]&&r[0].xAxis||l.xAxis[0]||{options:{}};l.isDirtyBox=!0;h.navigatorEnabled?(h.xAxis=new b(l,g({breaks:k.options.breaks,ordinal:k.options.ordinal},q.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:c,isInternal:!0,
offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},l.inverted?{offsets:[m,0,-m,0],width:d}:{offsets:[0,-m,0,m],height:d})),h.yAxis=new b(l,g(q.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:E,isInternal:!0,reversed:p(q.yAxis&&q.yAxis.reversed,l.yAxis[0]&&l.yAxis[0].reversed,!1),zoomEnabled:!1},l.inverted?{width:d}:{height:d})),r||q.series.data?h.updateNavigatorSeries(!1):0===l.series.length&&(h.unbindRedraw=v(l,"beforeRedraw",function(){0<
l.series.length&&!h.series&&(h.setBaseSeries(),h.unbindRedraw())})),h.reversedExtremes=l.inverted&&!h.xAxis.reversed||!l.inverted&&h.xAxis.reversed,h.renderElements(),h.addMouseEvents()):(h.xAxis={chart:l,navigatorAxis:{fake:!0},translate:function(a,d){var q=l.xAxis[0],g=q.getExtremes(),r=q.len-2*m,p=f("min",q.options.min,g.dataMin);q=f("max",q.options.max,g.dataMax)-p;return d?a*q/r+p:r*(a-p)/q},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},h.xAxis.navigatorAxis.axis=
h.xAxis,h.xAxis.navigatorAxis.toFixedRange=a.AdditionsClass.prototype.toFixedRange.bind(h.xAxis.navigatorAxis));l.options.scrollbar.enabled&&(l.scrollbar=h.scrollbar=new L(l.renderer,g(l.options.scrollbar,{margin:h.navigatorEnabled?0:10,vertical:l.inverted}),l),v(h.scrollbar,"changed",function(a){var f=h.size,d=f*this.to;f*=this.from;h.hasDragged=h.scrollbar.hasDragged;h.render(0,0,f,d);(l.options.scrollbar.liveRedraw||"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType)&&setTimeout(function(){h.onMouseUp(a)})}));
h.addBaseSeriesEvents();h.addChartEvents()};q.prototype.getUnionExtremes=function(a){var l=this.chart.xAxis[0],d=this.xAxis,q=d.options,g=l.options,r;a&&null===l.dataMin||(r={dataMin:p(q&&q.min,f("min",g.min,l.dataMin,d.dataMin,d.min)),dataMax:p(q&&q.max,f("max",g.max,l.dataMax,d.dataMax,d.max))});return r};q.prototype.setBaseSeries=function(a,f){var l=this.chart,d=this.baseSeries=[];a=a||l.options&&l.options.navigator.baseSeries||(l.series.length?A(l.series,function(a){return!a.options.isInternal}).index:
0);(l.series||[]).forEach(function(l,f){l.options.isInternal||!l.options.showInNavigator&&(f!==a&&l.options.id!==a||!1===l.options.showInNavigator)||d.push(l)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,f)};q.prototype.updateNavigatorSeries=function(a,f){var l=this,q=l.chart,r=l.baseSeries,x,c,h=l.navigatorOptions.series,k,b={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,
isInternal:!0,states:{inactive:{opacity:1}}},e=l.series=(l.series||[]).filter(function(a){var f=a.baseSeries;return 0>r.indexOf(f)?(f&&(d(f,"updatedData",l.updatedDataHandler),delete f.navigatorSeries),a.chart&&a.destroy(),!1):!0});r&&r.length&&r.forEach(function(a){var d=a.navigatorSeries,E=m({color:a.color,visible:a.visible},F(h)?C.navigator.series:h);d&&!1===l.navigatorOptions.adaptToUpdatedData||(b.name="Navigator "+r.length,x=a.options||{},k=x.navigatorOptions||{},c=g(x,b,E,k),c.pointRange=p(E.pointRange,
k.pointRange,C.plotOptions[c.type||"line"].pointRange),E=k.data||E.data,l.hasNavigatorData=l.hasNavigatorData||!!E,c.data=E||x.data&&x.data.slice(0),d&&d.options?d.update(c,f):(a.navigatorSeries=q.initSeries(c),a.navigatorSeries.baseSeries=a,e.push(a.navigatorSeries)))});if(h.data&&(!r||!r.length)||F(h))l.hasNavigatorData=!1,h=E(h),h.forEach(function(a,f){b.name="Navigator "+(e.length+1);c=g(C.navigator.series,{color:q.series[f]&&!q.series[f].options.isInternal&&q.series[f].color||q.options.colors[f]||
q.options.colors[0]},b,a);c.data=a.data;c.data&&(l.hasNavigatorData=!0,e.push(q.initSeries(c)))});a&&this.addBaseSeriesEvents()};q.prototype.addBaseSeriesEvents=function(){var a=this,f=a.baseSeries||[];f[0]&&f[0].xAxis&&v(f[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);f.forEach(function(l){v(l,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(l,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&
l.xAxis&&v(l,"updatedData",this.updatedDataHandler);v(l,"remove",function(){this.navigatorSeries&&(c(a.series,this.navigatorSeries),H(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};q.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,l){return Math.min(a,l.xData?l.xData[0]:a)},a)};q.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,f;"undefined"!==typeof a.getExtremes&&(!(f=this.getUnionExtremes(!0))||
f.dataMin===a.min&&f.dataMax===a.max||(a.min=f.dataMin,a.max=f.dataMax))};q.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,f=this.getExtremes(),d=f.dataMin,q=f.dataMax;f=f.max-f.min;var r=a.stickToMin,g=a.stickToMax,c=p(this.options.overscroll,0),E=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(r){var k=d;var b=k+f}g&&(b=q+c,r||(k=Math.max(d,b-f,a.getBaseSeriesMin(E&&E.xData?E.xData[0]:-Number.MAX_VALUE))));
m&&(r||g)&&h(k)&&(this.min=this.userMin=k,this.max=this.userMax=b)}a.stickToMin=a.stickToMax=null};q.prototype.updatedDataHandler=function(){var a=this.chart.navigator,f=this.navigatorSeries,d=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=h(this.xAxis.min)&&this.xAxis.min<=d&&(!this.chart.fixedRange||!a.stickToMax);f&&!a.hasNavigatorData&&(f.options.pointStart=this.xData[0],f.setData(this.options.data,
!1,null,!1))};q.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(v(this.chart,"redraw",function(){var a=this.navigator,f=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);f&&a.render(f.min,f.max)}),v(this.chart,"getMargins",function(){var a=this.navigator,f=a.opposite?"plotTop":"marginBottom";this.inverted&&(f=a.opposite?"marginRight":"plotLeft");this[f]=(this[f]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:
0)+a.navigatorOptions.margin}))};q.prototype.destroy=function(){this.removeEvents();this.xAxis&&(c(this.chart.xAxis,this.xAxis),c(this.chart.axes,this.xAxis));this.yAxis&&(c(this.chart.yAxis,this.yAxis),c(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},
this);[this.handles].forEach(function(a){G(a)},this)};return q}();y.Navigator||(y.Navigator=r,a.compose(b),v(B,"beforeShowResetZoom",function(){var a=this.options,f=a.navigator,d=a.rangeSelector;if((f&&f.enabled||d&&d.enabled)&&(!u&&"x"===a.chart.zoomType||u&&"x"===a.chart.pinchType))return!1}),v(B,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new r(this)}),v(B,"afterSetChartSize",function(){var a=this.legend,f=this.navigator;
if(f){var d=a&&a.options;var r=f.xAxis;var g=f.yAxis;var c=f.scrollbarHeight;this.inverted?(f.left=f.opposite?this.chartWidth-c-f.height:this.spacing[3]+c,f.top=this.plotTop+c):(f.left=this.plotLeft+c,f.top=f.navigatorOptions.top||this.chartHeight-f.height-c-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(d&&"bottom"===d.verticalAlign&&"proximate"!==d.layout&&d.enabled&&!d.floating?a.legendHeight+p(d.margin,10):0)-(this.titleOffset?this.titleOffset[2]:
0));r&&g&&(this.inverted?r.options.left=g.options.left=f.left:r.options.top=g.options.top=f.top,r.setAxisSize(),g.setAxisSize())}}),v(B,"update",function(a){var f=a.options.navigator||{},d=a.options.scrollbar||{};this.navigator||this.scroller||!f.enabled&&!d.enabled||(g(!0,this.options.navigator,f),g(!0,this.options.scrollbar,d),delete a.options.navigator,delete a.options.scrollbar)}),v(B,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||
(this.scroller=this.navigator=new r(this),p(a.redraw,!0)&&this.redraw(a.animation))}),v(B,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),v(t,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),B.prototype.callbacks.push(function(a){var f=a.navigator;f&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),f.render(a.min,a.max))}));y.Navigator=r;return y.Navigator});K(b,"Core/Axis/OrdinalAxis.js",[b["Core/Axis/Axis.js"],
b["Core/Globals.js"],b["Core/Series/CartesianSeries.js"],b["Core/Utilities.js"],b["Core/Chart/Chart.js"]],function(b,w,B,n,y){var t=n.addEvent,a=n.css,e=n.defined,L=n.error,D=n.pick,J=n.timeUnits,u;(function(b){var v=function(){function a(a){this.index={};this.axis=a}a.prototype.beforeSetTickPositions=function(){var a=this.axis,b=a.ordinal,e=[],c,m=!1,A=a.getExtremes(),F=A.min,h=A.max,g,p=a.isXAxis&&!!a.options.breaks;A=a.options.ordinal;var d=Number.MAX_VALUE,E=a.chart.options.chart.ignoreHiddenSeries,
f;if(A||p){a.series.forEach(function(a,g){c=[];if(!(E&&!1===a.visible||!1===a.takeOrdinalPosition&&!p)&&(e=e.concat(a.processedXData),r=e.length,e.sort(function(a,f){return a-f}),d=Math.min(d,D(a.closestPointRange,d)),r)){for(g=0;g<r-1;)e[g]!==e[g+1]&&c.push(e[g+1]),g++;c[0]!==e[0]&&c.unshift(e[0]);e=c}a.isSeriesBoosting&&(f=!0)});f&&(e.length=0);var r=e.length;if(2<r){var q=e[1]-e[0];for(g=r-1;g--&&!m;)e[g+1]-e[g]!==q&&(m=!0);!a.options.keepOrdinalPadding&&(e[0]-F>q||h-e[e.length-1]>q)&&(m=!0)}else a.options.overscroll&&
(2===r?d=e[1]-e[0]:1===r?(d=a.options.overscroll,e=[e[0],e[0]+d]):d=b.overscrollPointsRange);m?(a.options.overscroll&&(b.overscrollPointsRange=d,e=e.concat(b.getOverscrollPositions())),b.positions=e,q=a.ordinal2lin(Math.max(F,e[0]),!0),g=Math.max(a.ordinal2lin(Math.min(h,e[e.length-1]),!0),1),b.slope=h=(h-F)/(g-q),b.offset=F-q*h):(b.overscrollPointsRange=D(a.closestPointRange,b.overscrollPointsRange),b.positions=a.ordinal.slope=b.offset=void 0)}a.isOrdinal=A&&m;b.groupIntervalFactor=null};a.prototype.getExtendedPositions=
function(){var a=this,b=a.axis,e=b.constructor.prototype,c=b.chart,m=b.series[0].currentDataGrouping,A=a.index,F=m?m.count+m.unitName:"raw",h=b.options.overscroll,g=b.getExtremes(),p;A||(A=a.index={});if(!A[F]){var d={series:[],chart:c,getExtremes:function(){return{min:g.dataMin,max:g.dataMax+h}},options:{ordinal:!0},ordinal:{},ordinal2lin:e.ordinal2lin,val2lin:e.val2lin};d.ordinal.axis=d;b.series.forEach(function(g){p={xAxis:d,xData:g.xData.slice(),chart:c,destroyGroupedData:w.noop,getProcessedData:B.prototype.getProcessedData};
p.xData=p.xData.concat(a.getOverscrollPositions());p.options={dataGrouping:m?{enabled:!0,forced:!0,approximation:"open",units:[[m.unitName,[m.count]]]}:{enabled:!1}};g.processData.apply(p);d.series.push(p)});b.ordinal.beforeSetTickPositions.apply({axis:d});A[F]=d.ordinal.positions}return A[F]};a.prototype.getGroupIntervalFactor=function(a,b,e){e=e.processedXData;var c=e.length,m=[];var k=this.groupIntervalFactor;if(!k){for(k=0;k<c-1;k++)m[k]=e[k+1]-e[k];m.sort(function(a,c){return a-c});m=m[Math.floor(c/
2)];a=Math.max(a,e[0]);b=Math.min(b,e[c-1]);this.groupIntervalFactor=k=c*m/(b-a)}return k};a.prototype.getOverscrollPositions=function(){var a=this.axis,b=a.options.overscroll,v=this.overscrollPointsRange,c=[],m=a.dataMax;if(e(v))for(c.push(m);m<=a.dataMax+b;)m+=v,c.push(m);return c};a.prototype.postProcessTickInterval=function(a){var b=this.axis,k=this.slope;return k?b.options.breaks?b.closestPointRange||a:a/(k/b.closestPointRange):a};return a}();b.Composition=v;b.compose=function(v,k,u){v.keepProps.push("ordinal");
var C=v.prototype;v.prototype.getTimeTicks=function(a,b,k,v,h,g,p){void 0===h&&(h=[]);void 0===g&&(g=0);var d=0,c,f,r={},q=[],l=-Number.MAX_VALUE,m=this.options.tickPixelInterval,I=this.chart.time,A=[];if(!this.options.ordinal&&!this.options.breaks||!h||3>h.length||"undefined"===typeof b)return I.getTimeTicks.apply(I,arguments);var F=h.length;for(c=0;c<F;c++){var C=c&&h[c-1]>k;h[c]<b&&(d=c);if(c===F-1||h[c+1]-h[c]>5*g||C){if(h[c]>l){for(f=I.getTimeTicks(a,h[d],h[c],v);f.length&&f[0]<=l;)f.shift();
f.length&&(l=f[f.length-1]);A.push(q.length);q=q.concat(f)}d=c+1}if(C)break}if(f){f=f.info;if(p&&f.unitRange<=J.hour){c=q.length-1;for(d=1;d<c;d++)if(I.dateFormat("%d",q[d])!==I.dateFormat("%d",q[d-1])){r[q[d]]="day";var u=!0}u&&(r[q[0]]="day");f.higherRanks=r}f.segmentStarts=A;q.info=f}else L(12,!1,this.chart);if(p&&e(m)){d=A=q.length;u=[];var z;for(I=[];d--;)c=this.translate(q[d]),z&&(I[d]=z-c),u[d]=z=c;I.sort();I=I[Math.floor(I.length/2)];I<.6*m&&(I=null);d=q[A-1]>k?A-1:A;for(z=void 0;d--;)c=u[d],
A=Math.abs(z-c),z&&A<.8*m&&(null===I||A<.8*I)?(r[q[d]]&&!r[q[d+1]]?(A=d+1,z=c):A=d,q.splice(A,1)):z=c}return q};C.lin2val=function(a,b){var c=this.ordinal,m=c.positions;if(m){var h=c.slope,g=c.offset;c=m.length-1;if(b)if(0>a)a=m[0];else if(a>c)a=m[c];else{c=Math.floor(a);var p=a-c}else for(;c--;)if(b=h*c+g,a>=b){h=h*(c+1)+g;p=(a-b)/(h-b);break}return"undefined"!==typeof p&&"undefined"!==typeof m[c]?m[c]+(p?p*(m[c+1]-m[c]):0):a}return a};C.val2lin=function(a,b){var c=this.ordinal,m=c.positions;if(m){var h=
m.length,g;for(g=h;g--;)if(m[g]===a){var p=g;break}for(g=h-1;g--;)if(a>m[g]||0===g){a=(a-m[g])/(m[g+1]-m[g]);p=g+a;break}b=b?p:c.slope*(p||0)+c.offset}else b=a;return b};C.ordinal2lin=C.val2lin;t(v,"afterInit",function(){this.ordinal||(this.ordinal=new b.Composition(this))});t(v,"foundExtremes",function(){this.isXAxis&&e(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=
this.options.overscroll,!this.isInternal&&e(this.userMin)&&(this.min+=this.options.overscroll))});t(v,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});t(v,"initialAxisTranslation",function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});t(k,"pan",function(c){var b=this.xAxis[0],k=b.options.overscroll,e=c.originalEvent.chartX,
h=this.options.chart&&this.options.chart.panning,g=!1;if(h&&"y"!==h.type&&b.options.ordinal&&b.series.length){var p=this.mouseDownX,d=b.getExtremes(),E=d.dataMax,f=d.min,r=d.max,q=this.hoverPoints,l=b.closestPointRange||b.ordinal&&b.ordinal.overscrollPointsRange;p=(p-e)/(b.translationSlope*(b.ordinal.slope||l));var x={ordinal:{positions:b.ordinal.getExtendedPositions()}};l=b.lin2val;var I=b.val2lin;if(!x.ordinal.positions)g=!0;else if(1<Math.abs(p)){q&&q.forEach(function(a){a.setState()});if(0>p){q=
x;var v=b.ordinal.positions?b:x}else q=b.ordinal.positions?b:x,v=x;x=v.ordinal.positions;E>x[x.length-1]&&x.push(E);this.fixedRange=r-f;p=b.navigatorAxis.toFixedRange(null,null,l.apply(q,[I.apply(q,[f,!0])+p,!0]),l.apply(v,[I.apply(v,[r,!0])+p,!0]));p.min>=Math.min(d.dataMin,f)&&p.max<=Math.max(E,r)+k&&b.setExtremes(p.min,p.max,!0,!1,{trigger:"pan"});this.mouseDownX=e;a(this.container,{cursor:"move"})}}else g=!0;g||h&&/y/.test(h.type)?k&&(b.max=b.dataMax+k):c.preventDefault()});t(u,"updatedData",
function(){var a=this.xAxis;a&&a.options.ordinal&&delete a.ordinal.index})}})(u||(u={}));u.compose(b,y,B);return u});K(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,w,B,n){var y=n.addEvent,t=n.find,a=n.fireEvent,e=n.isArray,L=n.isNumber,D=n.pick,J=function(){function u(a){this.hasBreaks=!1;this.axis=a}u.isInBreak=function(a,b){var e=a.repeat||Infinity,k=a.from,v=a.to-a.from;b=b>=k?(b-k)%e:e-(k-b)%e;return a.inclusive?
b<=v:b<v&&0!==b};u.lin2Val=function(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b)return a;var e;for(e=0;e<b.length;e++){var k=b[e];if(k.from>=a)break;else k.to<a?a+=k.len:u.isInBreak(k,a)&&(a+=k.len)}return a};u.val2Lin=function(a){var b=this.brokenAxis;b=b&&b.breakArray;if(!b)return a;var e=a,k;for(k=0;k<b.length;k++){var n=b[k];if(n.to<=a)e-=n.len;else if(n.from>=a)break;else if(u.isInBreak(n,a)){e-=a-n.from;break}}return e};u.prototype.findBreakAt=function(a,b){return t(b,function(b){return b.from<
a&&a<b.to})};u.prototype.isInAnyBreak=function(a,b){var e=this.axis,k=e.options.breaks,v=k&&k.length,n;if(v){for(;v--;)if(u.isInBreak(k[v],a)){var c=!0;n||(n=D(k[v].showPoints,!e.isXAxis))}var m=c&&b?c&&!n:c}return m};u.prototype.setBreaks=function(n,v){var z=this,k=z.axis,y=e(n)&&!!n.length;k.isDirty=z.hasBreaks!==y;z.hasBreaks=y;k.options.breaks=k.userOptions.breaks=n;k.forceRedraw=!0;k.series.forEach(function(a){a.isDirty=!0});y||k.val2lin!==u.val2Lin||(delete k.val2lin,delete k.lin2val);y&&(k.userOptions.ordinal=
!1,k.lin2val=u.lin2Val,k.val2lin=u.val2Lin,k.setExtremes=function(a,c,m,e,k){if(z.hasBreaks){for(var h,g=this.options.breaks;h=z.findBreakAt(a,g);)a=h.to;for(;h=z.findBreakAt(c,g);)c=h.from;c<a&&(c=a)}b.prototype.setExtremes.call(this,a,c,m,e,k)},k.setAxisTranslation=function(){b.prototype.setAxisTranslation.call(this);z.unitLength=null;if(z.hasBreaks){var e=k.options.breaks||[],c=[],m=[],v=0,n,h=k.userMin||k.min,g=k.userMax||k.max,p=D(k.pointRangePadding,0),d;e.forEach(function(a){n=a.repeat||Infinity;
u.isInBreak(a,h)&&(h+=a.to%n-h%n);u.isInBreak(a,g)&&(g-=g%n-a.from%n)});e.forEach(function(a){f=a.from;for(n=a.repeat||Infinity;f-n>h;)f-=n;for(;f<h;)f+=n;for(d=f;d<g;d+=n)c.push({value:d,move:"in"}),c.push({value:d+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,f){return a.value===f.value?("in"===a.move?0:1)-("in"===f.move?0:1):a.value-f.value});var E=0;var f=h;c.forEach(function(a){E+="in"===a.move?1:-1;1===E&&"in"===a.move&&(f=a.value);0===E&&(m.push({from:f,to:a.value,len:a.value-
f-(a.size||0)}),v+=a.value-f-(a.size||0))});k.breakArray=z.breakArray=m;z.unitLength=g-h-v+p;a(k,"afterBreaks");k.staticScale?k.transA=k.staticScale:z.unitLength&&(k.transA*=(g-k.min+p)/z.unitLength);p&&(k.minPixelPadding=k.transA*k.minPointOffset);k.min=h;k.max=g}});D(v,!0)&&k.chart.redraw()};return u}();n=function(){function b(){}b.compose=function(b,e){b.keepProps.push("brokenAxis");var n=w.prototype;n.drawBreaks=function(b,e){var k=this,c=k.points,m,n,u,h;if(b&&b.brokenAxis&&b.brokenAxis.hasBreaks){var g=
b.brokenAxis;e.forEach(function(p){m=g&&g.breakArray||[];n=b.isXAxis?b.min:D(k.options.threshold,b.min);c.forEach(function(d){h=D(d["stack"+p.toUpperCase()],d[p]);m.forEach(function(g){if(L(n)&&L(h)){u=!1;if(n<g.from&&h>g.to||n>g.from&&h<g.from)u="pointBreak";else if(n<g.from&&h>g.from&&h<g.to||n>g.from&&h>g.to&&h<g.from)u="pointInBreak";u&&a(b,u,{point:d,brk:g})}})})})}};n.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var e=this.points.slice(),c=e.length-
1,m=this.yAxis,n;if(a&&0<c)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),n=void 0;c--;)n&&!1!==n.visible||(n=e[c+1]),b=e[c],!1!==n.visible&&!1!==b.visible&&(n.x-b.x>a&&(n=(b.x+n.x)/2,e.splice(c+1,0,{isNull:!0,x:n}),m.stacking&&this.options.stacking&&(n=m.stacking.stacks[this.stackKey][n]=new B(m,m.options.stackLabels,!1,n,this.stack),n.total=0)),n=b);return this.getGraphPath(e)};y(b,"init",function(){this.brokenAxis||(this.brokenAxis=new J(this))});
y(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});y(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,e=this.tickPositions.info,c=[],m;for(m=0;m<b.length;m++)a.isInAnyBreak(b[m])||c.push(b[m]);this.tickPositions=c;this.tickPositions.info=e}});y(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});y(e,"afterGeneratePoints",function(){var a=
this.options.connectNulls,b=this.points,e=this.xAxis,c=this.yAxis;if(this.isDirty)for(var m=b.length;m--;){var n=b[m],u=!(null===n.y&&!1===a)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(n.x,!0)||c&&c.brokenAxis&&c.brokenAxis.isInAnyBreak(n.y,!0));n.visible=u?!1:!1!==n.options.visible}});y(e,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,D(this.pointArrayMap,["y"]))})};return b}();n.compose(b,w);return n});K(b,"masters/modules/broken-axis.src.js",[],function(){});
K(b,"Extensions/DataGrouping.js",[b["Core/Axis/Axis.js"],b["Core/Axis/DateTimeAxis.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Series/Point.js"],b["Core/Tooltip.js"],b["Core/Utilities.js"]],function(b,w,B,n,y,t,a){"";var e=a.addEvent,L=a.arrayMax,D=a.arrayMin,J=a.correctFloat,u=a.defined,C=a.error,v=a.extend,z=a.format,k=a.isNumber,H=a.merge,G=a.pick;a=B.Series;var c=B.approximations={sum:function(a){var f=a.length;if(!f&&a.hasNulls)var b=null;else if(f)for(b=0;f--;)b+=a[f];return b},average:function(a){var f=
a.length;a=c.sum(a);k(a)&&f&&(a=J(a/f));return a},averages:function(){var a=[];[].forEach.call(arguments,function(f){a.push(c.average(f))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?L(a):a.hasNulls?null:void 0},low:function(a){return a.length?D(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,b,d,g){a=c.open(a);b=c.high(b);d=c.low(d);g=c.close(g);
if(k(a)||k(b)||k(d)||k(g))return[a,b,d,g]},range:function(a,b){a=c.low(a);b=c.high(b);if(k(a)||k(b))return[a,b];if(null===a&&null===b)return null}},m=function(a,b,d,g){var f=this,p=f.data,l=f.options&&f.options.data,q=[],r=[],h=[],e=a.length,E=!!b,m=[],n=f.pointArrayMap,v=n&&n.length,y=["x"].concat(n||["y"]),t=0,z=0,F;g="function"===typeof g?g:c[g]?c[g]:c[f.getDGApproximation&&f.getDGApproximation()||"average"];v?n.forEach(function(){m.push([])}):m.push([]);var C=v||1;for(F=0;F<=e&&!(a[F]>=d[0]);F++);
for(F;F<=e;F++){for(;"undefined"!==typeof d[t+1]&&a[F]>=d[t+1]||F===e;){var A=d[t];f.dataGroupInfo={start:f.cropStart+z,length:m[0].length};var D=g.apply(f,m);f.pointClass&&!u(f.dataGroupInfo.options)&&(f.dataGroupInfo.options=H(f.pointClass.prototype.optionsToObject.call({series:f},f.options.data[f.cropStart+z])),y.forEach(function(a){delete f.dataGroupInfo.options[a]}));"undefined"!==typeof D&&(q.push(A),r.push(D),h.push(f.dataGroupInfo));z=F;for(A=0;A<C;A++)m[A].length=0,m[A].hasNulls=!1;t+=1;
if(F===e)break}if(F===e)break;if(n)for(A=f.cropStart+F,D=p&&p[A]||f.pointClass.prototype.applyOptions.apply({series:f},[l[A]]),A=0;A<v;A++){var w=D[n[A]];k(w)?m[A].push(w):null===w&&(m[A].hasNulls=!0)}else A=E?b[F]:null,k(A)?m[0].push(A):null===A&&(m[0].hasNulls=!0)}return{groupedXData:q,groupedYData:r,groupMap:h}},A={approximations:c,groupData:m},F=a.prototype,h=F.processData,g=F.generatePoints,p={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L",
"-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},d={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},
ohlc:{groupPixelWidth:5}},E=B.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];F.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};F.groupData=m;F.processData=function(){var a=this.chart,b=this.options.dataGrouping,d=!1!==this.allowDG&&b&&G(b.enabled,a.options.isStock),
g=this.visible||!a.options.chart.ignoreHiddenSeries,c,p=this.currentDataGrouping,e=!1;this.forceCrop=d;this.groupPixelWidth=null;this.hasProcessed=!0;d&&!this.requireSorting&&(this.requireSorting=e=!0);d=!1===h.apply(this,arguments)||!d;e&&(this.requireSorting=!1);if(!d){this.destroyGroupedData();d=b.groupAll?this.xData:this.processedXData;var m=b.groupAll?this.yData:this.processedYData,k=a.plotSizeX;a=this.xAxis;var n=a.options.ordinal,v=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();
if(v){this.isDirty=c=!0;this.points=null;e=a.getExtremes();var y=e.min;e=e.max;n=n&&a.ordinal&&a.ordinal.getGroupIntervalFactor(y,e,this)||1;v=v*(e-y)/k*n;k=a.getTimeTicks(w.AdditionsClass.prototype.normalizeTimeTickInterval(v,b.units||E),Math.min(y,d[0]),Math.max(e,d[d.length-1]),a.options.startOfWeek,d,this.closestPointRange);m=F.groupData.apply(this,[d,m,k,b.approximation]);d=m.groupedXData;n=m.groupedYData;var A=0;if(b.smoothed&&d.length){var t=d.length-1;for(d[t]=Math.min(d[t],e);t--&&0<t;)d[t]+=
v/2;d[0]=Math.max(d[0],y)}for(t=1;t<k.length;t++)k.info.segmentStarts&&-1!==k.info.segmentStarts.indexOf(t)||(A=Math.max(k[t]-k[t-1],A));y=k.info;y.gapSize=A;this.closestPointRange=k.info.totalRange;this.groupMap=m.groupMap;if(u(d[0])&&d[0]<a.min&&g){if(!u(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(d[0],a.min);a.dataMin=Math.min(d[0],a.dataMin)}b.groupAll&&(b=this.cropData(d,n,a.min,a.max,1),d=b.xData,n=b.yData);this.processedXData=d;this.processedYData=n}else this.groupMap=
null;this.hasGroupedData=c;this.currentDataGrouping=y;this.preventGraphAnimation=(p&&p.totalRange)!==(y&&y.totalRange)}};F.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,d){a&&(this.groupedData[d]=a.destroy?a.destroy():null)},this),this.groupedData.length=0)};F.generatePoints=function(){g.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};e(y,"update",function(){if(this.dataGroup)return C(24,!1,this.series.chart),!1});
e(t,"headerFormatter",function(a){var d=this.chart,b=d.time,f=a.labelConfig,g=f.series,c=g.tooltipOptions,e=g.options.dataGrouping,h=c.xDateFormat,m=g.xAxis,E=c[(a.isFooter?"footer":"header")+"Format"];if(m&&"datetime"===m.options.type&&e&&k(f.key)){var n=g.currentDataGrouping;e=e.dateTimeLabelFormats||p.dateTimeLabelFormats;if(n)if(c=e[n.unitName],1===n.count)h=c[0];else{h=c[1];var u=c[2]}else!h&&e&&(h=this.getXDateFormat(f,c,m));h=b.dateFormat(h,f.key);u&&(h+=b.dateFormat(u,f.key+n.totalRange-1));
g.chart.styledMode&&(E=this.styledModeFormat(E));a.text=z(E,{point:v(f.point,{key:h}),series:g},d);a.preventDefault()}});e(a,"destroy",F.destroyGroupedData);e(a,"afterSetOptions",function(a){a=a.options;var b=this.type,f=this.chart.options.plotOptions,g=n.defaultOptions.plotOptions[b].dataGrouping,c=this.useCommonDataGrouping&&p;if(d[b]||c)g||(g=H(p,d[b])),a.dataGrouping=H(c,g,f.series&&f.series.dataGrouping,f[b].dataGrouping,this.userOptions.dataGrouping)});e(b,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=
!1})});b.prototype.getGroupPixelWidth=function(){var a=this.series,d=a.length,b,g=0,c=!1,e;for(b=d;b--;)(e=a[b].options.dataGrouping)&&(g=Math.max(g,G(e.groupPixelWidth,p.groupPixelWidth)));for(b=d;b--;)(e=a[b].options.dataGrouping)&&a[b].hasProcessed&&(d=(a[b].processedXData||a[b].data).length,a[b].groupPixelWidth||d>this.chart.plotSizeX/g||d&&e.forced)&&(c=!0);return c?g:0};b.prototype.setDataGrouping=function(a,d){var g;d=G(d,!0);a||(a={forced:!1,units:null});if(this instanceof b)for(g=this.series.length;g--;)this.series[g].update({dataGrouping:a},
!1);else this.chart.options.series.forEach(function(d){d.dataGrouping=a},!1);this.ordinal&&(this.ordinal.slope=void 0);d&&this.chart.redraw()};B.dataGrouping=A;"";return A});K(b,"Series/OHLCSeries.js",[b["Core/Series/Series.js"],b["Core/Series/Point.js"]],function(b,w){var B=b.seriesTypes;b.seriesType("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(b){return[b.open,b.high,b.low,b.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){B.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},pointAttribs:function(b,y){y=B.column.prototype.pointAttribs.call(this,b,y);var n=this.options;delete y.fill;!b.options.color&&n.upColor&&b.open<b.close&&
(y.stroke=n.upColor);return y},translate:function(){var b=this,y=b.yAxis,t=!!b.modifyValue,a=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];B.column.prototype.translate.apply(b);b.points.forEach(function(e){[e.open,e.high,e.low,e.close,e.low].forEach(function(n,D){null!==n&&(t&&(n=b.modifyValue(n)),e[a[D]]=y.toPixels(n,!0))});e.tooltipPos[1]=e.plotHigh+y.pos-b.chart.plotTop})},drawPoints:function(){var b=this,y=b.chart,t=function(a,b,n){var e=a[0];a=a[1];"number"===typeof e[2]&&(e[2]=Math.max(n+
b,e[2]));"number"===typeof a[2]&&(a[2]=Math.min(n-b,a[2]))};b.points.forEach(function(a){var e=a.graphic,n=!e;if("undefined"!==typeof a.plotY){e||(a.graphic=e=y.renderer.path().add(b.group));y.styledMode||e.attr(b.pointAttribs(a,a.selected&&"select"));var w=e.strokeWidth();var B=w%2/2;var u=Math.round(a.plotX)-B;var C=Math.round(a.shapeArgs.width/2);var v=[["M",u,Math.round(a.yBottom)],["L",u,Math.round(a.plotHigh)]];if(null!==a.open){var z=Math.round(a.plotOpen)+B;v.push(["M",u,z],["L",u-C,z]);t(v,
w/2,z)}null!==a.close&&(z=Math.round(a.plotClose)+B,v.push(["M",u,z],["L",u+C,z]),t(v,w/2,z));e[n?"attr":"animate"]({d:v}).addClass(a.getClassName(),!0)}})},animate:null},{getClassName:function(){return w.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});K(b,"Series/CandlestickSeries.js",[b["Core/Series/Series.js"],b["Core/Options.js"],b["Core/Utilities.js"]],function(b,w,B){w=w.defaultOptions;B=B.merge;var n=b.seriesTypes.column.prototype;
b.seriesType("candlestick","ohlc",B(w.plotOptions.column,{states:{hover:{lineWidth:2}},tooltip:w.plotOptions.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(b,t){var a=n.pointAttribs.call(this,b,t),e=this.options,y=b.open<b.close,w=e.lineColor||this.color;a["stroke-width"]=e.lineWidth;a.fill=b.options.color||(y?e.upColor||this.color:this.color);a.stroke=b.options.lineColor||(y?e.upLineColor||w:w);t&&(b=e.states[t],a.fill=b.color||
a.fill,a.stroke=b.lineColor||a.stroke,a["stroke-width"]=b.lineWidth||a["stroke-width"]);return a},drawPoints:function(){var b=this,n=b.chart,a=b.yAxis.reversed;b.points.forEach(function(e){var t=e.graphic,y=!t;if("undefined"!==typeof e.plotY){t||(e.graphic=t=n.renderer.path().add(b.group));b.chart.styledMode||t.attr(b.pointAttribs(e,e.selected&&"select")).shadow(b.options.shadow);var w=t.strokeWidth()%2/2;var u=Math.round(e.plotX)-w;var C=e.plotOpen;var v=e.plotClose;var z=Math.min(C,v);C=Math.max(C,
v);var k=Math.round(e.shapeArgs.width/2);v=a?C!==e.yBottom:Math.round(z)!==Math.round(e.plotHigh);var B=a?Math.round(z)!==Math.round(e.plotHigh):C!==e.yBottom;z=Math.round(z)+w;C=Math.round(C)+w;w=[];w.push(["M",u-k,C],["L",u-k,z],["L",u+k,z],["L",u+k,C],["Z"],["M",u,z],["L",u,v?Math.round(a?e.yBottom:e.plotHigh):z],["M",u,C],["L",u,B?Math.round(a?e.plotHigh:e.yBottom):C]);t[y?"attr":"animate"]({d:w}).addClass(e.getClassName(),!0)}})}});""});K(b,"Mixins/OnSeries.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],
function(b,w){var B=w.defined,n=w.stableSort,y=b.seriesTypes;return{getPlotBox:function(){return b.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){y.column.prototype.translate.apply(this);var b=this,a=b.options,e=b.chart,w=b.points,D=w.length-1,J,u=a.onSeries;u=u&&e.get(u);a=a.onKey||"y";var C=u&&u.options.step,v=u&&u.points,z=v&&v.length,k=e.inverted,H=b.xAxis,G=b.yAxis,c=0,m;if(u&&u.visible&&z){c=(u.pointXOffset||0)+(u.barW||
0)/2;e=u.currentDataGrouping;var A=v[z-1].x+(e?e.totalRange:0);n(w,function(a,b){return a.x-b.x});for(a="plot"+a[0].toUpperCase()+a.substr(1);z--&&w[D];){var F=v[z];e=w[D];e.y=F.y;if(F.x<=e.x&&"undefined"!==typeof F[a]){if(e.x<=A&&(e.plotY=F[a],F.x<e.x&&!C&&(m=v[z+1])&&"undefined"!==typeof m[a])){var h=(e.x-F.x)/(m.x-F.x);e.plotY+=h*(m[a]-F[a]);e.y+=h*(m.y-F.y)}D--;z++;if(0>D)break}}}w.forEach(function(a,p){a.plotX+=c;if("undefined"===typeof a.plotY||k)0<=a.plotX&&a.plotX<=H.len?k?(a.plotY=H.translate(a.x,
0,1,0,1),a.plotX=B(a.y)?G.translate(a.y,0,0,0,1):0):a.plotY=(H.opposite?0:b.yAxis.len)+H.offset:a.shapeArgs={};if((J=w[p-1])&&J.plotX===a.plotX){"undefined"===typeof J.stackIndex&&(J.stackIndex=0);var d=J.stackIndex+1}a.stackIndex=d});this.onSeries=u}}});K(b,"Series/FlagsSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Mixins/OnSeries.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,w,B,n,y,t){function a(a){G[a+"pin"]=
function(b,c,e,h,g){var p=g&&g.anchorX;g=g&&g.anchorY;"circle"===a&&h>e&&(b-=Math.round((h-e)/2),e=h);var d=G[a](b,c,e,h);if(p&&g){var m=p;"circle"===a?m=b+e/2:(b=d[0],e=d[1],"M"===b[0]&&"L"===e[0]&&(m=(b[1]+e[1])/2));d.push(["M",m,c>g?c:c+h],["L",p,g]);d=d.concat(G.circle(p-1,g-1,2,2))}return d}}var e=w.noop,L=t.addEvent,D=t.defined,J=t.isNumber,u=t.merge,C=t.objectEach,v=t.wrap;t=w.Renderer;var z=w.Series,k=w.TrackerMixin,H=w.VMLRenderer,G=y.prototype.symbols;"";b.seriesType("flags","column",{pointRange:0,
allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:z.prototype.init,pointAttribs:function(a,b){var c=this.options,e=a&&a.color||this.color,h=c.lineColor,g=a&&a.lineWidth;a=a&&a.fillColor||
c.fillColor;b&&(a=c.states[b].fillColor,h=c.states[b].lineColor,g=c.states[b].lineWidth);return{fill:a||e,stroke:h||e,"stroke-width":g||c.lineWidth||0}},translate:B.translate,getPlotBox:B.getPlotBox,drawPoints:function(){var a=this.points,b=this.chart,e=b.renderer,k=b.inverted,h=this.options,g=h.y,p,d=this.yAxis,E={},f=[];for(p=a.length;p--;){var r=a[p];var q=(k?r.plotY:r.plotX)>this.xAxis.len;var l=r.plotX;var x=r.stackIndex;var I=r.options.shape||h.shape;var t=r.plotY;"undefined"!==typeof t&&(t=
r.plotY+g-("undefined"!==typeof x&&x*h.stackDistance));r.anchorX=x?void 0:r.plotX;var y=x?void 0:r.plotY;var z="flag"!==I;x=r.graphic;"undefined"!==typeof t&&0<=l&&!q?(x||(x=r.graphic=e.label("",null,null,I,null,null,h.useHTML),b.styledMode||x.attr(this.pointAttribs(r)).css(u(h.style,r.style)),x.attr({align:z?"center":"left",width:h.width,height:h.height,"text-align":h.textAlign}).addClass("highcharts-point").add(this.markerGroup),r.graphic.div&&(r.graphic.div.point=r),b.styledMode||x.shadow(h.shadow),
x.isNew=!0),0<l&&(l-=x.strokeWidth()%2),I={y:t,anchorY:y},h.allowOverlapX&&(I.x=l,I.anchorX=r.anchorX),x.attr({text:r.options.title||h.title||"A"})[x.isNew?"attr":"animate"](I),h.allowOverlapX||(E[r.plotX]?E[r.plotX].size=Math.max(E[r.plotX].size,x.width):E[r.plotX]={align:z?.5:0,size:x.width,target:l,anchorX:l}),r.tooltipPos=[l,t+d.pos-b.plotTop]):x&&(r.graphic=x.destroy())}h.allowOverlapX||(C(E,function(a){a.plotX=a.anchorX;f.push(a)}),w.distribute(f,k?d.len:this.xAxis.len,100),a.forEach(function(a){var b=
a.graphic&&E[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos+b.align*b.size,anchorX:a.anchorX}),D(b.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));h.useHTML&&v(this.markerGroup,"on",function(a){return n.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;k.drawTrackerPoint.apply(this);a.forEach(function(b){var c=b.graphic;c&&L(c.element,"mouseover",function(){0<
b.stackIndex&&!b.raised&&(b._y=c.y,c.attr({y:b._y-8}),b.raised=!0);a.forEach(function(a){a!==b&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:function(a){a&&this.setClip()},setClip:function(){z.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:e,invertGroups:e},{isValid:function(){return J(this.y)||"undefined"===typeof this.y}});G.flag=function(a,b,e,k,h){var g=h&&h.anchorX||
a;h=h&&h.anchorY||b;var c=G.circle(g-1,h-1,2,2);c.push(["M",g,h],["L",a,b+k],["L",a,b],["L",a+e,b],["L",a+e,b+k],["L",a,b+k],["Z"]);return c};a("circle");a("square");t===H&&["circlepin","flag","squarepin"].forEach(function(a){H.prototype.symbols[a]=G[a]});""});K(b,"Extensions/RangeSelector.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Utilities.js"]],function(b,w,B,n,y,t){var a=n.defaultOptions,e=t.addEvent,
L=t.createElement,D=t.css,J=t.defined,u=t.destroyObjectProperties,C=t.discardElement,v=t.extend,z=t.fireEvent,k=t.isNumber,H=t.merge,G=t.objectEach,c=t.pick,m=t.pInt,A=t.splat;v(a,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});a.lang=H(a.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var F=
function(){function h(a){this.buttons=void 0;this.buttonOptions=h.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}h.prototype.clickButton=function(a,p){var d=this.chart,g=this.buttonOptions[a],f=d.xAxis[0],h=d.scroller&&d.scroller.getUnionExtremes()||f||{},q=h.dataMin,l=h.dataMax,m=f&&Math.round(Math.min(f.max,c(l,f.max))),n=g.type;h=g._range;var u,v=g.dataGrouping;if(null!==q&&null!==l){d.fixedRange=h;v&&(this.forcedDataGrouping=!0,b.prototype.setDataGrouping.call(f||{chart:this.chart},
v,!1),this.frozenStates=g.preserveDataGrouping);if("month"===n||"year"===n)if(f){n={range:g,max:m,chart:d,dataMin:q,dataMax:l};var t=f.minFromRange.call(n);k(n.newMax)&&(m=n.newMax)}else h=g;else if(h)t=Math.max(m-h,q),m=Math.min(t+h,l);else if("ytd"===n)if(f)"undefined"===typeof l&&(q=Number.MAX_VALUE,l=Number.MIN_VALUE,d.series.forEach(function(a){a=a.xData;q=Math.min(a[0],q);l=Math.max(a[a.length-1],l)}),p=!1),m=this.getYTDExtremes(l,q,d.time.useUTC),t=u=m.min,m=m.max;else{this.deferredYTDClick=
a;return}else"all"===n&&f&&(t=q,m=l);J(t)&&(t+=g._offsetMin);J(m)&&(m+=g._offsetMax);this.setSelected(a);if(f)f.setExtremes(t,m,c(p,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:g});else{var w=A(d.options.xAxis)[0];var y=w.range;w.range=h;var z=w.min;w.min=u;e(d,"load",function(){w.range=y;w.min=z})}}};h.prototype.setSelected=function(a){this.selected=this.options.selected=a};h.prototype.init=function(a){var b=this,d=a.options.rangeSelector,g=d.buttons||b.defaultButtons.slice(),f=d.selected,
c=function(){var a=b.minInput,d=b.maxInput;a&&a.blur&&z(a,"blur");d&&d.blur&&z(d,"blur")};b.chart=a;b.options=d;b.buttons=[];b.buttonOptions=g;this.unMouseDown=e(a.container,"mousedown",c);this.unResize=e(a,"resize",c);g.forEach(b.computeButtonRange);"undefined"!==typeof f&&g[f]&&this.clickButton(f,!1);e(a,"load",function(){a.xAxis&&a.xAxis[0]&&e(a.xAxis[0],"setExtremes",function(d){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==d.trigger&&b.forcedDataGrouping&&
!b.frozenStates&&this.setDataGrouping(!1,!1)})})};h.prototype.updateButtonStates=function(){var a=this,b=this.chart,d=b.xAxis[0],c=Math.round(d.max-d.min),f=!d.hasVisibleSeries,e=b.scroller&&b.scroller.getUnionExtremes()||d,h=e.dataMin,l=e.dataMax;b=a.getYTDExtremes(l,h,b.time.useUTC);var m=b.min,n=b.max,u=a.selected,v=k(u),t=a.options.allButtonsEnabled,w=a.buttons;a.buttonOptions.forEach(function(b,g){var e=b._range,p=b.type,r=b.count||1,q=w[g],k=0,E=b._offsetMax-b._offsetMin;b=g===u;var x=e>l-h,
I=e<d.minRange,y=!1,z=!1;e=e===c;("month"===p||"year"===p)&&c+36E5>=864E5*{month:28,year:365}[p]*r-E&&c-36E5<=864E5*{month:31,year:366}[p]*r+E?e=!0:"ytd"===p?(e=n-m+E===c,y=!b):"all"===p&&(e=d.max-d.min>=l-h,z=!b&&v&&e);p=!t&&(x||I||z||f);r=b&&e||e&&!v&&!y||b&&a.frozenStates;p?k=3:r&&(v=!0,k=2);q.state!==k&&(q.setState(k),0===k&&u===g&&a.setSelected(null))})};h.prototype.computeButtonRange=function(a){var b=a.type,d=a.count||1,g={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};
if(g[b])a._range=g[b]*d;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*d;a._offsetMin=c(a.offsetMin,0);a._offsetMax=c(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin};h.prototype.setInputValue=function(a,b){var d=this.chart.options.rangeSelector,g=this.chart.time,f=this[a+"Input"];J(b)&&(f.previousValue=f.HCTime,f.HCTime=b);f.value=g.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",f.HCTime);this[a+"DateBox"].attr({text:g.dateFormat(d.inputDateFormat||"%b %e, %Y",f.HCTime)})};
h.prototype.showInput=function(a){var b=this.inputGroup,d=this[a+"DateBox"];D(this[a+"Input"],{left:b.translateX+d.x+"px",top:b.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})};h.prototype.hideInput=function(a){D(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)};h.prototype.defaultInputDateParser=function(a,b){var d=new Date;return B.isSafari?Date.parse(a.split(" ").join("T")):b?Date.parse(a+"Z"):Date.parse(a)-6E4*d.getTimezoneOffset()};
h.prototype.drawInput=function(b){function c(){var a=u.value,b=g.xAxis[0];var f=g.scroller&&g.scroller.xAxis?g.scroller.xAxis:b;var c=f.dataMin,e=f.dataMax;f=(h.inputDateParser||y)(a,g.time.useUTC);f!==u.previousValue&&(u.previousValue=f,k(f)||(f=a.split("-"),f=Date.UTC(m(f[0]),m(f[1])-1,m(f[2]))),k(f)&&(g.time.useUTC||(f+=6E4*(new Date).getTimezoneOffset()),n?f>d.maxInput.HCTime?f=void 0:f<c&&(f=c):f<d.minInput.HCTime?f=void 0:f>e&&(f=e),"undefined"!==typeof f&&b.setExtremes(n?f:b.min,n?b.max:f,
void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,g=d.chart,f=g.renderer.style||{},e=g.renderer,h=g.options.rangeSelector,l=d.div,n="min"===b,u,t,w=this.inputGroup,y=this.defaultInputDateParser;this[b+"Label"]=t=e.label(a.lang[n?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(w);w.offset+=t.width+5;this[b+"DateBox"]=e=e.label("",w.offset).addClass("highcharts-range-input").attr({padding:2,width:h.inputBoxWidth||90,height:h.inputBoxHeight||
17,"text-align":"center"}).on("click",function(){d.showInput(b);d[b+"Input"].focus()});g.styledMode||e.attr({stroke:h.inputBoxBorderColor||"#cccccc","stroke-width":1});e.add(w);w.offset+=e.width+(n?10:0);this[b+"Input"]=u=L("input",{name:b,className:"highcharts-range-selector",type:"text"},{top:g.plotTop+"px"},l);g.styledMode||(t.css(H(f,h.labelStyle)),e.css(H({color:"#333333"},f,h.inputStyle)),D(u,v({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:f.fontSize,
fontFamily:f.fontFamily,top:"-9999em"},h.inputStyle)));u.onfocus=function(){d.showInput(b)};u.onblur=function(){u===B.doc.activeElement&&c();d.hideInput(b);u.blur()};u.onchange=c;u.onkeypress=function(a){13===a.keyCode&&c()}};h.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};h.prototype.getYTDExtremes=function(a,b,d){var c=this.chart.time,f=new c.Date(a),
g=c.get("FullYear",f);d=d?c.Date.UTC(g,0,1):+new c.Date(g,0,1);b=Math.max(b||0,d);f=f.getTime();return{max:Math.min(a||f,f),min:b}};h.prototype.render=function(b,e){var d=this,g=d.chart,f=g.renderer,h=g.container,p=g.options,l=p.exporting&&!1!==p.exporting.enabled&&p.navigation&&p.navigation.buttonOptions,m=a.lang,k=d.div,n=p.rangeSelector,u=c(p.chart.style&&p.chart.style.zIndex,0)+1;p=n.floating;var v=d.buttons;k=d.inputGroup;var t=n.buttonTheme,w=n.buttonPosition,y=n.inputPosition,z=n.inputEnabled,
C=t&&t.states,A=g.plotLeft,B=d.buttonGroup,F,D=d.options.verticalAlign,G=g.legend,H=G&&G.options,J=w.y,K=y.y,P=g.hasLoaded,Q=P?"animate":"attr",O=0,N=0;if(!1!==n.enabled){d.rendered||(d.group=F=f.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=B=f.g("range-selector-buttons").add(F),d.zoomText=f.text(m.rangeSelectorZoom,0,15).add(B),g.styledMode||(d.zoomText.css(n.labelStyle),t["stroke-width"]=c(t["stroke-width"],0)),d.buttonOptions.forEach(function(a,b){v[b]=f.button(a.text,0,0,function(f){var g=
a.events&&a.events.click,c;g&&(c=g.call(a,f));!1!==c&&d.clickButton(b);d.isActive=!0},t,C&&C.hover,C&&C.select,C&&C.disabled).attr({"text-align":"center"}).add(B)}),!1!==z&&(d.div=k=L("div",null,{position:"relative",height:0,zIndex:u}),h.parentNode.insertBefore(k,h),d.inputGroup=k=f.g("input-group").add(F),k.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[Q]({x:c(A+w.x,A)});var R=c(A+w.x,A)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(a,b){v[b][Q]({x:R});R+=v[b].width+
c(n.buttonSpacing,5)});A=g.plotLeft-g.spacing[3];d.updateButtonStates();l&&this.titleCollision(g)&&"top"===D&&"right"===w.align&&w.y+B.getBBox().height-12<(l.y||0)+l.height&&(O=-40);h=w.x-g.spacing[3];"right"===w.align?h+=O-A:"center"===w.align&&(h-=A/2);B.align({y:w.y,width:B.getBBox().width,align:w.align,x:h},!0,g.spacingBox);d.group.placed=P;d.buttonGroup.placed=P;!1!==z&&(O=l&&this.titleCollision(g)&&"top"===D&&"right"===y.align&&y.y-k.getBBox().height-12<(l.y||0)+l.height+g.spacing[0]?-40:0,
"left"===y.align?h=A:"right"===y.align&&(h=-Math.max(g.axisOffset[1],-O)),k.align({y:y.y,width:k.getBBox().width,align:y.align,x:y.x+h-2},!0,g.spacingBox),l=k.alignAttr.translateX+k.alignOptions.x-O+k.getBBox().x+2,h=k.alignOptions.width,m=B.alignAttr.translateX+B.getBBox().x,A=B.getBBox().width+20,(y.align===w.align||m+A>l&&l+h>m&&J<K+k.getBBox().height)&&k.attr({translateX:k.alignAttr.translateX+(g.axisOffset[1]>=-O?0:-O),translateY:k.alignAttr.translateY+B.getBBox().height+10}),d.setInputValue("min",
b),d.setInputValue("max",e),d.inputGroup.placed=P);d.group.align({verticalAlign:D},!0,g.spacingBox);b=d.group.getBBox().height+20;e=d.group.alignAttr.translateY;"bottom"===D&&(G=H&&"bottom"===H.verticalAlign&&H.enabled&&!H.floating?G.legendHeight+c(H.margin,10):0,b=b+G-20,N=e-b-(p?0:n.y)-(g.titleOffset?g.titleOffset[2]:0)-10);if("top"===D)p&&(N=0),g.titleOffset&&g.titleOffset[0]&&(N=g.titleOffset[0]),N+=g.margin[0]-g.spacing[0]||0;else if("middle"===D)if(K===J)N=0>K?e+void 0:e;else if(K||J)N=0>K||
0>J?N-Math.min(K,J):e-b+NaN;d.group.translate(n.x,n.y+Math.floor(N));!1!==z&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}};h.prototype.getHeight=function(){var a=this.options,b=this.group,d=a.y,c=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+d:0;b=Math.min(f,c);if(0>f&&0>c||0<f&&0<c)a+=Math.abs(b);return a};h.prototype.titleCollision=function(a){return!(a.options.title.text||
a.options.subtitle.text)};h.prototype.update=function(a){var b=this.chart;H(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};h.prototype.destroy=function(){var a=this,b=a.minInput,d=a.maxInput;a.unMouseDown();a.unResize();u(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);G(a,function(b,d){b&&"chart"!==d&&(b instanceof y?b.destroy():b instanceof window.HTMLElement&&C(b));b!==h.prototype[d]&&(a[d]=null)},this)};return h}();
F.prototype.defaultButtons=[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}];b.prototype.minFromRange=function(){var a=this.range,b=a.type,e=this.max,d=this.chart.time,m=function(a,f){var c="year"===b?"FullYear":"Month",e=new d.Date(a),g=d.get(c,e);d.set(c,e,g+f);g===d.get(c,e)&&d.set("Date",e,0);return e.getTime()-a};if(k(a)){var f=e-a;var r=a}else f=e+m(e,-a.count),
this.chart&&(this.chart.fixedRange=e-f);var q=c(this.dataMin,Number.MIN_VALUE);k(f)||(f=q);f<=q&&(f=q,"undefined"===typeof r&&(r=m(f,a.count)),this.newMax=Math.min(f+r,this.dataMax));k(e)||(f=void 0);return f};B.RangeSelector||(e(w,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new F(this))}),e(w,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(k(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();
a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),e(w,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!J(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new F(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,
a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),e(w,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),e(w,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&
(this.marginBottom+=a))}),w.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();h=a.legend;m=null===d||void 0===d?void 0:d.options.verticalAlign;k(c.min)&&d.render(c.min,c.max);d&&h.display&&"top"===m&&m===h.options.verticalAlign&&(f=H(a.spacingBox),f.y="vertical"===h.options.layout?a.plotTop:f.y+d.getHeight(),h.group.placed=!1,h.align(f))}var c,d=a.rangeSelector,h,f,m;if(d){var q=e(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var l=e(a,"redraw",b);b()}e(a,
"destroy",function(){d&&(l(),q())})}),B.RangeSelector=F);return B.RangeSelector});K(b,"Core/Chart/StockChart.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Series/LineSeries.js"],b["Core/Series/Point.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,w,B,n,y,t,a){var e=a.addEvent,K=a.arrayMax,D=a.arrayMin,J=a.clamp,u=a.defined,C=a.extend,v=a.find,z=a.format,k=a.getOptions,H=a.isNumber,G=a.isString,c=a.merge,m=a.pick,A=a.splat;a=n.prototype;
var F=a.init,h=a.processData,g=y.prototype.tooltipFormatter;B.StockChart=B.stockChart=function(a,b,e){var d=G(a)||a.nodeName,g=arguments[d?1:0],h=g,l=g.series,p=k(),n,u=m(g.navigator&&g.navigator.enabled,p.navigator.enabled,!0);g.xAxis=A(g.xAxis||{}).map(function(a,b){return c({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},p.xAxis,p.xAxis&&p.xAxis[b],a,{type:"datetime",categories:null},u?{startOnTick:!1,endOnTick:!1}:null)});g.yAxis=
A(g.yAxis||{}).map(function(a,b){n=m(a.opposite,!0);return c({labels:{y:-2},opposite:n,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},p.yAxis,p.yAxis&&p.yAxis[b],a)});g.series=null;g=c({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:u},scrollbar:{enabled:m(p.scrollbar.enabled,!0)},rangeSelector:{enabled:m(p.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:m(p.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});g.series=h.series=
l;return d?new w(a,g,e):new w(g,b)};e(n,"setOptions",function(a){var b;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=c(a.plotOptions[this.type],b)))});e(b,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var f=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&
f.enabled&&(15===f.x&&(f.x=0),"undefined"===typeof f.align&&(f.align="right"),b[c]=this,a.align="right",a.preventDefault()))});e(b,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});e(b,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return H(a)?[e[b][a]]:G(a)?[e.get(a)]:f.map(function(a){return a[b]})}var c=this,f=this.isLinked&&!this.series?
this.linkedParent.series:this.series,e=c.chart,g=e.renderer,h=c.left,k=c.top,p,n,t,w,y=[],z=[],C=a.translatedValue,A=a.value,B=a.force;if(e.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){a.preventDefault();z=b(c.coll);var F=c.isXAxis?e.yAxis:e.xAxis;F.forEach(function(a){if(u(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=u(a.options[b])?e[b][a.options[b]]:e[b][0];c===b&&z.push(a)}});var D=z.length?[]:[c.isXAxis?e.yAxis[0]:e.xAxis[0]];
z.forEach(function(a){-1!==D.indexOf(a)||v(D,function(b){return b.pos===a.pos&&b.len===a.len})||D.push(a)});var K=m(C,c.translate(A,null,null,a.old));H(K)&&(c.horiz?D.forEach(function(a){var b;n=a.pos;w=n+a.len;p=t=Math.round(K+c.transB);"pass"!==B&&(p<h||p>h+c.width)&&(B?p=t=J(p,h,h+c.width):b=!0);b||y.push(["M",p,n],["L",t,w])}):D.forEach(function(a){var b;p=a.pos;t=p+a.len;n=w=Math.round(k+c.height-K);"pass"!==B&&(n<k||n>k+c.height)&&(B?n=w=J(n,k,k+c.height):b=!0);b||y.push(["M",p,n],["L",t,w])}));
a.path=0<y.length?g.crispPolyLine(y,a.lineWidth||1):null}});t.prototype.crispPolyLine=function(a,b){for(var d=0;d<a.length;d+=2){var c=a[d],e=a[d+1];c[1]===e[1]&&(c[1]=e[1]=Math.round(c[1])-b%2/2);c[2]===e[2]&&(c[2]=e[2]=Math.round(c[2])+b%2/2)}return a};e(b,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});e(b,"afterDrawCrosshair",function(a){var b,c;if(u(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var f=this.chart,e=this.logarithmic,
g=this.options.crosshair.label,h=this.horiz,k=this.opposite,p=this.left,n=this.top,t=this.crossLabel,w=g.format,v="",y="inside"===this.options.tickPosition,A=!1!==this.crosshair.snap,B=0,D=a.e||this.cross&&this.cross.e,F=a.point;a=this.min;var G=this.max;e&&(a=e.lin2log(a),G=e.lin2log(G));e=h?"center":k?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";t||(t=this.crossLabel=f.renderer.label(null,null,null,g.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&
" highcharts-color-"+this.series[0].colorIndex)).attr({align:g.align||e,padding:m(g.padding,8),r:m(g.borderRadius,3),zIndex:2}).add(this.labelGroup),f.styledMode||t.attr({fill:g.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:g.borderColor||"","stroke-width":g.borderWidth||0}).css(C({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},g.style)));h?(e=A?F.plotX+p:D.chartX,n+=k?0:this.height):(e=k?this.width+p:0,n=A?F.plotY+n:D.chartY);w||g.formatter||(this.dateTime&&
(v="%b %d, %Y"),w="{value"+(v?":"+v:"")+"}");v=A?F[this.isXAxis?"x":"y"]:this.toValue(h?D.chartX:D.chartY);t.attr({text:w?z(w,{value:v},f):g.formatter.call(this,v),x:e,y:n,visibility:v<a||v>G?"hidden":"visible"});g=t.getBBox();if(H(t.y))if(h){if(y&&!k||!y&&k)n=t.y-g.height}else n=t.y-g.height/2;h?(b=p-g.x,c=p+this.width-g.x):(b="left"===this.labelAlign?p:0,c="right"===this.labelAlign?p+this.width:f.chartWidth);t.translateX<b&&(B=b-t.translateX);t.translateX+g.width>=c&&(B=-(t.translateX+g.width-c));
t.attr({x:e+B,y:n,anchorX:h?e:this.opposite?0:f.chartWidth,anchorY:h?this.opposite?f.chartHeight:0:n+g.height/2})}});a.init=function(){F.apply(this,arguments);this.setCompare(this.options.compare)};a.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&
(this.isDirty=!0)};a.processData=function(a){var b,c=-1,f=!0===this.options.compareStart?0:1;h.apply(this,arguments);if(this.xAxis&&this.processedYData){var e=this.processedXData;var g=this.processedYData;var l=g.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<l-f;b++){var k=g[b]&&-1<c?g[b][c]:g[b];if(H(k)&&e[b+f]>=this.xAxis.min&&0!==k){this.compareValue=k;break}}}};e(n,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&
a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];a.dataMin=D(b);a.dataMax=K(b)}});b.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),m(b,!0)&&this.chart.redraw())};y.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,m(this.series.tooltipOptions.changeDecimals,2)));return g.apply(this,[a])};e(n,"render",function(){var a=this.chart;if(!(a.is3d&&
a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var e=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,f=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=e&&(b-=Math.max(f-e,0))}this.clipBox||a.hasRendered?a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len})):(this.clipBox=c(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=
b)}});e(w,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(c(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})});K(b,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map