/*
 Highcharts Gantt JS v8.2.2 (2020-10-27)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(B){b(B);b.Highcharts=B;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function B(b,t,E,w){b.hasOwnProperty(t)||(b[t]=w.apply(null,E))}b=b?b._modules:{};B(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var t=b.extend,x=b.isNumber,w=b.pick,q=function(b,k){var p=b.reduce(function(e,
p){var m=w(p.parent,"");"undefined"===typeof e[m]&&(e[m]=[]);e[m].push(p);return e},{});Object.keys(p).forEach(function(e,b){var m=p[e];""!==e&&-1===k.indexOf(e)&&(m.forEach(function(e){b[""].push(e)}),delete b[e])});return p},k=function(b,q,p,e,C,m){var r=0,n=0,l=m&&m.after,a=m&&m.before;q={data:e,depth:p-1,id:b,level:p,parent:q};var g,h;"function"===typeof a&&a(q,m);a=(C[b]||[]).map(function(d){var c=k(d.id,b,p+1,d,C,m),f=d.start;d=!0===d.milestone?f:d.end;g=!x(g)||f<g?f:g;h=!x(h)||d>h?d:h;r=r+
1+c.descendants;n=Math.max(c.height+1,n);return c});e&&(e.start=w(e.start,g),e.end=w(e.end,h));t(q,{children:a,descendants:r,height:n});"function"===typeof l&&l(q,m);return q};return{getListOfParents:q,getNode:k,getTree:function(b,t){var p=b.map(function(e){return e.id});b=q(b,p);return k("",null,1,null,b,t)}}});B(b,"Core/Axis/TreeGridTick.js",[b["Core/Utilities.js"]],function(b){var t=b.addEvent,E=b.defined,w=b.isObject,q=b.isNumber,k=b.pick,u=b.wrap,x;(function(b){function e(){this.treeGrid||(this.treeGrid=
new l(this))}function p(a,g){a=a.treeGrid;var h=!a.labelIcon,d=g.renderer,c=g.xy,f=g.options,A=f.width,D=f.height,H=c.x-A/2-f.padding;c=c.y-D/2;var b=g.collapsed?90:180,e=g.show&&q(c),v=a.labelIcon;v||(a.labelIcon=v=d.path(d.symbols[f.type](f.x,f.y,A,D)).addClass("highcharts-label-icon").add(g.group));e||v.attr({y:-9999});d.styledMode||v.attr({"stroke-width":1,fill:k(g.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});v[h?"attr":"animate"]({translateX:H,translateY:c,
rotation:b})}function m(a,g,h,d,c,f,A,D,b){var e=k(this.options&&this.options.labels,f);f=this.pos;var H=this.axis,v="treegrid"===H.options.type;a=a.apply(this,[g,h,d,c,e,A,D,b]);v&&(g=e&&w(e.symbol,!0)?e.symbol:{},e=e&&q(e.indentation)?e.indentation:0,f=(f=(H=H.treeGrid.mapOfPosToGridNode)&&H[f])&&f.depth||1,a.x+=g.width+2*g.padding+(f-1)*e);return a}function r(a){var g=this,h=g.pos,d=g.axis,c=g.label,f=d.treeGrid.mapOfPosToGridNode,A=d.options,D=k(g.options&&g.options.labels,A&&A.labels),e=D&&w(D.symbol,
!0)?D.symbol:{},b=(f=f&&f[h])&&f.depth;A="treegrid"===A.type;var r=-1<d.tickPositions.indexOf(h);h=d.chart.styledMode;A&&f&&c&&c.element&&c.addClass("highcharts-treegrid-node-level-"+b);a.apply(g,Array.prototype.slice.call(arguments,1));A&&c&&c.element&&f&&f.descendants&&0<f.descendants&&(d=d.treeGrid.isCollapsed(f),p(g,{color:!h&&c.styles&&c.styles.color||"",collapsed:d,group:c.parentGroup,options:e,renderer:c.renderer,show:r,xy:c.xy}),e="highcharts-treegrid-node-"+(d?"expanded":"collapsed"),c.addClass("highcharts-treegrid-node-"+
(d?"collapsed":"expanded")).removeClass(e),h||c.css({cursor:"pointer"}),[c,g.treeGrid.labelIcon].forEach(function(f){f&&!f.attachedTreeGridEvents&&(t(f.element,"mouseover",function(){c.addClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:"underline"})}),t(f.element,"mouseout",function(){var f=E(D.style)?D.style:{};c.removeClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:f.textDecoration})}),t(f.element,"click",function(){g.treeGrid.toggleCollapse()}),
f.attachedTreeGridEvents=!0)}))}var n=!1;b.compose=function(a){n||(t(a,"init",e),u(a.prototype,"getLabelPosition",m),u(a.prototype,"renderLabel",r),a.prototype.collapse=function(a){this.treeGrid.collapse(a)},a.prototype.expand=function(a){this.treeGrid.expand(a)},a.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)},n=!0)};var l=function(){function a(a){this.tick=a}a.prototype.collapse=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.collapse(d.treeGrid.mapOfPosToGridNode[h.pos]),
c.setBreaks(h,k(a,!0)))};a.prototype.expand=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.expand(d.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,k(a,!0)))};a.prototype.toggleCollapse=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.toggleCollapse(d.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,k(a,!0)))};return a}();b.Additions=l})(x||(x={}));return x});B(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],
b["Core/Utilities.js"]],function(b,t){var x=t.extend,w=t.isArray,q=t.isNumber,k=t.isObject,u=t.merge,G=t.pick;return{getColor:function(p,e){var k=e.index,m=e.mapOptionsToLevel,r=e.parentColor,n=e.parentColorIndex,l=e.series,a=e.colors,g=e.siblings,h=l.points,d=l.chart.options.chart,c;if(p){h=h[p.i];p=m[p.level]||{};if(m=h&&p.colorByPoint){var f=h.index%(a?a.length:d.colorCount);var A=a&&a[f]}if(!l.chart.styledMode){a=h&&h.options.color;d=p&&p.color;if(c=r)c=(c=p&&p.colorVariation)&&"brightness"===
c.key?b.parse(r).brighten(k/g*c.to).get():r;c=G(a,d,A,c,l.color)}var D=G(h&&h.options.colorIndex,p&&p.colorIndex,f,n,e.colorIndex)}return{color:c,colorIndex:D}},getLevelOptions:function(b){var e=null;if(k(b)){e={};var p=q(b.from)?b.from:1;var m=b.levels;var r={};var n=k(b.defaults)?b.defaults:{};w(m)&&(r=m.reduce(function(b,a){if(k(a)&&q(a.level)){var e=u({},a);var h="boolean"===typeof e.levelIsConstant?e.levelIsConstant:n.levelIsConstant;delete e.levelIsConstant;delete e.level;a=a.level+(h?0:p-1);
k(b[a])?x(b[a],e):b[a]=e}return b},{}));m=q(b.to)?b.to:1;for(b=0;b<=m;b++)e[b]=u({},n,k(r[b])?r[b]:{})}return e},setTreeValues:function m(b,k){var e=k.before,n=k.idRoot,l=k.mapIdToNode[n],a=k.points[b.i],g=a&&a.options||{},h=0,d=[];x(b,{levelDynamic:b.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:l.level),name:G(a&&a.name,""),visible:n===b.id||("boolean"===typeof k.visible?k.visible:!1)});"function"===typeof e&&(b=e(b,k));b.children.forEach(function(c,f){var a=x({},k);x(a,{index:f,
siblings:b.children.length,visible:b.visible});c=m(c,a);d.push(c);c.visible&&(h+=c.val)});b.visible=0<h||b.visible;e=G(g.value,h);x(b,{children:d,childrenTotal:h,isLeaf:b.visible&&!h,val:e});return b},updateRootId:function(b){if(k(b)){var e=k(b.options)?b.options:{};e=G(b.rootNode,e.rootId,"");k(b.userOptions)&&(b.userOptions.rootId=e);b.rootNode=e}return e}}});B(b,"Core/Axis/GridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],
function(b,t,E,w,q){var k=q.addEvent,u=q.defined,x=q.erase,p=q.find,e=q.isArray,C=q.isNumber,m=q.merge,r=q.pick,n=q.timeUnits,l=q.wrap;E=t.Chart;var a=function(d){var c=d.options;c.labels||(c.labels={});c.labels.align=r(c.labels.align,"center");d.categories||(c.showLastLabel=!1);d.labelRotation=0;c.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(d,c){var f={width:0,height:0};c.forEach(function(c){c=d[c];if(q.isObject(c,!0)){var a=q.isObject(c.label,!0)?c.label:{};c=a.getBBox?a.getBBox().height:
0;a.textStr&&!C(a.textPxLength)&&(a.textPxLength=a.getBBox().width);var b=C(a.textPxLength)?Math.round(a.textPxLength):0;a.textStr&&(b=Math.round(a.getBBox().width));f.height=Math.max(c,f.height);f.width=Math.max(b,f.width)}});return f};t.dateFormats.W=function(a){a=new this.Date(a);var c=(this.get("Day",a)+6)%7,f=new this.Date(a.valueOf());this.set("Date",f,this.get("Date",a)-c+3);c=new this.Date(this.get("FullYear",f),0,1);4!==this.get("Day",c)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",
c))%7));return(1+Math.floor((f.valueOf()-c.valueOf())/6048E5)).toString()};t.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};k(E,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});k(w,"afterGetLabelPosition",function(a){var c=this.label,f=this.axis,d=f.reversed,b=f.chart,e=f.options.grid||{},g=f.options.labels,r=g.align,v=h.Side[f.side],n=a.tickmarkOffset,l=f.tickPositions,
F=this.pos-n;l=C(l[a.index+1])?l[a.index+1]-n:f.max+n;var y=f.tickSize("tick");n=y?y[0]:0;y=y?y[1]/2:0;if(!0===e.enabled){if("top"===v){e=f.top+f.offset;var z=e-n}else"bottom"===v?(z=b.chartHeight-f.bottom+f.offset,e=z+n):(e=f.top+f.len-f.translate(d?l:F),z=f.top+f.len-f.translate(d?F:l));"right"===v?(v=b.chartWidth-f.right+f.offset,d=v+n):"left"===v?(d=f.left+f.offset,v=d-n):(v=Math.round(f.left+f.translate(d?l:F))-y,d=Math.round(f.left+f.translate(d?F:l))-y);this.slotWidth=d-v;a.pos.x="left"===
r?v:"right"===r?d:v+(d-v)/2;a.pos.y=z+(e-z)/2;b=b.renderer.fontMetrics(g.style.fontSize,c.element);c=c.getBBox().height;g.useHTML?a.pos.y+=b.b+-(c/2):(c=Math.round(c/b.h),a.pos.y+=(b.b-(b.h-b.f))/2+-((c-1)*b.h/2));a.pos.x+=f.horiz&&g.x||0}});var g=function(){function a(c){this.axis=c}a.prototype.isOuterAxis=function(){var c=this.axis,a=c.grid.columnIndex,d=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,b=a?c.linkedParent:c,h=-1,e=0;c.chart[c.coll].forEach(function(a,f){a.side!==c.side||
a.options.isInternal||(e=f,a===b&&(h=f))});return e===h&&(C(a)?d.length===a:!0)};a.prototype.renderBorder=function(c){var a=this.axis,d=a.chart.renderer,b=a.options;c=d.path(c).addClass("highcharts-axis-line").add(a.axisBorder);d.styledMode||c.attr({stroke:b.lineColor,"stroke-width":b.lineWidth,zIndex:7});return c};return a}(),h=function(){function d(){}d.compose=function(c){b.keepProps.push("grid");l(c.prototype,"unsquish",d.wrapUnsquish);k(c,"init",d.onInit);k(c,"afterGetOffset",d.onAfterGetOffset);
k(c,"afterGetTitlePosition",d.onAfterGetTitlePosition);k(c,"afterInit",d.onAfterInit);k(c,"afterRender",d.onAfterRender);k(c,"afterSetAxisTranslation",d.onAfterSetAxisTranslation);k(c,"afterSetOptions",d.onAfterSetOptions);k(c,"afterSetOptions",d.onAfterSetOptions2);k(c,"afterSetScale",d.onAfterSetScale);k(c,"afterTickSize",d.onAfterTickSize);k(c,"trimTicks",d.onTrimTicks);k(c,"destroy",d.onDestroy)};d.onAfterGetOffset=function(){var c=this.grid;(c&&c.columns||[]).forEach(function(c){c.getOffset()})};
d.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||{}).enabled){var a=this.axisTitle,b=this.height,h=this.horiz,e=this.left,g=this.offset,n=this.opposite,l=this.options.title,k=void 0===l?{}:l;l=this.top;var m=this.width,F=this.tickSize(),y=a&&a.getBBox().width,z=k.x||0,K=k.y||0,p=r(k.margin,h?5:10);a=this.chart.renderer.fontMetrics(k.style&&k.style.fontSize,a).f;F=(h?l+b:e)+(h?1:-1)*(n?-1:1)*(F?F[0]/2:0)+(this.side===d.Side.bottom?a:0);c.titlePosition.x=h?e-y/2-p+z:F+(n?m:0)+g+z;c.titlePosition.y=
h?F-(n?b:0)+(n?a:-a)/2+g+K:l-p+K}};d.onAfterInit=function(){var c=this.chart,f=this.options.grid;f=void 0===f?{}:f;var d=this.userOptions;f.enabled&&(a(this),l(this,"labelFormatter",function(a){var c=this.axis,f=this.value,d=c.tickPositions,b=(c.isLinked?c.linkedParent:c).series[0],h=f===d[0];d=f===d[d.length-1];var e=b&&p(b.options.data,function(a){return a[c.isXAxis?"x":"y"]===f});if(e&&b.is("gantt")){var g=m(e);t.seriesTypes.gantt.prototype.setGanttPointAliases(g)}this.isFirst=h;this.isLast=d;
this.point=g;return a.call(this)}));if(f.columns)for(var h=this.grid.columns=[],e=this.grid.columnIndex=0;++e<f.columns.length;){var g=m(d,f.columns[f.columns.length-e-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete g.grid.columns;g=new b(this.chart,g);g.grid.isColumn=!0;g.grid.columnIndex=e;x(c.axes,g);x(c[this.coll],g);h.push(g)}};d.onAfterRender=function(){var c,a=this.grid,b=this.options;if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(b=b.lineWidth)){b=this.getLinePath(b);var h=b[0],e=b[1],g=((this.tickSize("tick")||[1])[0]-1)*(this.side===d.Side.top||this.side===d.Side.left?-1:1);"M"===h[0]&&"L"===e[0]&&(this.horiz?(h[2]+=g,e[2]+=g):(h[1]+=g,e[1]+=g));!this.horiz&&this.chart.marginRight&&(h=[h,["L",this.left,h[2]]],g=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],e=
[["M",e[1],this.toPixels(this.max+this.tickmarkOffset)],g],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(h)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:h}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(e)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:e}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:b}):this.grid.axisLineExtra=this.grid.renderBorder(b);this.axisLine[this.showAxis?"show":
"hide"](!0)}(a&&a.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(c=this.linkedParent)||void 0===c?0:c.scrollbar))&&(c=this.max,a=this.tickmarkOffset,b=this.tickPositions[this.tickPositions.length-1],e=this.tickPositions[0],this.min-e>a?this.ticks[e].label.hide():this.ticks[e].label.show(),b-c>a?this.ticks[b].label.hide():this.ticks[b].label.show(),b-c<a&&0<b-c&&this.ticks[b].isLast?this.ticks[b].mark.hide():this.ticks[b-1].mark.show())}};
d.onAfterSetAxisTranslation=function(){var a,b=this.tickPositions&&this.tickPositions.info,d=this.options,e=d.grid||{},h=this.userOptions.labels||{};this.horiz?(!0===e.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&d.dateTimeLabelFormats&&d.labels&&!u(h.align)&&(!1===d.dateTimeLabelFormats[b.unitName].range||1<b.count)&&(d.labels.align="left",u(h.x)||(d.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};
d.onAfterSetOptions=function(a){var c=this.options;a=a.userOptions;var b=c&&q.isObject(c.grid,!0)?c.grid:{};if(!0===b.enabled){var d=m(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(u(a.linkedTo)&&!u(a.tickPixelInterval)&&(d.tickPixelInterval=350),u(a.tickPixelInterval)||!u(a.linkedTo)||u(a.tickPositioner)||u(a.tickInterval)||(d.tickPositioner=function(a,c){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var f,e=d.units;for(f=0;f<e.length;f++)if(e[f][0]===b.unitName){var h=f;break}if(e[h+1]){var g=e[h+
1][0];var y=(e[h+1][1]||[1])[0]}else"year"===b.unitName&&(g="year",y=10*b.count);b=n[g];this.tickInterval=b*y;return this.getTimeTicks({unitRange:b,count:y,unitName:g},a,c,this.options.startOfWeek)}}));m(!0,this.options,d);this.horiz&&(c.minPadding=r(a.minPadding,0),c.maxPadding=r(a.maxPadding,0));C(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=b.borderWidth)}};d.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var c=a.columns;a.enabled&&c&&m(!0,this.options,c[c.length-1])};d.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};d.onAfterTickSize=function(a){var c=b.defaultLeftAxisOptions,d=this.horiz,h=this.maxLabelDimensions,g=this.options.grid;g=void 0===g?{}:g;g.enabled&&h&&(c=2*Math.abs(c.labels.x),d=d?g.cellHeight||c+h.height:c+h.width,e(a.tickSize)?a.tickSize[0]=d:a.tickSize=[d,0])};d.onDestroy=function(a){var c=this.grid;(c.columns||[]).forEach(function(c){c.destroy(a.keepEvents)});c.columns=void 0};d.onInit=function(a){a=a.userOptions||{};var c=
a.grid||{};c.enabled&&u(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor);this.grid||(this.grid=new g(this))};d.onTrimTicks=function(){var a=this.options,b=this.categories,d=this.tickPositions,h=d[0],e=d[d.length-1],g=this.linkedParent&&this.linkedParent.min||this.min,n=this.linkedParent&&this.linkedParent.max||this.max,l=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(h<g&&h+l>g&&!a.startOnTick&&(d[0]=g),e>n&&e-l<n&&!a.endOnTick&&(d[d.length-1]=n))};d.wrapUnsquish=
function(a){var c=this.options.grid;return!0===(void 0===c?{}:c).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return d}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});B(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,t,E,w){var q=w.addEvent,k=w.find,
u=w.fireEvent,x=w.isArray,p=w.isNumber,e=w.pick,C=function(){function m(b){this.hasBreaks=!1;this.axis=b}m.isInBreak=function(b,e){var l=b.repeat||Infinity,a=b.from,g=b.to-b.from;e=e>=a?(e-a)%l:l-(a-e)%l;return b.inclusive?e<=g:e<g&&0!==e};m.lin2Val=function(b){var e=this.brokenAxis;e=e&&e.breakArray;if(!e)return b;var l;for(l=0;l<e.length;l++){var a=e[l];if(a.from>=b)break;else a.to<b?b+=a.len:m.isInBreak(a,b)&&(b+=a.len)}return b};m.val2Lin=function(b){var e=this.brokenAxis;e=e&&e.breakArray;if(!e)return b;
var l=b,a;for(a=0;a<e.length;a++){var g=e[a];if(g.to<=b)l-=g.len;else if(g.from>=b)break;else if(m.isInBreak(g,b)){l-=b-g.from;break}}return l};m.prototype.findBreakAt=function(b,e){return k(e,function(e){return e.from<b&&b<e.to})};m.prototype.isInAnyBreak=function(b,k){var l=this.axis,a=l.options.breaks,g=a&&a.length,h;if(g){for(;g--;)if(m.isInBreak(a[g],b)){var d=!0;h||(h=e(a[g].showPoints,!l.isXAxis))}var c=d&&k?d&&!h:d}return c};m.prototype.setBreaks=function(k,n){var l=this,a=l.axis,g=x(k)&&
!!k.length;a.isDirty=l.hasBreaks!==g;l.hasBreaks=g;a.options.breaks=a.userOptions.breaks=k;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});g||a.val2lin!==m.val2Lin||(delete a.val2lin,delete a.lin2val);g&&(a.userOptions.ordinal=!1,a.lin2val=m.lin2Val,a.val2lin=m.val2Lin,a.setExtremes=function(a,d,c,e,g){if(l.hasBreaks){for(var f,h=this.options.breaks;f=l.findBreakAt(a,h);)a=f.to;for(;f=l.findBreakAt(d,h);)d=f.from;d<a&&(d=a)}b.prototype.setExtremes.call(this,a,d,c,e,g)},a.setAxisTranslation=
function(){b.prototype.setAxisTranslation.call(this);l.unitLength=null;if(l.hasBreaks){var h=a.options.breaks||[],d=[],c=[],f=0,g,k=a.userMin||a.min,n=a.userMax||a.max,p=e(a.pointRangePadding,0),q;h.forEach(function(a){g=a.repeat||Infinity;m.isInBreak(a,k)&&(k+=a.to%g-k%g);m.isInBreak(a,n)&&(n-=n%g-a.from%g)});h.forEach(function(a){r=a.from;for(g=a.repeat||Infinity;r-g>k;)r-=g;for(;r<k;)r+=g;for(q=r;q<n;q+=g)d.push({value:q,move:"in"}),d.push({value:q+(a.to-a.from),move:"out",size:a.breakSize})});
d.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var v=0;var r=k;d.forEach(function(a){v+="in"===a.move?1:-1;1===v&&"in"===a.move&&(r=a.value);0===v&&(c.push({from:r,to:a.value,len:a.value-r-(a.size||0)}),f+=a.value-r-(a.size||0))});a.breakArray=l.breakArray=c;l.unitLength=n-k-f+p;u(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:l.unitLength&&(a.transA*=(n-a.min+p)/l.unitLength);p&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=k;
a.max=n}});e(n,!0)&&a.chart.redraw()};return m}();w=function(){function b(){}b.compose=function(b,k){b.keepProps.push("brokenAxis");var l=t.prototype;l.drawBreaks=function(a,b){var g=this,d=g.points,c,f,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var n=a.brokenAxis;b.forEach(function(b){c=n&&n.breakArray||[];f=a.isXAxis?a.min:e(g.options.threshold,a.min);d.forEach(function(d){l=e(d["stack"+b.toUpperCase()],d[b]);c.forEach(function(b){if(p(f)&&p(l)){k=!1;if(f<b.from&&l>b.to||f>b.from&&l<b.from)k=
"pointBreak";else if(f<b.from&&l>b.from&&l<b.to||f>b.from&&l>b.to&&l<b.from)k="pointInBreak";k&&u(a,k,{point:d,brk:b})}})})})}};l.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var e=this.points.slice(),d=e.length-1,c=this.yAxis,f;if(a&&0<d)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),f=void 0;d--;)f&&!1!==f.visible||(f=e[d+1]),b=e[d],!1!==f.visible&&!1!==b.visible&&(f.x-b.x>a&&(f=(b.x+f.x)/2,e.splice(d+
1,0,{isNull:!0,x:f}),c.stacking&&this.options.stacking&&(f=c.stacking.stacks[this.stackKey][f]=new E(c,c.options.stackLabels,!1,f,this.stack),f.total=0)),f=b);return this.getGraphPath(e)};q(b,"init",function(){this.brokenAxis||(this.brokenAxis=new C(this))});q(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});q(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,e=this.tickPositions.info,
d=[],c;for(c=0;c<b.length;c++)a.isInAnyBreak(b[c])||d.push(b[c]);this.tickPositions=d;this.tickPositions.info=e}});q(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});q(k,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,e=this.xAxis,d=this.yAxis;if(this.isDirty)for(var c=b.length;c--;){var f=b[c],k=!(null===f.y&&!1===a)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(f.x,!0)||d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(f.y,
!0));f.visible=k?!1:!1!==f.options.visible}});q(k,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,e(this.pointArrayMap,["y"]))})};return b}();w.compose(b,t);return w});B(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,t,E,w,q,k,u){var x=k.getLevelOptions,p=u.addEvent,e=u.find,C=u.fireEvent,m=u.isArray,
r=u.isNumber,n=u.isObject,l=u.isString,a=u.merge,g=u.pick,h=u.wrap,d;(function(c){function d(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function k(a,b,c){var d=[],f=[],g={},h={},k=-1,y="boolean"===typeof b?b:!1;a=w.getTree(a,{after:function(a){a=h[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=c;a.height=b;a.collapsed&&f.push(a)},before:function(a){var b=n(a.data,!0)?a.data:
{},c=l(b.name)?b.name:"",f=g[a.parent];f=n(f,!0)?h[f.pos]:null;var m=function(a){return a.name===c},z;y&&n(f,!0)&&(z=e(f.children,m))?(m=z.pos,z.nodes.push(a)):m=k++;h[m]||(h[m]=z={depth:f?f.depth+1:0,name:c,id:b.id,nodes:[a],children:[],pos:m},-1!==m&&d.push(c),n(f,!0)&&f.children.push(z));l(a.id)&&(g[a.id]=a);z&&!0===b.collapsed&&(z.collapsed=!0);a.pos=m}});h=function(a,b){var c=function(a,d,e){var f=d+(-1===d?0:b-1),g=(f-d)/2,h=d+g;a.nodes.forEach(function(a){var b=a.data;n(b,!0)&&(b.y=d+(b.seriesIndex||
0),delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return e};return c(a["-1"],-1,{})}(h,c);return{categories:d,mapOfIdToNode:g,mapOfPosToGridNode:h,collapsedNodes:f,tree:a}}function t(c){c.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(d){var e=d.options||{},f=e.labels,g=e.uniqueNames,h=0;e=e.max;if(!d.treeGrid.mapOfPosToGridNode||d.series.some(function(a){return!a.hasRendered||
a.isDirtyData||a.isDirty})){var l=d.series.reduce(function(a,c){c.visible&&((c.options.data||[]).forEach(function(d){c.options.keys&&c.options.keys.length&&(d=c.pointClass.prototype.optionsToObject.call({series:c},d),b.seriesTypes.gantt.prototype.setGanttPointAliases(d));n(d,!0)&&(d.seriesIndex=h,a.push(d))}),!0===g&&h++);return a},[]);if(e&&l.length<e)for(var y=l.length;y<=e;y++)l.push({name:y+"\u200b"});e=k(l,g||!1,!0===g?h:1);d.categories=e.categories;d.treeGrid.mapOfPosToGridNode=e.mapOfPosToGridNode;
d.hasNames=!0;d.treeGrid.tree=e.tree;d.series.forEach(function(b){var c=(b.options.data||[]).map(function(c){m(c)&&b.options.keys&&b.options.keys.length&&l.forEach(function(a){0<=c.indexOf(a.x)&&0<=c.indexOf(a.x2)&&(c=a)});return n(c,!0)?a(c):c});b.visible&&b.setData(c,!1)});d.treeGrid.mapOptionsToLevel=x({defaults:f,from:1,levels:f&&f.levels,to:d.treeGrid.tree&&d.treeGrid.tree.height});"beforeRender"===c.type&&(d.treeGrid.collapsedNodes=e.collapsedNodes)}})}function u(a,b){var c=this.treeGrid.mapOptionsToLevel||
{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=f,e.addLabel()):d[b]=new E(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function B(a){var b=this.options;b=(b=b&&b.labels)&&r(b.indentation)?b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,
1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var d=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(d-1)}return c}function G(b,c,d){var e=this,f="treegrid"===d.type;e.treeGrid||(e.treeGrid=new J(e));f&&(p(c,"beforeRender",t),p(c,"beforeRedraw",t),p(c,"addSeries",function(a){a.options.data&&(a=k(a.options.data,d.uniqueNames||!1,1),e.treeGrid.collapsedNodes=(e.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),p(e,"foundExtremes",function(){e.treeGrid.collapsedNodes&&
e.treeGrid.collapsedNodes.forEach(function(a){var b=e.treeGrid.collapse(a);e.brokenAxis&&(e.brokenAxis.setBreaks(b,!1),e.treeGrid.collapsedNodes&&(e.treeGrid.collapsedNodes=e.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),p(e,"afterBreaks",function(){var a;"yAxis"===e.coll&&!e.staticScale&&(null===(a=e.chart.options.chart)||void 0===a?0:a.height)&&(e.isDirty=!0)}),d=a({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},
{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(e,[c,d]);f&&(e.hasNames=!0,e.options.showLastLabel=!0)}function v(a){var b=this.options;"treegrid"===b.type?(this.min=g(this.userMin,b.min,this.dataMin),this.max=g(this.userMax,b.max,this.dataMax),C(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?
this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var I=!1;c.compose=function(a){I||(h(a.prototype,"generateTick",u),h(a.prototype,"getMaxLabelDimensions",B),h(a.prototype,"init",G),h(a.prototype,"setTickInterval",v),q.compose(E),I=!0)};var J=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,c=b.chart;b.series.forEach(function(b){var d=b.options.data;if(a.id&&d){var e=c.get(a.id);b=d[b.data.indexOf(e)];e&&b&&(e.collapsed=
a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);c.push(e);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return c};a.prototype.expand=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return c.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*
a.tickInterval,c=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(e,d){d=+d;!(d>=b&&d<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(d)||e.push(d);return e},[])};a.prototype.isCollapsed=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);return c.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();c.Additions=
J})(d||(d={}));t.prototype.utils={getNode:w.getNode};d.compose(t);return d});B(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map