/*
 Highcharts JS v8.2.2 (2020-10-27)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(D){c(D);c.Highcharts=D;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function D(c,a,k,g){c.hasOwnProperty(a)||(c[a]=g.apply(null,k))}c=c?c._modules:{};D(c,"Extensions/Pane.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Pointer.js"],c["Core/Utilities.js"],c["Mixins/CenteredSeries.js"]],
function(c,a,k,g,e){function r(b,e,q){return Math.sqrt(Math.pow(b-q[0],2)+Math.pow(e-q[1],2))<=q[2]/2}var u=g.addEvent,E=g.extend,B=g.merge,A=g.pick,b=g.splat;c.prototype.collectionsWithUpdate.push("pane");g=function(){function l(b,q){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,
y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(b,q)}l.prototype.init=function(b,q){this.chart=q;this.background=[];q.pane.push(this);this.setOptions(b)};l.prototype.setOptions=function(b){this.options=B(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)};l.prototype.render=function(){var e=this.options,q=this.options.background,l=this.chart.renderer;this.group||(this.group=l.g("pane-group").attr({zIndex:e.zIndex||
0}).add());this.updateCenter();if(q)for(q=b(q),e=Math.max(q.length,this.background.length||0),l=0;l<e;l++)q[l]&&this.axis?this.renderBackground(B(this.defaultBackgroundOptions,q[l]),l):this.background[l]&&(this.background[l]=this.background[l].destroy(),this.background.splice(l,1))};l.prototype.renderBackground=function(b,l){var e="animate",q={"class":"highcharts-pane "+(b.className||"")};this.chart.styledMode||E(q,{fill:b.backgroundColor,stroke:b.borderColor,"stroke-width":b.borderWidth});this.background[l]||
(this.background[l]=this.chart.renderer.path().add(this.group),e="attr");this.background[l][e]({d:this.axis.getPlotBandPath(b.from,b.to,b)}).attr(q)};l.prototype.updateCenter=function(b){this.center=(b||this.axis||{}).center=e.getCenter.call(this)};l.prototype.update=function(b,l){B(!0,this.options,b);B(!0,this.chart.options.pane,b);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(b){b.pane===this&&(b.pane=null,b.update({},l))},this)};return l}();c.prototype.getHoverPane=
function(b){var l=this,e;b&&l.pane.forEach(function(q){var a=b.chartX-l.plotLeft,p=b.chartY-l.plotTop;r(l.inverted?p:a,l.inverted?a:p,q.center)&&(e=q)});return e};u(c,"afterIsInsidePlot",function(b){this.polar&&(b.isInsidePlot=this.pane.some(function(l){return r(b.x,b.y,l.center)}))});u(k,"beforeGetHoverData",function(b){var l=this.chart;l.polar&&(l.hoverPane=l.getHoverPane(b),b.filter=function(e){return e.visible&&!(!b.shared&&e.directTouch)&&A(e.options.enableMouseTracking,!0)&&(!l.hoverPane||e.xAxis.pane===
l.hoverPane)})});u(k,"afterGetHoverData",function(b){var e=this.chart;b.hoverPoint&&b.hoverPoint.plotX&&b.hoverPoint.plotY&&e.hoverPane&&!r(b.hoverPoint.plotX,b.hoverPoint.plotY,e.hoverPane.center)&&(b.hoverPoint=void 0)});a.Pane=g;return a.Pane});D(c,"Core/Axis/HiddenAxis.js",[],function(){return function(){function c(){}c.init=function(a){a.getOffset=function(){};a.redraw=function(){this.isDirty=!1};a.render=function(){this.isDirty=!1};a.createLabelCollector=function(){return function(){}};a.setScale=
function(){};a.setCategories=function(){};a.setTitle=function(){};a.isHidden=!0};return c}()});D(c,"Core/Axis/RadialAxis.js",[c["Core/Axis/Axis.js"],c["Core/Axis/Tick.js"],c["Core/Axis/HiddenAxis.js"],c["Core/Utilities.js"]],function(c,a,k,g){var e=g.addEvent,r=g.correctFloat,u=g.defined,E=g.extend,B=g.fireEvent,A=g.merge,b=g.pick,l=g.relativeLength,x=g.wrap;g=function(){function q(){}q.init=function(e){var q=c.prototype;e.setOptions=function(b){b=this.options=A(e.constructor.defaultOptions,this.defaultPolarOptions,
b);b.plotBands||(b.plotBands=[]);B(this,"afterSetOptions")};e.getOffset=function(){q.getOffset.call(this);this.chart.axisOffset[this.side]=0};e.getLinePath=function(p,m,f){p=this.pane.center;var d=this.chart,h=b(m,p[2]/2-this.offset);"undefined"===typeof f&&(f=this.horiz?0:this.center&&-this.center[3]/2);f&&(h+=f);this.isCircular||"undefined"!==typeof m?(m=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],h,h,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),m.xBounds=[this.left+
p[0]],m.yBounds=[this.top+p[1]-h]):(m=this.postTranslate(this.angleRad,h),m=[["M",this.center[0]+d.plotLeft,this.center[1]+d.plotTop],["L",m.x,m.y]]);return m};e.setAxisTranslation=function(){q.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)};e.beforeSetTickPositions=function(){this.autoConnect=
this.isCircular&&"undefined"===typeof b(this.userMax,this.options.max)&&r(this.endAngleRad-this.startAngleRad)===r(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};e.setAxisSize=function(){q.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var p=this.center=E([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var m=this.postTranslate(this.angleRad,
p[3]/2);p[0]=m.x-this.chart.plotLeft;p[1]=m.y-this.chart.plotTop}this.len=this.width=this.height=(p[2]-p[3])*b(this.sector,1)/2}};e.getPosition=function(p,m){p=this.translate(p);return this.postTranslate(this.isCircular?p:this.angleRad,b(this.isCircular?m:0>p?0:p,this.center[2]/2)-this.offset)};e.postTranslate=function(b,m){var f=this.chart,d=this.center;b=this.startAngleRad+b;return{x:f.plotLeft+d[0]+Math.cos(b)*m,y:f.plotTop+d[1]+Math.sin(b)*m}};e.getPlotBandPath=function(p,m,f){var d=function(d){if("string"===
typeof d){var h=parseInt(d,10);w.test(d)&&(h=h*t/100);return h}return d},h=this.center,v=this.startAngleRad,t=h[2]/2,n=Math.min(this.offset,0),w=/%$/;var y=this.isCircular;var e=b(d(f.outerRadius),t),l=d(f.innerRadius);d=b(d(f.thickness),10);if("polygon"===this.options.gridLineInterpolation)n=this.getPlotLinePath({value:p}).concat(this.getPlotLinePath({value:m,reverse:!0}));else{p=Math.max(p,this.min);m=Math.min(m,this.max);p=this.translate(p);m=this.translate(m);y||(e=p||0,l=m||0);if("circle"!==
f.shape&&y)f=v+(p||0),v+=m||0;else{f=-Math.PI/2;v=1.5*Math.PI;var q=!0}e-=n;n=this.chart.renderer.symbols.arc(this.left+h[0],this.top+h[1],e,e,{start:Math.min(f,v),end:Math.max(f,v),innerR:b(l,e-(d-n)),open:q});y&&(y=(v+f)/2,q=this.left+h[0]+h[2]/2*Math.cos(y),n.xBounds=y>-Math.PI/2&&y<Math.PI/2?[q,this.chart.plotWidth]:[0,q],n.yBounds=[this.top+h[1]+h[2]/2*Math.sin(y)],n.yBounds[0]+=y>-Math.PI&&0>y||y>Math.PI?-10:10)}return n};e.getCrosshairPosition=function(b,m,f){var d=b.value,h=this.pane.center;
if(this.isCircular){if(u(d))b.point&&(v=b.point.shapeArgs||{},v.start&&(d=this.chart.inverted?this.translate(b.point.rectPlotY,!0):b.point.x));else{var v=b.chartX||0;var t=b.chartY||0;d=this.translate(Math.atan2(t-f,v-m)-this.startAngleRad,!0)}b=this.getPosition(d);v=b.x;t=b.y}else u(d)||(v=b.chartX,t=b.chartY),u(v)&&u(t)&&(f=h[1]+this.chart.plotTop,d=this.translate(Math.min(Math.sqrt(Math.pow(v-m,2)+Math.pow(t-f,2)),h[2]/2)-h[3]/2,!0));return[d,v||0,t||0]};e.getPlotLinePath=function(b){var m=this,
f=m.pane.center,d=m.chart,h=d.inverted,v=b.value,t=b.reverse,n=m.getPosition(v),w=m.pane.options.background?m.pane.options.background[0]||m.pane.options.background:{},y=w.innerRadius||"0%",e=w.outerRadius||"100%";w=f[0]+d.plotLeft;var p=f[1]+d.plotTop,q=n.x,a=n.y,g=m.height;n=f[3]/2;var k;b.isCrosshair&&(a=this.getCrosshairPosition(b,w,p),v=a[0],q=a[1],a=a[2]);if(m.isCircular)v=Math.sqrt(Math.pow(q-w,2)+Math.pow(a-p,2)),t="string"===typeof y?l(y,1):y/v,d="string"===typeof e?l(e,1):e/v,f&&n&&(v=n/
v,t<v&&(t=v),d<v&&(d=v)),f=[["M",w+t*(q-w),p-t*(p-a)],["L",q-(1-d)*(q-w),a+(1-d)*(p-a)]];else if((v=m.translate(v))&&(0>v||v>g)&&(v=0),"circle"===m.options.gridLineInterpolation)f=m.getLinePath(0,v,n);else if(f=[],d[h?"yAxis":"xAxis"].forEach(function(d){d.pane===m.pane&&(k=d)}),k)for(w=k.tickPositions,k.autoConnect&&(w=w.concat([w[0]])),t&&(w=w.slice().reverse()),v&&(v+=n),q=0;q<w.length;q++)p=k.getPosition(w[q],v),f.push(q?["L",p.x,p.y]:["M",p.x,p.y]);return f};e.getTitlePosition=function(){var b=
this.center,m=this.chart,f=this.options.title;return{x:m.plotLeft+b[0]+(f.x||0),y:m.plotTop+b[1]-{high:.5,middle:.25,low:0}[f.align]*b[2]+(f.y||0)}};e.createLabelCollector=function(){var b=this;return function(){if(b.isRadial&&b.tickPositions&&!0!==b.options.labels.allowOverlap)return b.tickPositions.map(function(m){return b.ticks[m]&&b.ticks[m].label}).filter(function(b){return!!b})}}};q.compose=function(a,g){e(a,"init",function(b){var m=this.chart,f=m.inverted,d=m.angular,h=m.polar,v=this.isXAxis,
t=this.coll,n=d&&v,w,y=m.options;b=b.userOptions.pane||0;b=this.pane=m.pane&&m.pane[b];if("colorAxis"===t)this.isRadial=!1;else{if(d){if(n?k.init(this):q.init(this),w=!v)this.defaultPolarOptions=q.defaultRadialGaugeOptions}else h&&(q.init(this),this.defaultPolarOptions=(w=this.horiz)?q.defaultCircularOptions:A("xAxis"===t?a.defaultOptions:a.defaultYAxisOptions,q.defaultRadialOptions),f&&"yAxis"===t&&(this.defaultPolarOptions.stackLabels=a.defaultYAxisOptions.stackLabels));d||h?(this.isRadial=!0,y.chart.zoomType=
null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&m.labelCollectors.push(this.labelCollector)):this.isRadial=!1;b&&w&&(b.axis=this);this.isCircular=w}});e(a,"afterInit",function(){var e=this.chart,m=this.options,f=this.pane,d=f&&f.options;e.angular&&this.isXAxis||!f||!e.angular&&!e.polar||(this.angleRad=(m.angle||0)*Math.PI/180,this.startAngleRad=(d.startAngle-90)*Math.PI/180,this.endAngleRad=(b(d.endAngle,d.startAngle+360)-90)*Math.PI/180,this.offset=
m.offset||0)});e(a,"autoLabelAlign",function(b){this.isRadial&&(b.align=void 0,b.preventDefault())});e(a,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var b=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=b&&this.chart.labelCollectors.splice(b,1)}});e(a,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});e(g,"afterGetPosition",function(b){this.axis.getPosition&&E(b.pos,this.axis.getPosition(this.pos))});e(g,"afterGetLabelPosition",
function(e){var m=this.axis,f=this.label;if(f){var d=f.getBBox(),h=m.options.labels,v=h.y,t=20,n=h.align,w=(m.translate(this.pos)+m.startAngleRad+Math.PI/2)/Math.PI*180%360,y=Math.round(w),q="end",a=0>y?y+360:y,p=a,g=0,k=0,z=null===h.y?.3*-d.height:0;if(m.isRadial){var c=m.getPosition(this.pos,m.center[2]/2+l(b(h.distance,-25),m.center[2]/2,-m.center[2]/2));"auto"===h.rotation?f.attr({rotation:w}):null===v&&(v=m.chart.renderer.fontMetrics(f.styles&&f.styles.fontSize).b-d.height/2);null===n&&(m.isCircular?
(d.width>m.len*m.tickInterval/(m.max-m.min)&&(t=0),n=w>t&&w<180-t?"left":w>180+t&&w<360-t?"right":"center"):n="center",f.attr({align:n}));if("auto"===n&&2===m.tickPositions.length&&m.isCircular){90<a&&180>a?a=180-a:270<a&&360>=a&&(a=540-a);180<p&&360>=p&&(p=360-p);if(m.pane.options.startAngle===y||m.pane.options.startAngle===y+360||m.pane.options.startAngle===y-360)q="start";n=-90<=y&&90>=y||-360<=y&&-270>=y||270<=y&&360>=y?"start"===q?"right":"left":"start"===q?"left":"right";70<p&&110>p&&(n="center");
15>a||180<=a&&195>a?g=.3*d.height:15<=a&&35>=a?g="start"===q?0:.75*d.height:195<=a&&215>=a?g="start"===q?.75*d.height:0:35<a&&90>=a?g="start"===q?.25*-d.height:d.height:215<a&&270>=a&&(g="start"===q?d.height:.25*-d.height);15>p?k="start"===q?.15*-d.height:.15*d.height:165<p&&180>=p&&(k="start"===q?.15*d.height:.15*-d.height);f.attr({align:n});f.translate(k,g+z)}e.pos.x=c.x+h.x;e.pos.y=c.y+v}}});x(g.prototype,"getMarkPath",function(b,m,f,d,h,v,t){var n=this.axis;n.isRadial?(b=n.getPosition(this.pos,
n.center[2]/2+d),m=["M",m,f,"L",b.x,b.y]):m=b.call(this,m,f,d,h,v,t);return m})};q.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};q.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2};
q.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return q}();g.compose(c,a);return g});D(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,g){var e=g.defined,r=g.extend,u=g.isArray,E=g.isNumber,B=g.pick,A=c.seriesTypes.area.prototype,b=c.seriesTypes.column.prototype,l=k.prototype,x=a.Series.prototype;
c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(b){return[b.low,b.high]},highToXY:function(b){var e=this.chart,a=this.xAxis.postTranslate(b.rectPlotX,this.yAxis.len-b.plotHigh);
b.plotHighX=a.x-e.plotLeft;b.plotHigh=a.y-e.plotTop;b.plotLowX=b.plotX},translate:function(){var b=this,e=b.yAxis,a=!!b.modifyValue;A.translate.apply(b);b.points.forEach(function(l){var m=l.high,f=l.plotY;l.isNull?l.plotY=null:(l.plotLow=f,l.plotHigh=e.translate(a?b.modifyValue(m,l):m,0,1,0,1),a&&(l.yBottom=l.plotHigh))});this.chart.polar&&this.points.forEach(function(e){b.highToXY(e);e.tooltipPos=[(e.plotHighX+e.plotLowX)/2,(e.plotHigh+e.plotLow)/2]})},getGraphPath:function(b){var e=[],a=[],l,m=
A.getGraphPath;var f=this.options;var d=this.chart.polar,h=d&&!1!==f.connectEnds,v=f.connectNulls,t=f.step;b=b||this.points;for(l=b.length;l--;){var n=b[l];var w=d?{plotX:n.rectPlotX,plotY:n.yBottom,doCurve:!1}:{plotX:n.plotX,plotY:n.plotY,doCurve:!1};n.isNull||h||v||b[l+1]&&!b[l+1].isNull||a.push(w);var y={polarPlotY:n.polarPlotY,rectPlotX:n.rectPlotX,yBottom:n.yBottom,plotX:B(n.plotHighX,n.plotX),plotY:n.plotHigh,isNull:n.isNull};a.push(y);e.push(y);n.isNull||h||v||b[l-1]&&!b[l-1].isNull||a.push(w)}b=
m.call(this,b);t&&(!0===t&&(t="left"),f.step={left:"right",center:"center",right:"left"}[t]);e=m.call(this,e);a=m.call(this,a);f.step=t;f=[].concat(b,e);!this.chart.polar&&a[0]&&"M"===a[0][0]&&(a[0]=["L",a[0][1],a[0][2]]);this.graphPath=f;this.areaPath=b.concat(a);f.isArea=!0;f.xMap=b.xMap;this.areaPath.xMap=b.xMap;return f},drawDataLabels:function(){var b=this.points,e=b.length,a,l=[],m=this.options.dataLabels,f,d=this.chart.inverted;if(u(m)){var h=m[0]||{enabled:!1};var v=m[1]||{enabled:!1}}else h=
r({},m),h.x=m.xHigh,h.y=m.yHigh,v=r({},m),v.x=m.xLow,v.y=m.yLow;if(h.enabled||this._hasPointLabels){for(a=e;a--;)if(f=b[a]){var t=h.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow;f.y=f.high;f._plotY=f.plotY;f.plotY=f.plotHigh;l[a]=f.dataLabel;f.dataLabel=f.dataLabelUpper;f.below=t;d?h.align||(h.align=t?"right":"left"):h.verticalAlign||(h.verticalAlign=t?"top":"bottom")}this.options.dataLabels=h;x.drawDataLabels&&x.drawDataLabels.apply(this,arguments);for(a=e;a--;)if(f=b[a])f.dataLabelUpper=f.dataLabel,
f.dataLabel=l[a],delete f.dataLabels,f.y=f.low,f.plotY=f._plotY}if(v.enabled||this._hasPointLabels){for(a=e;a--;)if(f=b[a])t=v.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow,f.below=!t,d?v.align||(v.align=t?"left":"right"):v.verticalAlign||(v.verticalAlign=t?"bottom":"top");this.options.dataLabels=v;x.drawDataLabels&&x.drawDataLabels.apply(this,arguments)}if(h.enabled)for(a=e;a--;)if(f=b[a])f.dataLabels=[f.dataLabelUpper,f.dataLabel].filter(function(d){return!!d});this.options.dataLabels=m},alignDataLabel:function(){b.alignDataLabel.apply(this,
arguments)},drawPoints:function(){var b=this.points.length,a;x.drawPoints.apply(this,arguments);for(a=0;a<b;){var l=this.points[a];l.origProps={plotY:l.plotY,plotX:l.plotX,isInside:l.isInside,negative:l.negative,zone:l.zone,y:l.y};l.lowerGraphic=l.graphic;l.graphic=l.upperGraphic;l.plotY=l.plotHigh;e(l.plotHighX)&&(l.plotX=l.plotHighX);l.y=l.high;l.negative=l.high<(this.options.threshold||0);l.zone=this.zones.length&&l.getZone();this.chart.polar||(l.isInside=l.isTopInside="undefined"!==typeof l.plotY&&
0<=l.plotY&&l.plotY<=this.yAxis.len&&0<=l.plotX&&l.plotX<=this.xAxis.len);a++}x.drawPoints.apply(this,arguments);for(a=0;a<b;)l=this.points[a],l.upperGraphic=l.graphic,l.graphic=l.lowerGraphic,r(l,l.origProps),delete l.origProps,a++},setStackedPoints:a.noop},{setState:function(){var b=this.state,a=this.series,g=a.chart.polar;e(this.plotHigh)||(this.plotHigh=a.yAxis.toPixels(this.high,!0));e(this.plotLow)||(this.plotLow=this.plotY=a.yAxis.toPixels(this.low,!0));a.stateMarkerGraphic&&(a.lowerStateMarkerGraphic=
a.stateMarkerGraphic,a.stateMarkerGraphic=a.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;g&&(this.plotX=this.plotHighX);l.setState.apply(this,arguments);this.state=b;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;g&&(this.plotX=this.plotLowX);a.stateMarkerGraphic&&(a.upperStateMarkerGraphic=a.stateMarkerGraphic,a.stateMarkerGraphic=a.lowerStateMarkerGraphic,a.lowerStateMarkerGraphic=void 0);l.setState.apply(this,arguments)},haloPath:function(){var b=this.series.chart.polar,
a=[];this.plotY=this.plotLow;b&&(this.plotX=this.plotLowX);this.isInside&&(a=l.haloPath.apply(this,arguments));this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);this.isTopInside&&(a=a.concat(l.haloPath.apply(this,arguments)));return a},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(b){this[b]&&(this[b]=this[b].destroy())},this);this.graphic=null;return l.destroyElements.apply(this,arguments)},isValid:function(){return E(this.low)&&E(this.high)}});""});D(c,"Series/AreaSplineRangeSeries.js",
[c["Core/Series/Series.js"]],function(c){c.seriesType("areasplinerange","arearange",null,{getPointSpline:c.seriesTypes.spline.prototype.getPointSpline});""});D(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,a,k,g){a=a.noop;k=k.defaultOptions;var e=g.clamp,r=g.merge,u=g.pick,E=c.seriesTypes.arearange.prototype,B=c.seriesTypes.column.prototype;c.seriesType("columnrange","arearange",r(k.plotOptions.column,k.plotOptions.arearange,
{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){r(!0,arguments[0],{stacking:void 0});return E.setOptions.apply(this,arguments)},translate:function(){var a=this,b=a.yAxis,l=a.xAxis,g=l.startAngleRad,k,c=a.chart,r=a.xAxis.isRadial,p=Math.max(c.chartWidth,c.chartHeight)+999,m;B.translate.apply(a);a.points.forEach(function(f){var d=f.shapeArgs,h=a.options.minPointLength;f.plotHigh=m=e(b.translate(f.high,0,1,0,1),-p,p);f.plotLow=e(f.plotY,-p,p);var v=m;var t=u(f.rectPlotY,
f.plotY)-m;Math.abs(t)<h?(h-=t,t+=h,v-=h/2):0>t&&(t*=-1,v-=t);r?(k=f.barX+g,f.shapeType="arc",f.shapeArgs=a.polarArc(v+t,v,k,k+f.pointWidth)):(d.height=t,d.y=v,f.tooltipPos=c.inverted?[b.len+b.pos-c.plotLeft-v-t/2,l.len+l.pos-c.plotTop-d.x-d.width/2,t]:[l.left-c.plotLeft+d.x+d.width/2,b.pos-c.plotTop+v+t/2,t])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:a,getSymbol:a,crispCol:function(){return B.crispCol.apply(this,arguments)},drawPoints:function(){return B.drawPoints.apply(this,
arguments)},drawTracker:function(){return B.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return B.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return B.pointAttribs.apply(this,arguments)},animate:function(){return B.animate.apply(this,arguments)},polarArc:function(){return B.polarArc.apply(this,arguments)},translate3dPoints:function(){return B.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return B.translate3dShapes.apply(this,arguments)}},
{setState:B.pointClass.prototype.setState});""});D(c,"Series/ColumnPyramidSeries.js",[c["Core/Series/Series.js"],c["Series/ColumnSeries.js"],c["Core/Utilities.js"]],function(c,a,k){var g=a.prototype,e=k.clamp,r=k.pick;c.seriesType("columnpyramid","column",{},{translate:function(){var a=this,k=a.chart,c=a.options,A=a.dense=2>a.closestPointRange*a.xAxis.transA;A=a.borderWidth=r(c.borderWidth,A?0:1);var b=a.yAxis,l=c.threshold,x=a.translatedThreshold=b.getThreshold(l),q=r(c.minPointLength,5),C=a.getColumnMetrics(),
z=C.width,p=a.barW=Math.max(z,1+2*A),m=a.pointXOffset=C.offset;k.inverted&&(x-=.5);c.pointPadding&&(p=Math.ceil(p));g.translate.apply(a);a.points.forEach(function(f){var d=r(f.yBottom,x),h=999+Math.abs(d),v=e(f.plotY,-h,b.len+h);h=f.plotX+m;var t=p/2,n=Math.min(v,d);d=Math.max(v,d)-n;var w;f.barX=h;f.pointWidth=z;f.tooltipPos=k.inverted?[b.len+b.pos-k.plotLeft-v,a.xAxis.len-h-t,d]:[h+t,v+b.pos-k.plotTop,d];v=l+(f.total||f.y);"percent"===c.stacking&&(v=l+(0>f.y)?-100:100);v=b.toPixels(v,!0);var y=
(w=k.plotHeight-v-(k.plotHeight-x))?t*(n-v)/w:0;var g=w?t*(n+d-v)/w:0;w=h-y+t;y=h+y+t;var G=h+g+t;g=h-g+t;var u=n-q;var F=n+d;0>f.y&&(u=n,F=n+d+q);k.inverted&&(G=k.plotWidth-n,w=v-(k.plotWidth-x),y=t*(v-G)/w,g=t*(v-(G-d))/w,w=h+t+y,y=w-2*y,G=h-g+t,g=h+g+t,u=n,F=n+d-q,0>f.y&&(F=n+d+q));f.shapeType="path";f.shapeArgs={x:w,y:u,width:y-w,height:d,d:[["M",w,u],["L",y,u],["L",G,F],["L",g,F],["Z"]]}})}});""});D(c,"Series/GaugeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],
function(c,a,k){var g=k.clamp,e=k.isNumber,r=k.merge,u=k.pick,E=k.pInt,B=a.Series;k=a.TrackerMixin;c.seriesType("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:a.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,b=this.options,l=a.center;
this.generatePoints();this.points.forEach(function(k){var c=r(b.dial,k.dial),x=E(u(c.radius,"80%"))*l[2]/200,A=E(u(c.baseLength,"70%"))*x/100,p=E(u(c.rearLength,"10%"))*x/100,m=c.baseWidth||3,f=c.topWidth||1,d=b.overshoot,h=a.startAngleRad+a.translate(k.y,null,null,null,!0);if(e(d)||!1===b.wrap)d=e(d)?d/180*Math.PI:0,h=g(h,a.startAngleRad-d,a.endAngleRad+d);h=180*h/Math.PI;k.shapeType="path";k.shapeArgs={d:c.path||[["M",-p,-m/2],["L",A,-m/2],["L",x,-f/2],["L",x,f/2],["L",A,m/2],["L",-p,m/2],["Z"]],
translateX:l[0],translateY:l[1],rotation:h};k.plotX=l[0];k.plotY=l[1]})},drawPoints:function(){var a=this,b=a.chart,l=a.yAxis.center,e=a.pivot,g=a.options,k=g.pivot,c=b.renderer;a.points.forEach(function(e){var m=e.graphic,f=e.shapeArgs,d=f.d,h=r(g.dial,e.dial);m?(m.animate(f),f.d=d):e.graphic=c[e.shapeType](f).attr({rotation:f.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!b.styledMode)e.graphic[m?"animate":"attr"]({stroke:h.borderColor||"none","stroke-width":h.borderWidth||0,fill:h.backgroundColor||
"#000000"})});e?e.animate({translateX:l[0],translateY:l[1]}):(a.pivot=c.circle(0,0,u(k.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(l[0],l[1]).add(a.group),b.styledMode||a.pivot.attr({"stroke-width":k.borderWidth||0,stroke:k.borderColor||"#cccccc",fill:k.backgroundColor||"#000000"}))},animate:function(a){var b=this;a||b.points.forEach(function(a){var e=a.graphic;e&&(e.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),e.animate({rotation:a.shapeArgs.rotation},b.options.animation))})},
render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);B.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,b){B.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();u(b,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:k&&k.drawTrackerPoint},{setState:function(a){this.state=a}});""});D(c,"Series/BoxPlotSeries.js",[c["Core/Series/Series.js"],
c["Series/ColumnSeries.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k,g){var e=a.prototype;a=k.noop;var r=g.pick;c.seriesType("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low",
"q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:a,translate:function(){var a=this.yAxis,g=this.pointArrayMap;e.translate.apply(this);this.points.forEach(function(e){g.forEach(function(g){null!==e[g]&&(e[g+"Plot"]=a.translate(e[g],0,1,0,1))});e.plotHigh=e.highPlot})},drawPoints:function(){var a=this,e=a.options,g=a.chart,k=g.renderer,b,l,c,q,C,z,p=0,m,f,d,h,v=!1!==a.doQuartiles,t,n=a.options.whiskerLength;
a.points.forEach(function(w){var y=w.graphic,I=y?"animate":"attr",G=w.shapeArgs,x={},F={},H={},J={},u=w.color||a.color;"undefined"!==typeof w.plotY&&(m=Math.round(G.width),f=Math.floor(G.x),d=f+m,h=Math.round(m/2),b=Math.floor(v?w.q1Plot:w.lowPlot),l=Math.floor(v?w.q3Plot:w.lowPlot),c=Math.floor(w.highPlot),q=Math.floor(w.lowPlot),y||(w.graphic=y=k.g("point").add(a.group),w.stem=k.path().addClass("highcharts-boxplot-stem").add(y),n&&(w.whiskers=k.path().addClass("highcharts-boxplot-whisker").add(y)),
v&&(w.box=k.path(void 0).addClass("highcharts-boxplot-box").add(y)),w.medianShape=k.path(void 0).addClass("highcharts-boxplot-median").add(y)),g.styledMode||(F.stroke=w.stemColor||e.stemColor||u,F["stroke-width"]=r(w.stemWidth,e.stemWidth,e.lineWidth),F.dashstyle=w.stemDashStyle||e.stemDashStyle||e.dashStyle,w.stem.attr(F),n&&(H.stroke=w.whiskerColor||e.whiskerColor||u,H["stroke-width"]=r(w.whiskerWidth,e.whiskerWidth,e.lineWidth),H.dashstyle=w.whiskerDashStyle||e.whiskerDashStyle||e.dashStyle,w.whiskers.attr(H)),
v&&(x.fill=w.fillColor||e.fillColor||u,x.stroke=e.lineColor||u,x["stroke-width"]=e.lineWidth||0,x.dashstyle=w.boxDashStyle||e.boxDashStyle||e.dashStyle,w.box.attr(x)),J.stroke=w.medianColor||e.medianColor||u,J["stroke-width"]=r(w.medianWidth,e.medianWidth,e.lineWidth),J.dashstyle=w.medianDashStyle||e.medianDashStyle||e.dashStyle,w.medianShape.attr(J)),z=w.stem.strokeWidth()%2/2,p=f+h+z,y=[["M",p,l],["L",p,c],["M",p,b],["L",p,q]],w.stem[I]({d:y}),v&&(z=w.box.strokeWidth()%2/2,b=Math.floor(b)+z,l=Math.floor(l)+
z,f+=z,d+=z,y=[["M",f,l],["L",f,b],["L",d,b],["L",d,l],["L",f,l],["Z"]],w.box[I]({d:y})),n&&(z=w.whiskers.strokeWidth()%2/2,c+=z,q+=z,t=/%$/.test(n)?h*parseFloat(n)/100:n/2,y=[["M",p-t,c],["L",p+t,c],["M",p-t,q],["L",p+t,q]],w.whiskers[I]({d:y})),C=Math.round(w.medianPlot),z=w.medianShape.strokeWidth()%2/2,C+=z,y=[["M",f,C],["L",d,C]],w.medianShape[I]({d:y}))})},setStackedPoints:a});""});D(c,"Series/ErrorBarSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"]],function(c,a){a=a.noop;var k=
c.seriesTypes;c.seriesType("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:k.arearange?function(){var a=this.pointValKey;k.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(e){e.y=
e[a]})}:a,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||k.column.prototype.getColumnMetrics.call(this)}});""});D(c,"Series/WaterfallSeries.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Extensions/Stacking.js"],c["Core/Utilities.js"]],function(c,a,k,g,e,r,u){var E=a.seriesTypes,B=u.addEvent,A=u.arrayMax,b=u.arrayMin,l=u.correctFloat,x=u.isNumber,q=u.objectEach,C=u.pick,z=g.Series,
p;(function(b){function f(){var d=this.waterfall.stacks;d&&(d.changed=!1,delete d.alreadyChanged)}function d(){var d=this.options.stackLabels;d&&d.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function h(){for(var d=this.axes,h=this.series,b=h.length;b--;)h[b].options.stacking&&(d.forEach(function(d){d.isXAxis||(d.waterfall.stacks.changed=!0)}),b=0)}function a(){this.waterfall||(this.waterfall=new t(this))}var t=function(){function d(d){this.axis=d;this.stacks={changed:!1}}d.prototype.renderStackTotals=
function(){var d=this.axis,h=d.waterfall.stacks,b=d.stacking&&d.stacking.stackTotalGroup,f=new r(d,d.options.stackLabels,!1,0,void 0);this.dummyStackItem=f;q(h,function(d){q(d,function(d){f.total=d.stackTotal;d.label&&(f.label=d.label);r.prototype.render.call(f,b);d.label=f.label;delete f.label})});f.total=null};return d}();b.Composition=t;b.compose=function(b,v){B(b,"init",a);B(b,"afterBuildStacks",f);B(b,"afterRender",d);B(v,"beforeRedraw",h)}})(p||(p={}));a.seriesType("waterfall","column",{dataLabels:{inside:!0},
lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var b;E.column.prototype.generatePoints.apply(this);var f=0;for(b=this.points.length;f<b;f++){var d=this.points[f];var h=this.processedYData[f];if(d.isIntermediateSum||d.isSum)d.y=l(h)}},translate:function(){var b=this.options,f=this.yAxis,d,h=C(b.minPointLength,5),a=h/2,t=b.threshold,n=b.stacking,e=f.waterfall.stacks[this.stackKey];E.column.prototype.translate.apply(this);
var l=d=t;var g=this.points;var k=0;for(b=g.length;k<b;k++){var c=g[k];var p=this.processedYData[k];var q=c.shapeArgs;var r=[0,p];var x=c.y;if(n){if(e){r=e[k];if("overlap"===n){var u=r.stackState[r.stateIndex--];u=0<=x?u:u-x;Object.hasOwnProperty.call(r,"absolutePos")&&delete r.absolutePos;Object.hasOwnProperty.call(r,"absoluteNeg")&&delete r.absoluteNeg}else 0<=x?(u=r.threshold+r.posTotal,r.posTotal-=x):(u=r.threshold+r.negTotal,r.negTotal-=x,u-=x),!r.posTotal&&Object.hasOwnProperty.call(r,"absolutePos")&&
(r.posTotal=r.absolutePos,delete r.absolutePos),!r.negTotal&&Object.hasOwnProperty.call(r,"absoluteNeg")&&(r.negTotal=r.absoluteNeg,delete r.absoluteNeg);c.isSum||(r.connectorThreshold=r.threshold+r.stackTotal);f.reversed?(p=0<=x?u-x:u+x,x=u):(p=u,x=u-x);c.below=p<=C(t,0);q.y=f.translate(p,0,1,0,1);q.height=Math.abs(q.y-f.translate(x,0,1,0,1))}if(x=f.waterfall.dummyStackItem)x.x=k,x.label=e[k].label,x.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[k],this.stackedYPos[k])}else u=Math.max(l,
l+x)+r[0],q.y=f.translate(u,0,1,0,1),c.isSum?(q.y=f.translate(r[1],0,1,0,1),q.height=Math.min(f.translate(r[0],0,1,0,1),f.len)-q.y):c.isIntermediateSum?(0<=x?(p=r[1]+d,x=d):(p=d,x=r[1]+d),f.reversed&&(p^=x,x^=p,p^=x),q.y=f.translate(p,0,1,0,1),q.height=Math.abs(q.y-Math.min(f.translate(x,0,1,0,1),f.len)),d+=r[1]):(q.height=0<p?f.translate(l,0,1,0,1)-q.y:f.translate(l,0,1,0,1)-f.translate(l-p,0,1,0,1),l+=p,c.below=l<C(t,0)),0>q.height&&(q.y+=q.height,q.height*=-1);c.plotY=q.y=Math.round(q.y)-this.borderWidth%
2/2;q.height=Math.max(Math.round(q.height),.001);c.yBottom=q.y+q.height;q.height<=h&&!c.isNull?(q.height=h,q.y-=a,c.plotY=q.y,c.minPointLengthOffset=0>c.y?-a:a):(c.isNull&&(q.width=0),c.minPointLengthOffset=0);q=c.plotY+(c.negative?q.height:0);this.chart.inverted?c.tooltipPos[0]=f.len-q:c.tooltipPos[1]=q}},processData:function(b){var f=this.options,d=this.yData,h=f.data,a=d.length,t=f.threshold||0,n,e,m,k,g;for(g=e=n=m=k=0;g<a;g++){var c=d[g];var q=h&&h[g]?h[g]:{};"sum"===c||q.isSum?d[g]=l(e):"intermediateSum"===
c||q.isIntermediateSum?(d[g]=l(n),n=0):(e+=c,n+=c);m=Math.min(e,m);k=Math.max(e,k)}z.prototype.processData.call(this,b);f.stacking||(this.dataMin=m+t,this.dataMax=k)},toYData:function(b){return b.isSum?"sum":b.isIntermediateSum?"intermediateSum":b.y},updateParallelArrays:function(b,f){z.prototype.updateParallelArrays.call(this,b,f);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=null},pointAttribs:function(b,f){var d=this.options.upColor;d&&!b.options.color&&(b.color=0<b.y?
d:null);b=E.column.prototype.pointAttribs.call(this,b,f);delete b.dashstyle;return b},getGraphPath:function(){return[["M",0,0]]},getCrispPath:function(){var b=this.data,f=this.yAxis,d=b.length,h=Math.round(this.graph.strokeWidth())%2/2,a=Math.round(this.borderWidth)%2/2,t=this.xAxis.reversed,n=this.yAxis.reversed,e=this.options.stacking,l=[],g;for(g=1;g<d;g++){var k=b[g].shapeArgs;var c=b[g-1];var q=b[g-1].shapeArgs;var p=f.waterfall.stacks[this.stackKey];var r=0<c.y?-q.height:0;p&&q&&k&&(p=p[g-1],
e?(p=p.connectorThreshold,r=Math.round(f.translate(p,0,1,0,1)+(n?r:0))-h):r=q.y+c.minPointLengthOffset+a-h,l.push(["M",(q.x||0)+(t?0:q.width||0),r],["L",(k.x||0)+(t?k.width||0:0),r]));!e&&l.length&&q&&(0>c.y&&!n||0<c.y&&n)&&(l[l.length-2][2]+=q.height,l[l.length-1][2]+=q.height)}return l},drawGraph:function(){z.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function b(d,h,b,a){if(C)for(b;b<C;b++)u.stackState[b]+=a;else u.stackState[0]=d,C=u.stackState.length;
u.stackState.push(u.stackState[C-1]+h)}var f=this.options,d=this.yAxis.waterfall.stacks,h=f.threshold,a=h||0,t=a,n=this.stackKey,e=this.xData,l=e.length,g,k,c;this.yAxis.stacking.usePercentage=!1;var q=k=c=a;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var p=d.changed;(g=d.alreadyChanged)&&0>g.indexOf(n)&&(p=!0);d[n]||(d[n]={});g=d[n];for(var r=0;r<l;r++){var x=e[r];if(!g[x]||p)g[x]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:p&&g[x]?g[x].label:
void 0};var u=g[x];var A=this.yData[r];0<=A?u.posTotal+=A:u.negTotal+=A;var z=f.data[r];x=u.absolutePos=u.posTotal;var B=u.absoluteNeg=u.negTotal;u.stackTotal=x+B;var C=u.stackState.length;z&&z.isIntermediateSum?(b(c,k,0,c),c=k,k=h,a^=t,t^=a,a^=t):z&&z.isSum?(b(h,q,C),a=h):(b(a,A,0,q),z&&(q+=A,k+=A));u.stateIndex++;u.threshold=a;a+=u.stackTotal}d.changed=!1;d.alreadyChanged||(d.alreadyChanged=[]);d.alreadyChanged.push(n)}},getExtremes:function(){var a=this.options.stacking;if(a){var f=this.yAxis;
f=f.waterfall.stacks;var d=this.stackedYNeg=[];var h=this.stackedYPos=[];"overlap"===a?q(f[this.stackKey],function(a){d.push(b(a.stackState));h.push(A(a.stackState))}):q(f[this.stackKey],function(b){d.push(b.negTotal+b.threshold);h.push(b.posTotal+b.threshold)});return{dataMin:b(d),dataMax:A(h)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}},{getClassName:function(){var b=e.prototype.getClassName.call(this);this.isSum?b+=" highcharts-sum":this.isIntermediateSum&&(b+=" highcharts-intermediate-sum");
return b},isValid:function(){return x(this.y)||this.isSum||!!this.isIntermediateSum}});"";p.compose(c,k);return p});D(c,"Series/PolygonSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Mixins/LegendSymbol.js"]],function(c,a,k){var g=c.seriesTypes,e=a.Series;c.seriesType("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=e.prototype.getGraphPath.call(this),
g=a.length+1;g--;)(g===a.length||"M"===a[g][0])&&0<g&&a.splice(g,0,["Z"]);return this.areaPath=a},drawGraph:function(){this.options.fillColor=this.color;g.area.prototype.drawGraph.call(this)},drawLegendSymbol:k.drawRectangle,drawTracker:e.prototype.drawTracker,setStackedPoints:a.noop});""});D(c,"Series/Bubble/BubbleLegend.js",[c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Core/Legend.js"],c["Core/Utilities.js"]],function(c,a,k,g,e){var r=a.parse;a=e.addEvent;var u=e.arrayMax,
E=e.arrayMin,B=e.isNumber,A=e.merge,b=e.objectEach,l=e.pick,x=e.setOptions,q=e.stableSort,C=e.wrap;"";var z=k.Series,p=k.noop;x({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,
color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});x=function(){function a(b,d){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=p;this.init(b,d)}a.prototype.init=function(b,d){this.options=b;this.visible=!0;this.chart=d.chart;this.legend=d};a.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,
0,this)};a.prototype.drawLegendSymbol=function(b){var d=this.chart,h=this.options,a=l(b.options.itemDistance,20),f=h.ranges;var n=h.connectorDistance;this.fontMetrics=d.renderer.fontMetrics(h.labels.style.fontSize.toString()+"px");f&&f.length&&B(f[0].value)?(q(f,function(d,h){return h.value-d.value}),this.ranges=f,this.setOptions(),this.render(),d=this.getMaxLabelSize(),f=this.ranges[0].radius,b=2*f,n=n-f+d.width,n=0<n?n:0,this.maxLabel=d,this.movementX="left"===h.labels.align?n:0,this.legendItemWidth=
b+n+a,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var b=this.ranges,d=this.options,h=this.chart.series[d.seriesIndex],a=this.legend.baseline,e={"z-index":d.zIndex,"stroke-width":d.borderWidth},n={"z-index":d.zIndex,"stroke-width":d.connectorWidth},w=this.getLabelStyles(),g=h.options.marker.fillOpacity,c=this.chart.styledMode;b.forEach(function(f,t){c||(e.stroke=l(f.borderColor,d.borderColor,h.color),e.fill=l(f.color,d.color,
1!==g?r(h.color).setOpacity(g).get("rgba"):h.color),n.stroke=l(f.connectorColor,d.connectorColor,h.color));b[t].radius=this.getRangeRadius(f.value);b[t]=A(b[t],{center:b[0].radius-b[t].radius+a});c||A(!0,b[t],{bubbleStyle:A(!1,e),connectorStyle:A(!1,n),labelStyle:w})},this)};a.prototype.getLabelStyles=function(){var a=this.options,d={},h="left"===a.labels.align,e=this.legend.options.rtl;b(a.labels.style,function(h,b){"color"!==b&&"fontSize"!==b&&"z-index"!==b&&(d[b]=h)});return A(!1,d,{"font-size":a.labels.style.fontSize,
fill:l(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:e||h?"right":"left"})};a.prototype.getRangeRadius=function(b){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-1].value,d.ranges[0].value,d.minSize,d.maxSize,b)};a.prototype.render=function(){var b=this.chart.renderer,d=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");
this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(h){h.value>=d&&this.renderRange(h)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(b){var d=this.options,h=d.labels,a=this.chart.renderer,f=this.symbols,e=f.labels,w=b.center,l=Math.abs(b.radius),g=d.connectorDistance||0,c=h.align,k=h.style.fontSize;g=this.legend.options.rtl||"left"===c?-g:g;h=d.connectorWidth;
var m=this.ranges[0].radius||0,q=w-l-d.borderWidth/2+h/2;k=k/2-(this.fontMetrics.h-k)/2;var p=a.styledMode;"center"===c&&(g=0,d.connectorDistance=0,b.labelStyle.align="center");c=q+d.labels.y;var r=m+g+d.labels.x;f.bubbleItems.push(a.circle(m,w+((q%1?1:.5)-(h%2?0:.5)),l).attr(p?{}:b.bubbleStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(d.className||"")).add(this.legendSymbol));f.connectors.push(a.path(a.crispLine([["M",m,q],["L",m+g,q]],
d.connectorWidth)).attr(p?{}:b.connectorStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(d.connectorClassName||"")).add(this.legendSymbol));b=a.text(this.formatLabel(b),r,c+k).attr(p?{}:b.labelStyle).addClass("highcharts-bubble-legend-labels "+(d.labels.className||"")).add(this.legendSymbol);e.push(b);b.placed=!0;b.alignAttr={x:r,y:c+k}};a.prototype.getMaxLabelSize=function(){var b,d;this.symbols.labels.forEach(function(h){d=h.getBBox(!0);
b=b?d.width>b.width?d:b:d});return b||{}};a.prototype.formatLabel=function(b){var d=this.options,h=d.labels.formatter;d=d.labels.format;var a=this.chart.numberFormatter;return d?e.format(d,b):h?h.call(b):a(b.value,1)};a.prototype.hideOverlappingLabels=function(){var b=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(b.hideOverlappingLabels(d.labels),d.labels.forEach(function(b,a){b.newOpacity?b.newOpacity!==b.oldOpacity&&d.connectors[a].show():d.connectors[a].hide()}))};a.prototype.getRanges=
function(){var b=this.legend.bubbleLegend,d=b.options.ranges,h,a=Number.MAX_VALUE,e=-Number.MAX_VALUE;b.chart.series.forEach(function(d){d.isBubble&&!d.ignoreSeries&&(h=d.zData.filter(B),h.length&&(a=l(d.options.zMin,Math.min(a,Math.max(E(h),!1===d.options.displayNegative?d.options.zThreshold:-Number.MAX_VALUE))),e=l(d.options.zMax,Math.max(e,u(h)))))});var n=a===e?[{value:e}]:[{value:a},{value:(a+e)/2},{value:e,autoRanges:!0}];d.length&&d[0].radius&&n.reverse();n.forEach(function(b,h){d&&d[h]&&(n[h]=
A(!1,d[h],b))});return n};a.prototype.predictBubbleSizes=function(){var b=this.chart,d=this.fontMetrics,h=b.legend.options,a="horizontal"===h.layout,e=a?b.legend.lastLineHeight:0,n=b.plotSizeX,l=b.plotSizeY,g=b.series[this.options.seriesIndex];b=Math.ceil(g.minPxSize);var c=Math.ceil(g.maxPxSize);g=g.options.maxSize;var k=Math.min(l,n);if(h.floating||!/%$/.test(g))d=c;else if(g=parseFloat(g),d=(k+e-d.h/2)*g/100/(g/100+1),a&&l-d>=n||!a&&n-d>=l)d=c;return[b,Math.ceil(d)]};a.prototype.updateRanges=function(b,
d){var h=this.legend.options.bubbleLegend;h.minSize=b;h.maxSize=d;h.ranges=this.getRanges()};a.prototype.correctSizes=function(){var b=this.legend,d=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(d.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,d.maxPxSize),b.render())};return a}();a(g,"afterGetAllItems",function(b){var a=this.bubbleLegend,d=this.options,h=d.bubbleLegend,e=this.chart.getVisibleBubbleSeriesIndex();a&&a.ranges&&a.ranges.length&&(h.ranges.length&&
(h.autoRanges=!!h.ranges[0].autoRanges),this.destroyItem(a));0<=e&&d.enabled&&h.enabled&&(h.seriesIndex=e,this.bubbleLegend=new k.BubbleLegend(h,this),this.bubbleLegend.addToLegend(b.allItems))});c.prototype.getVisibleBubbleSeriesIndex=function(){for(var b=this.series,a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1};g.prototype.getLinesHeights=function(){var b=this.allItems,a=[],d=b.length,h,e=0;for(h=0;h<d;h++)if(b[h].legendItemHeight&&(b[h].itemHeight=
b[h].legendItemHeight),b[h]===b[d-1]||b[h+1]&&b[h]._legendItemPos[1]!==b[h+1]._legendItemPos[1]){a.push({height:0});var t=a[a.length-1];for(e;e<=h;e++)b[e].itemHeight>t.height&&(t.height=b[e].itemHeight);t.step=h}return a};g.prototype.retranslateItems=function(b){var a,d,h,e=this.options.rtl,t=0;this.allItems.forEach(function(n,f){a=n.legendGroup.translateX;d=n._legendItemPos[1];if((h=n.movementX)||e&&n.ranges)h=e?a-n.options.maxSize/2:a+h,n.legendGroup.attr({translateX:h});f>b[t].step&&t++;n.legendGroup.attr({translateY:Math.round(d+
b[t].height/2)});n._legendItemPos[1]=d+b[t].height/2})};a(z,"legendItemClick",function(){var b=this.chart,a=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=b.getVisibleBubbleSeriesIndex(),d.bubbleLegend.visible!==b&&(d.update({bubbleLegend:{enabled:b}}),d.bubbleLegend.visible=b),this.visible=a)});C(c.prototype,"drawChartBox",function(a,e,d){var h=this.legend,f=0<=this.getVisibleBubbleSeriesIndex();if(h&&h.options.enabled&&h.bubbleLegend&&h.options.bubbleLegend.autoRanges&&
f){var t=h.bubbleLegend.options;f=h.bubbleLegend.predictBubbleSizes();h.bubbleLegend.updateRanges(f[0],f[1]);t.placed||(h.group.placed=!1,h.allItems.forEach(function(d){d.legendGroup.translateY=null}));h.render();this.getMargins();this.axes.forEach(function(d){d.visible&&d.render();t.placed||(d.setScale(),d.updateNames(),b(d.ticks,function(d){d.isNew=!0;d.isNewLabel=!0}))});t.placed=!0;this.getMargins();a.call(this,e,d);h.bubbleLegend.correctSizes();h.retranslateItems(h.getLinesHeights())}else a.call(this,
e,d),h&&h.options.enabled&&h.bubbleLegend&&(h.render(),h.retranslateItems(h.getLinesHeights()))});k.BubbleLegend=x;return k.BubbleLegend});D(c,"Series/Bubble/BubbleSeries.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,g,e,r){var u=k.parse;k=g.noop;var E=r.arrayMax,B=r.arrayMin,A=r.clamp,b=r.extend,l=r.isNumber,x=r.pick,q=r.pInt,C=g.Series,z=a.seriesTypes;"";a.seriesType("bubble",
"scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],
specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(b,a){var e=this.options.marker.fillOpacity;b=C.prototype.pointAttribs.call(this,b,a);1!==e&&(b.fill=u(b.fill).setOpacity(e).get("rgba"));return b},getRadii:function(b,a,e){var d=this.zData,h=this.yData,f=e.minPxSize,t=e.maxPxSize,n=[];var l=0;for(e=d.length;l<e;l++){var g=d[l];n.push(this.getRadius(b,a,f,t,g,h[l]))}this.radii=n},getRadius:function(b,a,e,d,h,g){var t=this.options,n="width"!==t.sizeBy,
f=t.zThreshold,v=a-b,c=.5;if(null===g||null===h)return null;if(l(h)){t.sizeByAbsoluteValue&&(h=Math.abs(h-f),v=Math.max(a-f,Math.abs(b-f)),b=0);if(h<b)return e/2-1;0<v&&(c=(h-b)/v)}n&&0<=c&&(c=Math.sqrt(c));return Math.ceil(e+c*(d-e))/2},animate:function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var a=b.graphic;a&&a.width&&(this.hasRendered||a.attr({x:b.plotX,y:b.plotY,width:1,height:1}),a.animate(this.markerAttribs(b),this.options.animation))},this)},
hasData:function(){return!!this.processedXData.length},translate:function(){var a,e=this.data,f=this.radii;z.scatter.prototype.translate.call(this);for(a=e.length;a--;){var d=e[a];var h=f?f[a]:0;l(h)&&h>=this.minPxSize/2?(d.marker=b(d.marker,{radius:h,width:2*h,height:2*h}),d.dlBox={x:d.plotX-h,y:d.plotY-h,width:2*h,height:2*h}):d.shapeArgs=d.plotY=d.dlBox=void 0}},alignDataLabel:z.column.prototype.alignDataLabel,buildKDTree:k,applyZones:k},{haloPath:function(b){return e.prototype.haloPath.call(this,
0===b?0:(this.marker?this.marker.radius||0:0)+b)},ttBelow:!1});c.prototype.beforePadding=function(){var b=this,a=this.len,e=this.chart,d=0,h=a,g=this.isXAxis,t=g?"xData":"yData",n=this.min,c={},k=Math.min(e.plotWidth,e.plotHeight),r=Number.MAX_VALUE,u=-Number.MAX_VALUE,z=this.max-n,F=a/z,C=[];this.series.forEach(function(d){var a=d.options;!d.bubblePadding||!d.visible&&e.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=!0,C.push(d),g&&(["minSize","maxSize"].forEach(function(d){var b=a[d],h=/%$/.test(b);
b=q(b);c[d]=h?k*b/100:b}),d.minPxSize=c.minSize,d.maxPxSize=Math.max(c.maxSize,c.minSize),d=d.zData.filter(l),d.length&&(r=x(a.zMin,A(B(d),!1===a.displayNegative?a.zThreshold:-Number.MAX_VALUE,r)),u=x(a.zMax,Math.max(u,E(d))))))});C.forEach(function(a){var e=a[t],f=e.length;g&&a.getRadii(r,u,a);if(0<z)for(;f--;)if(l(e[f])&&b.dataMin<=e[f]&&e[f]<=b.max){var c=a.radii?a.radii[f]:0;d=Math.min((e[f]-n)*F-c,d);h=Math.max((e[f]-n)*F+c,h)}});C.length&&0<z&&!this.logarithmic&&(h-=a,F*=(a+Math.max(0,d)-Math.min(h,
a))/a,[["min","userMin",d],["max","userMax",h]].forEach(function(d){"undefined"===typeof x(b.options[d[0]],b[d[1]])&&(b[d[0]]+=d[2]/F)}))};""});D(c,"Series/Networkgraph/DraggableNodes.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k){var g=k.addEvent;a.dragNodesMixin={onMouseDown:function(a,g){g=this.chart.pointer.normalize(g);a.fixedPosition={chartX:g.chartX,chartY:g.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,g){if(a.fixedPosition&&
a.inDragMode){var e=this.chart;g=e.pointer.normalize(g);var c=a.fixedPosition.chartX-g.chartX,k=a.fixedPosition.chartY-g.chartY;g=e.graphLayoutsLookup;if(5<Math.abs(c)||5<Math.abs(k))c=a.fixedPosition.plotX-c,k=a.fixedPosition.plotY-k,e.isInsidePlot(c,k)&&(a.plotX=c,a.plotY=k,a.hasDragged=!0,this.redrawHalo(a),g.forEach(function(a){a.restartSimulation()}))}},onMouseUp:function(a,g){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=
a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};g(c,"load",function(){var a=this,c,k,E;a.container&&(c=g(a.container,"mousedown",function(e){var c=a.hoverPoint;c&&c.series&&c.series.hasDraggableNodes&&c.series.options.draggable&&(c.series.onMouseDown(c,e),k=g(a.container,"mousemove",function(b){return c&&c.series&&c.series.onMouseMove(c,b)}),E=g(a.container.ownerDocument,
"mouseup",function(b){k();E();return c&&c.series&&c.series.onMouseUp(c,b)}))}));g(a,"destroy",function(){c()})})});D(c,"Series/Networkgraph/Integrations.js",[c["Core/Globals.js"]],function(c){c.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,c){return(c-a)/a},repulsiveForceFunction:function(a,c){return(c-a)/a*(c>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,g=this.barycenter.yFactor;c=(c-(this.box.left+this.box.width)/2)*a;g=
(g-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=c/a.mass/a.degree,a.plotY-=g/a.mass/a.degree)})},repulsive:function(a,c,g){c=c*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=g.x*c,a.plotY+=g.y*c)},attractive:function(a,c,g){var e=a.getMass(),k=-g.x*c*this.diffTemperature;c=-g.y*c*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=k*e.fromNode/a.fromNode.degree,a.fromNode.plotY-=c*e.fromNode/a.fromNode.degree);a.toNode.fixedPosition||
(a.toNode.plotX+=k*e.toNode/a.toNode.degree,a.toNode.plotY+=c*e.toNode/a.toNode.degree)},integrate:function(a,c){var g=-a.options.friction,e=a.options.maxSpeed,k=(c.plotX+c.dispX-c.prevX)*g;g*=c.plotY+c.dispY-c.prevY;var u=Math.abs,E=u(k)/(k||1);u=u(g)/(g||1);k=E*Math.min(e,Math.abs(k));g=u*Math.min(e,Math.abs(g));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=k;c.plotY+=g;c.temperature=a.vectorLength({x:k,y:g})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)}},
euler:{attractiveForceFunction:function(a,c){return a*a/c},repulsiveForceFunction:function(a,c){return c*c/a},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,g=this.barycenter.yFactor;this.nodes.forEach(function(e){if(!e.fixedPosition){var k=e.getDegree();k*=1+k/2;e.dispX+=(c-e.plotX)*a*k/e.degree;e.dispY+=(g-e.plotY)*a*k/e.degree}})},repulsive:function(a,c,g,e){a.dispX+=g.x/e*c/a.degree;a.dispY+=g.y/e*c/a.degree},attractive:function(a,c,g,e){var k=a.getMass(),
u=g.x/e*c;c*=g.y/e;a.fromNode.fixedPosition||(a.fromNode.dispX-=u*k.fromNode/a.fromNode.degree,a.fromNode.dispY-=c*k.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=u*k.toNode/a.toNode.degree,a.toNode.dispY+=c*k.toNode/a.toNode.degree)},integrate:function(a,c){c.dispX+=c.dispX*a.options.friction;c.dispY+=c.dispY*a.options.friction;var g=c.temperature=a.vectorLength({x:c.dispX,y:c.dispY});0!==g&&(c.plotX+=c.dispX/g*Math.min(Math.abs(c.dispX),a.temperature),c.plotY+=c.dispY/g*Math.min(Math.abs(c.dispY),
a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.3)}}}});D(c,"Series/Networkgraph/QuadTree.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a){a=a.extend;var k=c.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};a(k.prototype,{insert:function(a,c){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,c-1):(this.isEmpty=!1,this.body?c?(this.isInternal=!0,
this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,c-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,c-1)):(c=new k({top:a.plotX,left:a.plotY,width:.1,height:.1}),c.body=a,c.isInternal=!1,this.nodes.push(c)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,c=0,k=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(a+=e.mass,c+=e.plotX*e.mass,k+=e.plotY*e.mass)}),c/=a,k/=a):this.body&&(a=this.body.mass,c=this.body.plotX,
k=this.body.plotY);this.mass=a;this.plotX=c;this.plotY=k},divideBox:function(){var a=this.box.width/2,c=this.box.height/2;this.nodes[0]=new k({left:this.box.left,top:this.box.top,width:a,height:c});this.nodes[1]=new k({left:this.box.left+a,top:this.box.top,width:a,height:c});this.nodes[2]=new k({left:this.box.left+a,top:this.box.top+c,width:a,height:c});this.nodes[3]=new k({left:this.box.left,top:this.box.top+c,width:a,height:c})},getBoxPosition:function(a){var c=a.plotY<this.box.top+this.box.height/
2;return a.plotX<this.box.left+this.box.width/2?c?0:3:c?1:2}});c=c.QuadTree=function(a,c,r,u){this.box={left:a,top:c,width:r,height:u};this.maxDepth=25;this.root=new k(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(c.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,c,k){var e;a||(a=this.root);a===this.root&&c&&(e=c(a));!1!==e&&(a.nodes.forEach(function(a){if(a.isInternal){c&&(e=c(a));
if(!1===e)return;this.visitNodeRecursive(a,c,k)}else a.body&&c&&c(a.body);k&&k(a)},this),a===this.root&&k&&k(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});D(c,"Series/Networkgraph/Layouts.js",[c["Core/Chart/Chart.js"],c["Core/Animation/AnimationUtilities.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k,g){var e=a.setAnimation;a=g.addEvent;var r=g.clamp,u=g.defined,E=g.extend,B=g.isFunction,A=g.pick;k.layouts={"reingold-fruchterman":function(){}};
E(k.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=k.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=A(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=A(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=
A(a,this.options.enableSimulation)},start:function(){var a=this.series,c=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(c);this.enableSimulation&&this.step()},step:function(){var a=this,c=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+
"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(c.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&k.win.cancelAnimationFrame(a.simulation),a.simulation=k.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&
k.win.cancelAnimationFrame(this.simulation)},setArea:function(a,c,e,g){this.box={left:a,top:c,width:e,height:g}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,c){a.forEach(function(a){-1===c.indexOf(a)&&c.push(a)})},removeElementFromCollection:function(a,c){a=c.indexOf(a);-1!==a&&c.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=
!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},setMaxIterations:function(a){this.maxIterations=A(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=
this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new k.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;B(a)?(a.call(this),this.nodes.forEach(function(a){u(a.prevX)||(a.prevX=a.plotX);u(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},
setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(d){p[d.toNode.id]||(p[d.toNode.id]=!0,r.push(d.toNode),a(d.toNode))})}var c=this.box,e=this.nodes,g=2*Math.PI/(e.length+1),k=e.filter(function(a){return 0===a.linksTo.length}),r=[],p={},m=this.options.initialPositionRadius;k.forEach(function(b){r.push(b);a(b)});r.length?e.forEach(function(a){-1===r.indexOf(a)&&r.push(a)}):r=e;r.forEach(function(a,d){a.plotX=a.prevX=A(a.plotX,c.width/2+m*Math.cos(d*g));a.plotY=a.prevY=A(a.plotY,
c.height/2+m*Math.sin(d*g));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var c=this.box,e=this.nodes,g=e.length+1;e.forEach(function(b,e){b.plotX=b.prevX=A(b.plotX,c.width*a(e));b.plotY=b.prevY=A(b.plotY,c.height*a(g+e));b.dispX=0;b.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=
0,c=0,e=0;this.nodes.forEach(function(b){c+=b.plotX*b.mass;e+=b.plotY*b.mass;a+=b.mass});return this.barycenter={x:c,y:e,xFactor:c/a,yFactor:e/a}},barnesHutApproximation:function(a,c){var b=this.getDistXY(a,c),e=this.vectorLength(b);if(a!==c&&0!==e)if(c.isInternal)if(c.boxSize/e<this.options.theta&&0!==e){var g=this.repulsiveForce(e,this.k);this.force("repulsive",a,g*c.mass,b,e);var l=!1}else l=!0;else g=this.repulsiveForce(e,this.k),this.force("repulsive",a,g*c.mass,b,e);return l},repulsiveForces:function(){var a=
this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){if(b!==c&&!b.fixedPosition){var e=a.getDistXY(b,c);var g=a.vectorLength(e);if(0!==g){var l=a.repulsiveForce(g,a.k);a.force("repulsive",b,l*c.mass,e,g)}}})})},attractiveForces:function(){var a=this,c,e,g;a.links.forEach(function(b){b.fromNode&&b.toNode&&(c=a.getDistXY(b.fromNode,b.toNode),e=a.vectorLength(c),
0!==e&&(g=a.attractiveForce(e,a.k),a.force("attractive",b,g,c,e)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,c){var b=a.radius;a.plotX=r(a.plotX,c.left+b,c.width-b);a.plotY=r(a.plotY,c.top+b,c.height-b)},coolDown:function(a,c,e){return a-c*e},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},
getSystemTemperature:function(){return this.nodes.reduce(function(a,c){return a+c.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,c){a=this.getDistXY(a,c);return this.vectorLength(a)},getDistXY:function(a,c){var b=a.plotX-c.plotX;a=a.plotY-c.plotY;return{x:b,y:a,absX:Math.abs(b),absY:Math.abs(a)}}});a(c,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});a(c,"render",function(){function a(a){a.maxIterations--&&
isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),g=!1,c=!0)}var c=!1;if(this.graphLayoutsLookup){e(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!g;){var g=!0;this.graphLayoutsLookup.forEach(a)}c&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});a(c,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),this.redraw())});a(c,"afterPrint",function(){this.graphLayoutsLookup&&
this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});D(c,"Series/PackedBubbleSeries.js",[c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,g,e,r){var u=k.parse,E=r.addEvent,B=r.clamp,A=r.defined,b=r.extend;k=r.extendClass;var l=r.fireEvent,x=r.isArray,q=r.isNumber,C=r.merge,z=r.pick,p=g.Series,m=g.layouts["reingold-fruchterman"],f=g.dragNodesMixin;"";a.prototype.getSelectedParentNodes=
function(){var a=[];this.series.forEach(function(d){d.parentNode&&d.parentNode.selected&&a.push(d.parentNode)});return a};g.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,c,e){return Math.min(a,(c.marker.radius+e.marker.radius)/2)},barycenter:function(){var a=this,b=a.options.gravitationalConstant,c=a.box,e=a.nodes,n,f;e.forEach(function(d){a.options.splitSeries&&!d.isParentNode?(n=d.series.parentNode.plotX,f=d.series.parentNode.plotY):(n=c.width/2,f=c.height/2);d.fixedPosition||
(d.plotX-=(d.plotX-n)*b/(d.mass*Math.sqrt(e.length)),d.plotY-=(d.plotY-f)*b/(d.mass*Math.sqrt(e.length)))})},repulsive:function(a,b,c,e){var d=b*this.diffTemperature/a.mass/a.degree;b=c.x*d;c=c.y*d;a.fixedPosition||(a.plotX+=b,a.plotY+=c);e.fixedPosition||(e.plotX-=b,e.plotY-=c)},integrate:g.networkgraphIntegrations.verlet.integrate,getK:g.noop};g.layouts.packedbubble=k(m,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=
this,b=a.box,c=a.nodes,e=2*Math.PI/(c.length+1),n,f,g=a.options.initialPositionRadius;c.forEach(function(d,c){a.options.splitSeries&&!d.isParentNode?(n=d.series.parentNode.plotX,f=d.series.parentNode.plotY):(n=b.width/2,f=b.height/2);d.plotX=d.prevX=z(d.plotX,n+g*Math.cos(d.index||c*e));d.plotY=d.prevY=z(d.plotY,f+g*Math.sin(d.index||c*e));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,b,c,e,n=a.options.bubblePadding;a.nodes.forEach(function(d){d.degree=d.mass;d.neighbours=0;a.nodes.forEach(function(h){b=
0;d===h||d.fixedPosition||!a.options.seriesInteraction&&d.series!==h.series||(e=a.getDistXY(d,h),c=a.vectorLength(e)-(d.marker.radius+h.marker.radius+n),0>c&&(d.degree+=.01,d.neighbours++,b=a.repulsiveForce(-c/Math.sqrt(d.neighbours),a.k,d,h)),a.force("repulsive",d,b*h.mass,e,h,c))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var d=this.getDistXY(a,a.series.parentNode);var b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(d);
0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*d.x,a.plotY-=.01*d.y)}m.prototype.applyLimitBox.apply(this,arguments)}});c.seriesType("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},
layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},
{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],trackerGroups:["group","dataLabelsGroup","parentNodesGroup"],pointValKey:"value",isCartesian:!1,requireSorting:!1,directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:g.noop,accumulateAllPoints:function(a){var d=a.chart,b=[],c,e;for(c=0;c<d.series.length;c++)if(a=d.series[c],a.is("packedbubble")&&a.visible||!d.options.chart.ignoreHiddenSeries)for(e=0;e<a.yData.length;e++)b.push([null,null,a.yData[e],a.index,e,{id:e,
marker:{radius:0}}]);return b},init:function(){p.prototype.init.apply(this,arguments);E(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},render:function(){var a=[];p.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(d){x(d.dataLabels)&&d.dataLabels.forEach(function(d){a.push(d)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=
this;p.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(d){a.layout.removeElementFromCollection(d,a.layout.nodes)}))},drawDataLabels:function(){var a=
this.options.dataLabels.textPath,b=this.points;p.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,p.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,c=Math.min,e,n=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){A(a.plotX)&&
A(a.plotY)&&a.marker.radius&&(e=a.marker.radius,n[0]=c(n[0],a.plotX-e),n[1]=b(n[1],a.plotX+e),n[2]=c(n[2],a.plotY-e),n[3]=b(n[3],a.plotY+e))});return q(n.width/n.height)?n:null},calculateParentRadius:function(){var a=this.seriesBox();this.parentNodeRadius=B(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},
drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||u(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=C({x:this.parentNode.plotX-
this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,e,n=a.parentNode,f=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(d){a.parentNodeMass+=Math.PI*Math.pow(d.marker.radius,2)});a.calculateParentRadius();
c.nodes.forEach(function(d){d.seriesIndex===a.index&&(e=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);e||(n||(n=(new f).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(n.plotX=a.parentNode.plotX,n.plotY=a.parentNode.plotY),a.parentNode=n,c.addElementsToCollection([a],c.series),c.addElementsToCollection([n],c.nodes))},drawTracker:function(){var a=this.parentNode;
g.TrackerMixin.drawTrackerPoint.call(this);if(a){var b=x(a.dataLabels)?a.dataLabels:a.dataLabel?[a.dataLabel]:[];a.graphic&&(a.graphic.element.point=a);b.forEach(function(d){d.div?d.div.point=a:d.element.point=a})}},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,e=C(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var n=b[a.type+"-series"];n||(b[a.type+"-series"]=n=new g.layouts[a.type],n.init(e),
c.splice(n.index,0,n));this.parentNodeLayout=n;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,e=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=c=[]);var n=b[a.type];n||(a.enableSimulation=A(e.forExport)?!e.forExport:a.enableSimulation,b[a.type]=n=new g.layouts[a.type],n.init(a),c.splice(n.index,0,n));this.layout=n;this.points.forEach(function(a){a.mass=
2;a.degree=1;a.collisionNmb=1});n.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);n.addElementsToCollection([this],n.series);n.addElementsToCollection(this.points,n.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,c=this.data,e=this.index,f,n=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();A(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),
this.getPointRadius());if(n)var g=a.allDataPoints;else g=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(f=0;f<g.length;f++)if(g[f][3]===e){var k=c[g[f][4]];var m=g[f][2];n||(k.plotX=g[f][0]-a.plotLeft+a.diffX,k.plotY=g[f][1]-a.plotTop+a.diffY);k.marker=b(k.marker,{radius:m,width:2*m,height:2*m});k.radius=m}n&&this.deferLayout();l(this,"afterTranslate")},checkOverlap:function(a,b){var d=a[0]-b[0],c=a[1]-b[1];return-.001>Math.sqrt(d*d+c*c)-Math.abs(a[2]+b[2])},positionBubble:function(a,
b,c){var d=Math.sqrt,h=Math.asin,e=Math.acos,f=Math.pow,g=Math.abs;d=d(f(a[0]-b[0],2)+f(a[1]-b[1],2));e=e((f(d,2)+f(c[2]+b[2],2)-f(c[2]+a[2],2))/(2*(c[2]+b[2])*d));h=h(g(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+e+h*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var d=this.checkOverlap,b=this.positionBubble,c=[],e=1,f=0,g=0;var k=[];var l;a=a.sort(function(a,d){return d[2]-a[2]});if(a.length){c.push([[0,0,a[0][2],
a[0][3],a[0][4]]]);if(1<a.length)for(c.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),l=2;l<a.length;l++)a[l][2]=a[l][2]||1,k=b(c[e][f],c[e-1][g],a[l]),d(k,c[e][0])?(c.push([]),g=0,c[e+1].push(b(c[e][f],c[e][0],a[l])),e++,f=0):1<e&&c[e-1][g+1]&&d(k,c[e-1][g+1])?(g++,c[e].push(b(c[e][f],c[e-1][g],a[l])),f++):(f++,c[e].push(k));this.chart.stages=c;this.chart.rawPositions=[].concat.apply([],c);this.resizeRadius();k=this.chart.rawPositions}return k},resizeRadius:function(){var a=this.chart,b=a.rawPositions,
c=Math.min,e=Math.max,f=a.plotLeft,g=a.plotTop,l=a.plotHeight,k=a.plotWidth,m,q,p;var r=m=Number.POSITIVE_INFINITY;var u=q=Number.NEGATIVE_INFINITY;for(p=0;p<b.length;p++){var x=b[p][2];r=c(r,b[p][0]-x);u=e(u,b[p][0]+x);m=c(m,b[p][1]-x);q=e(q,b[p][1]+x)}p=[u-r,q-m];c=c.apply([],[(k-f)/p[0],(l-g)/p[1]]);if(1e-10<Math.abs(c-1)){for(p=0;p<b.length;p++)b[p][2]*=c;this.placeBubbles(b)}else a.diffY=l/2+g-m-(q-m)/2,a.diffX=k/2+f-r-(u-r)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,
c=Infinity,e=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){A(a)&&(a>e&&(e=a),a<c&&(c=a))})});a=z(a,c);b=z(b,e);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,e=c.useSimulation,f=Math.min(b.plotWidth,b.plotHeight),g={},l=[],k=b.allDataPoints,m,p,q,r;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),d=/%$/.test(c[a]);g[a]=d?f*b/100:b*Math.sqrt(k.length)});b.minRadius=m=g.minSize/Math.sqrt(k.length);b.maxRadius=
p=g.maxSize/Math.sqrt(k.length);var u=e?a.calculateZExtremes():[m,p];(k||[]).forEach(function(b,d){q=e?B(b[2],u[0],u[1]):b[2];r=a.getRadius(u[0],u[1],m,p,q);0===r&&(r=null);k[d][2]=r;l.push(r)});a.radii=l},redrawHalo:f.redrawHalo,onMouseDown:f.onMouseDown,onMouseMove:f.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,c,d=this.layout,e=this.parentNodeLayout;e&&d.options.dragBetweenSeries&&e.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(b=d.getDistXY(a,e),c=
d.vectorLength(b)-e.marker.radius-a.marker.radius,0>c&&(e.series.addPoint(C(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),d.removeElementFromCollection(a,d.nodes),a.remove()))});f.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&
(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));g.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:g.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return e.prototype.destroy.apply(this,arguments)},firePointEvent:function(a,b,c){var d=this.series.options;if(this.isParentNode&&d.parentNode){var h=d.allowPointSelect;d.allowPointSelect=d.parentNode.allowPointSelect;e.prototype.firePointEvent.apply(this,
arguments);d.allowPointSelect=h}else e.prototype.firePointEvent.apply(this,arguments)},select:function(b,c){var d=this.series.chart;this.isParentNode?(d.getSelectedPoints=d.getSelectedParentNodes,e.prototype.select.apply(this,arguments),d.getSelectedPoints=a.prototype.getSelectedPoints):e.prototype.select.apply(this,arguments)}});E(a,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});D(c,"Extensions/Polar.js",[c["Core/Animation/AnimationUtilities.js"],c["Core/Chart/Chart.js"],
c["Core/Globals.js"],c["Extensions/Pane.js"],c["Core/Pointer.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,a,k,g,e,r,u){var E=c.animObject,B=u.addEvent,A=u.defined,b=u.find,l=u.isNumber,x=u.pick,q=u.splat,C=u.uniqueKey;c=u.wrap;var z=k.Series,p=k.seriesTypes,m=z.prototype;e=e.prototype;m.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};
m.getConnectors=function(a,b,c,e){var d=e?1:0;var h=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>h-1?a.length-(1+d):h-1;d=h+1>a.length-1?d:h+1;var f=a[b];d=a[d];var g=f.plotX;f=f.plotY;var k=d.plotX;var l=d.plotY;d=a[h].plotX;h=a[h].plotY;g=(1.5*d+g)/2.5;f=(1.5*h+f)/2.5;k=(1.5*d+k)/2.5;var t=(1.5*h+l)/2.5;l=Math.sqrt(Math.pow(g-d,2)+Math.pow(f-h,2));var m=Math.sqrt(Math.pow(k-d,2)+Math.pow(t-h,2));g=Math.atan2(f-h,g-d);t=Math.PI/2+(g+Math.atan2(t-h,k-d))/2;Math.abs(g-t)>Math.PI/2&&(t-=Math.PI);g=
d+Math.cos(t)*l;f=h+Math.sin(t)*l;k=d+Math.cos(Math.PI+t)*m;t=h+Math.sin(Math.PI+t)*m;d={rightContX:k,rightContY:t,leftContX:g,leftContY:f,plotX:d,plotY:h};c&&(d.prevPointCont=this.getConnectors(a,b,!1,e));return d};m.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var e=a.plotX,f=a.plotY,g=a.series,k=b.inverted,l=a.y,m=k?e:d.len-f;k&&g&&!g.isRadialBar&&(a.plotY=f="number"===typeof l?d.translate(l)||0:0);a.rectPlotX=e;a.rectPlotY=f;d.center&&(m+=d.center[3]/2);d=k?d.postTranslate(f,
m):c.postTranslate(e,m);a.plotX=a.polarPlotX=d.x-b.plotLeft;a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};p.spline&&(c(p.spline.prototype,"getPointSpline",function(a,b,c,e){this.chart.polar?e?(a=this.getConnectors(b,e,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,e);return a}),p.areasplinerange&&
(p.areasplinerange.prototype.getPointSpline=p.spline.prototype.getPointSpline));B(z,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var b=this.points,c=b.length;c--;)this.toXY(b[c]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&b[c].y<this.yAxis.min&&(b[c].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=
!!this.eventsToUnbind.push(B(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=k.noop}})))}},{order:2});c(m,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=
!0;b.splice(b.length,0,b[e]);var h=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));h&&b.pop();return d});var f=function(a,b){var c=this,d=this.chart,e=this.options.animation,h=this.group,f=this.markerGroup,g=this.xAxis.center,l=d.plotLeft,m=d.plotTop,p,q,r,u;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=x(c.translatedThreshold,c.xAxis.startAngleRad),k.seriesTypes.pie.prototype.animate.call(c,b));else{if(d.renderer.isSVG)if(e=E(e),
c.is("column")){if(!b){var A=g[3]/2;c.points.forEach(function(a){p=a.graphic;r=(q=a.shapeArgs)&&q.r;u=q&&q.innerR;p&&q&&(p.attr({r:A,innerR:A}),p.animate({r:r,innerR:u},c.options.animation))})}}else b?(a={translateX:g[0]+l,translateY:g[1]+m,scaleX:.001,scaleY:.001},h.attr(a),f&&f.attr(a)):(a={translateX:l,translateY:m,scaleX:1,scaleY:1},h.animate(a,e),f&&f.animate(a,e))}else a.call(this,b)};c(m,"animate",f);p.column&&(z=p.arearange.prototype,p=p.column.prototype,p.polarArc=function(a,b,c,e){var d=
this.xAxis.center,h=this.yAxis.len,f=d[3]/2;b=h-b+f;a=h-x(a,h)+f;this.yAxis.reversed&&(0>b&&(b=f),0>a&&(a=f));return{x:d[0],y:d[1],r:b,innerR:a,start:c,end:e}},c(p,"animate",f),c(p,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,e=this.xAxis,f=this.yAxis,g=f.reversed,k=f.center,m=e.startAngleRad,p=e.endAngleRad-m;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var q=f.translate(f.min);var r=f.translate(f.max);b=b.threshold||0;if(d.inverted&&l(b)){var x=
f.translate(b);A(x)&&(0>x?x=0:x>p&&(x=p),this.translatedThreshold=x+m)}for(;e--;){b=a[e];var z=b.barX;var B=b.x;var E=b.y;b.shapeType="arc";if(d.inverted){b.plotY=f.translate(E);if(c&&f.stacking){if(E=f.stacking.stacks[(0>E?"-":"")+this.stackKey],this.visible&&E&&E[B]&&!b.isNull){var C=E[B].points[this.getStackIndicator(void 0,B,this.index).key];var D=f.translate(C[0]);C=f.translate(C[1]);A(D)&&(D=u.clamp(D,0,p))}}else D=x,C=b.plotY;D>C&&(C=[D,D=C][0]);if(!g)if(D<q)D=q;else if(C>r)C=r;else{if(C<q||
D>r)D=C=0}else if(C>q)C=q;else if(D<r)D=r;else if(D>q||C<r)D=C=p;f.min>f.max&&(D=C=g?p:0);D+=m;C+=m;k&&(b.barX=z+=k[3]/2);B=Math.max(z,0);E=Math.max(z+b.pointWidth,0);b.shapeArgs={x:k&&k[0],y:k&&k[1],r:E,innerR:B,start:D,end:C};b.opacity=D===C?0:void 0;b.plotY=(A(this.translatedThreshold)&&(D<this.translatedThreshold?D:C))-m}else D=z+m,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,D,D+b.pointWidth);this.toXY(b);d.inverted?(z=f.postTranslate(b.rectPlotY,z+b.pointWidth/2),b.tooltipPos=[z.x-d.plotLeft,
z.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];k&&(b.ttBelow=b.plotY>k[1])}}}),p.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b},z&&(z.findAlignments=p.findAlignments),c(p,"alignDataLabel",function(a,b,c,e,f,g){var d=this.chart,h=x(e.inside,!!this.options.stacking);d.polar?(a=b.rectPlotX/Math.PI*180,d.inverted?(this.forceDL=d.isInsidePlot(b.plotX,
Math.round(b.plotY),!1),h&&b.shapeArgs?(f=b.shapeArgs,f=this.yAxis.postTranslate((f.start+f.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),f={x:f.x-d.plotLeft,y:f.y-d.plotTop}):b.tooltipPos&&(f={x:b.tooltipPos[0],y:b.tooltipPos[1]}),e.align=x(e.align,"center"),e.verticalAlign=x(e.verticalAlign,"middle")):this.findAlignments&&(e=this.findAlignments(a,e)),m.alignDataLabel.call(this,b,c,e,f,g),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,e,f,
g)}));c(e,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});r.prototype.clipCircle=function(a,b,c,e){var d=C(),f=this.createElement("clipPath").attr({id:d}).add(this.defs);a=e?this.arc(a,
b,c,e,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=d;a.clipPath=f;return a};B(a,"getAxes",function(){this.pane||(this.pane=[]);q(this.options.pane).forEach(function(a){new g(a,this)},this)});B(a,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});B(k.Series,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});c(a.prototype,"get",function(a,c){return b(this.pane,function(a){return a.options.id===
c})||a.call(this,c)})});D(c,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map